ALTER TABLE REP_UNIDADES_CIEE DROP COLUMN ID_DOMINIO_PAI;

CREATE TABLE {{user}}.REP_DOMINIOS_UNIT (
    ID NUMBER(20) NOT NULL,
    DESCRICAO VARCHAR2(255 CHAR),
    ID_DOMINIO_PAI NUMBER(20),
    INTERNO_CIEE NUMBER(1,0),
    ATIVO NUMBER(1,0)
);