--
-- View para buscar as resultado do processo seletivo
--
CREATE OR REPLACE VIEW  V_CANDIDATOS_RESULTADO_ULTIMA_ETAPA AS
SELECT
    *
FROM 
    (SELECT
        E.ID AS ID_ESTUDANTE_AGENDA, V.ID_ESTUDANTE, RE.NOME, V.CODIGO_VAGA, E.ID_VINCULO_VAGA,
        S.ID AS ID_ETAPA_PROCESSO_SELETIVO, S.ORDEM_ETAPA, R.SITUACAO,
        RANK() OVER ( PARTITION BY E.ID_VINCULO_VAGA ORDER BY E.ID_VINCULO_VAGA, S.ORDEM_ETAPA DESC) RANK
    FROM
        ESTUDANTES_AGENDA E
    INNER JOIN
        VINCULOS_VAGA V ON E.ID_VINCULO_VAGA = V.ID
    INNER JOIN
        REP_ESTUDANTES RE ON V.ID_ESTUDANTE = RE.ID
    LEFT JOIN
        RESULTADOS_PROCESSO_SELETIVO R ON E.ID = R.ID_ESTUDANTE_AGENDA
    INNER JOIN
        AGENDA_PROCESSO_SELETIVO A ON E.ID_AGENDA_PROCESSO_SELETIVO = A.ID
    INNER JOIN
        ETAPAS_PROCESSO_SELETIVO S ON A.ID_ETAPA_PROCESSO_SELETIVO = S.ID
    WHERE
        V.SITUACAO_VINCULO = 1 AND (R.ID IS NULL OR R.SITUACAO IS NOT NULL)
    ORDER BY
       E.ID_VINCULO_VAGA, S.ORDEM_ETAPA DESC)
WHERE
    RANK = 1
