
ALTER TABLE REP_INSTITUICOES_ENSINOS
ADD
  NIVEL_INSTITUICAO VARCHAR2(5 CHAR) NULL;

ALTER TABLE REP_INSTITUICOES_ENSINOS
  ADD CONSTRAINT krs_indice_02324 FOREIGN KEY ( ENDERECO )
    REFERENCES REP_ENDERECOS_ESCOLAS ( ID )
      NOT DEFERRABLE;

