ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO
    DROP COLUMN ID_CBO;

ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO
    DROP COLUMN DESCRICAO_CBO;

ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO
    DROP COLUMN ID_CBO;

ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO
    DROP COLUMN DESCRICAO_CBO;

ALTER TABLE HIST_CONTRATOS_CURSOS_CAPACITACAO
    DROP COLUMN ID_CBO;

ALTER TABLE HIST_CONTRATOS_CURSOS_CAPACITACAO
    DROP COLUMN DESCRICAO_CBO;

