ALTER TABLE PARAMS_CSE
    ADD TIPO_PRAZO NUMBER(2);

CREATE TABLE CONTROLE_COMUNICAO_CSE
(
    ID               NUMBER(20)  NOT NULL,
    ID_CSE           NUMBER(20)  NOT NULL,
    DATA_ENVIO       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    TIPO_PRAZO       NUMBER(2) NOT NULL
);

CREATE SEQUENCE SEQ_CONTROLE_COMUNICACAO_CSE MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE NOKEEP  NOSCALE  GLOBAL;

ALTER TABLE CONTROLE_COMUNICAO_CSE
    ADD CONSTRAINT KRS_INDICE_04200 PRIMARY KEY (ID);

ALTER TABLE CONTROLE_COMUNICAO_CSE
    ADD CONSTRAINT KRS_INDICE_04208 FOREIGN KEY (ID_CSE) REFERENCES CSE (ID);
