-- ## Atividades CIEE (CNAE)

CREATE TABLE REP_ATIVIDADES_CIEE
  (
    ID NUMBER(20) NOT NULL,
    CODIGO NUMBER(5,0) NOT NULL,
    DESCRICAO VARCHAR2(150 CHAR) NOT NULL,
    DELETADO NUMBER(1,0),
    DATA_CRIACAO TIMESTAMP (6) NOT NULL,
    DATA_ALTERACAO TIMESTAMP (6) NOT NULL,
    CRIADO_POR VARCHAR2(255 CHAR),
    MODIFICADO_POR VARCHAR2(255 CHAR)
    );

ALTER TABLE REP_ATIVIDADES_CIEE ADD CONSTRAINT KRS_INDICE_01808 PRIMARY KEY ( id );

-- ## Add coluna TIPO_SERVICO em REP_CONTRATOS (informação da vaga ESTAGIO ou APRENDIZ)

ALTER TABLE REP_CONTRATOS ADD TIPO_SERVICO VARCHAR2(50 CHAR);