CREATE TABLE REP_PESSOAS_TELEFONES
(ID_PESSOA NUMBER(19) not null,
ID_TELEFONE NUMBER(19) not null
);

ALTER TABLE REP_PESSOAS_TELEFONES ADD CONSTRAINT KRS_INDICE_03774 FOREIGN KEY
    (ID_PESSOA) REFERENCES REP_PESSOAS (ID);

ALTER TABLE REP_PESSOAS_TELEFONES ADD CONSTRAINT KRS_INDICE_03775 FOREIGN KEY
    (ID_TELEFONE) REFERENCES REP_TELEFONES_ESCOLA (ID);

ALTER TABLE REP_PESSOAS_TELEFONES ADD PRIMARY KEY (ID_PESSOA, ID_TELEFONE);




