create or replace view V_VINCULO_CLASSIFICACAO as
(
    select distinct case when RPS.SITUACAO IS NULL AND RPS.ID IS NOT NULL then 1 else 0 end "POSSUI_ETAPA_PENDENTE",
        VV.ID ID_VINCULO_VAGA,
        EXTRACT(DAY FROM SYSDATE - CASE WHEN RPS.SITUACAO IS NULL AND RPS.ID IS NOT NULL
                THEN CASE WHEN FS.TIPO_FERRAMENTA_SELECAO = 0 THEN APS.DATA
                    ELSE (SELECT MAX(NVL(DATA_FINAL, DATA_INICIO)) FROM ETAPAS_PERIODOS EP WHERE EPS.ID = EP.ID_ETAPA_PROCESSO_SELETIVO)
                END
                ELSE NVL(VE.DATA_CRIACAO, VA.DATA_CRIACAO) END
            ) "CALCULO_DATAS",
        NVL(EPS.ORDEM_ETAPA, 1) "ORDEM_ETAPA", EPS.ID
    FROM VINCULOS_VAGA VV
         LEFT JOIN VAGAS_ESTAGIO VE ON VE.CODIGO_DA_VAGA = VV.CODIGO_VAGA
         LEFT JOIN VAGAS_APRENDIZ VA ON VA.CODIGO_DA_VAGA = VV.CODIGO_VAGA
         LEFT JOIN ESTUDANTES_AGENDA EA ON VV.ID = EA.ID_VINCULO_VAGA
         LEFT JOIN AGENDA_PROCESSO_SELETIVO APS on EA.ID_AGENDA_PROCESSO_SELETIVO = APS.ID
         LEFT JOIN RESULTADOS_PROCESSO_SELETIVO RPS ON EA.ID = RPS.ID_ESTUDANTE_AGENDA
         LEFT JOIN ETAPAS_PROCESSO_SELETIVO EPS ON APS.ID_ETAPA_PROCESSO_SELETIVO = EPS.ID
         LEFT JOIN FERRAMENTAS_SELECAO FS on EPS.ID_FERRAMENTA_SELECAO = FS.ID
    where (EA.DELETADO IS NULL OR EA.DELETADO = 0)
    );