CREATE TABLE FERRAMENTAS_EMPRESAS (
    ID                        NUMBER(20) NOT NULL,
    ID_CONTRATO               NUMBER(20) NOT NULL,
    ID_FERRAMENTA             NUMBER(20) NOT NULL,
    DESCRICAO_TERMO_ADITIVO   VARCHAR2(20),
    DELETADO                  NUMBER,
    DATA_CRIACAO              TIMESTAMP NOT NULL,
    DATA_ALTERACAO            TIMESTAMP,
    CRIADO_POR                VARCHAR2(255),
    MODIFICADO_POR            VARCHAR2(255)
);

COMMENT ON TABLE FERRAMENTAS_EMPRESAS IS
    'OBS:

  A EMPRESA SÓ PODERA VINCULAR FERRAMENTAS SE: 

TER ADITIVO PP = SIM  NO CONTRATO EMPRESA
SE ADITIVO PP = NÃO, NÃO SERÁ POSSÍVEL DEFINIR AS FERRAMENTAS.

PARA ESSA INFORMAÇÃO NÃO HAVERÁ REPLICA, NA BASE DE COMPANY AS TABELAS ENVOLVIDAS SÃO:

CONFIGURACAO_CONTRATO E CONFIG_CONTRATOS_ESTAGIO
'
    ;

ALTER TABLE FERRAMENTAS_EMPRESAS ADD CONSTRAINT KRS_INDICE_01744 PRIMARY KEY ( ID );

ALTER TABLE FERRAMENTAS_EMPRESAS
    ADD CONSTRAINT KRS_INDICE_01745 FOREIGN KEY ( ID_CONTRATO )
        REFERENCES REP_CONTRATOS ( ID );

ALTER TABLE FERRAMENTAS_EMPRESAS
    ADD CONSTRAINT KRS_INDICE_01746 FOREIGN KEY ( ID_FERRAMENTA )
        REFERENCES FERRAMENTAS_SELECAO ( ID );

--------------------------------------------------------------------------------------------

CREATE TABLE ACOMPANHAMENTOS_VAGAS (
    ID                 NUMBER(20) NOT NULL,
    CODIGO_VAGA        NUMBER(20) NOT NULL,
    ID_STATUS_ACOMP    NUMBER(20) NOT NULL,
    DESCRICAO          VARCHAR2(200),
    CONTATO            VARCHAR2(60),
    DDD_FONE_CONTATO   VARCHAR2(2),
    FONE_CONTATO       VARCHAR2(60),
    TIPO_PROCESSO      NUMBER(1),
    TIPO_REGISTRO      NUMBER(1),
    DELETADO           NUMBER,
    DATA_CRIACAO       TIMESTAMP,
    DATA_ALTERACAO     TIMESTAMP,
    CRIADO_POR         VARCHAR2(255),
    MODIFICADO_POR     VARCHAR2(255)
);

COMMENT ON COLUMN ACOMPANHAMENTOS_VAGAS.TIPO_PROCESSO IS
    'ENUM:

0 - VAGAS
1 - CONTRATOS';

COMMENT ON COLUMN ACOMPANHAMENTOS_VAGAS.TIPO_REGISTRO IS
    'ENUM:

0 - MANUAL
1 - AUTOMATICO';

ALTER TABLE ACOMPANHAMENTOS_VAGAS ADD CONSTRAINT KRS_INDICE_01764 PRIMARY KEY ( ID );

CREATE TABLE AGENDA_EMPRESA_VAGA (
    ID                NUMBER(20) NOT NULL,
    ID_EMPRESA        NUMBER(20) NOT NULL,
    CODIGO_VAGA       NUMBER(20) NOT NULL,
    ID_STATUS_ACOMP   NUMBER(20) NOT NULL,
    ASSUNTO           CLOB,
    DATA_HORA         TIMESTAMP,
    DELETADO          NUMBER,
    DATA_CRIACAO      TIMESTAMP,
    DATA_ALTERACAO    TIMESTAMP,
    CRIADO_POR        VARCHAR2(255),
    MODIFICADO_POR    VARCHAR2(255)
);

ALTER TABLE AGENDA_EMPRESA_VAGA ADD CONSTRAINT KRS_INDICE_01766 PRIMARY KEY ( ID );

CREATE TABLE STATUS_ACOMPANHAMENTO (
    ID               NUMBER(20) NOT NULL,
    DESCRICAO        VARCHAR2(150),
    GERA_AGENDA      NUMBER,
    DELETADO         NUMBER,
    DATA_CRIACAO     TIMESTAMP,
    DATA_ALTERACAO   TIMESTAMP,
    CRIADO_POR       VARCHAR2(255),
    MODIFICADO_POR   VARCHAR2(255)
);

COMMENT ON COLUMN STATUS_ACOMPANHAMENTO.GERA_AGENDA IS
    'FLAG 0 OU 1

';

ALTER TABLE STATUS_ACOMPANHAMENTO ADD CONSTRAINT KRS_INDICE_01763 PRIMARY KEY ( ID );

ALTER TABLE ACOMPANHAMENTOS_VAGAS
    ADD CONSTRAINT KRS_INDICE_01765 FOREIGN KEY ( ID_STATUS_ACOMP )
        REFERENCES STATUS_ACOMPANHAMENTO ( ID );

ALTER TABLE AGENDA_EMPRESA_VAGA
    ADD CONSTRAINT KRS_INDICE_01767 FOREIGN KEY ( ID_STATUS_ACOMP )
        REFERENCES STATUS_ACOMPANHAMENTO ( ID );

ALTER TABLE AGENDA_EMPRESA_VAGA
    ADD CONSTRAINT KRS_INDICE_01769 FOREIGN KEY ( ID_EMPRESA )
        REFERENCES REP_EMPRESAS ( ID );
        
--------------------------------------------------------------------------------------------

CREATE SEQUENCE SEQ_FERRAMENTAS_EMPRESAS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;                                                   
CREATE SEQUENCE SEQ_ACOMPANHAMENTOS_VAGAS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;                                                     
CREATE SEQUENCE SEQ_AGENDA_EMPRESA_VAGA MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;


--------------------------------------------------------------------------------------------
-- ADD CAMPOS NA REPLICA DE ESTUDANTES
ALTER TABLE REP_ESTUDANTES ADD(
    NOME_SOCIAL VARCHAR2(255)
);


-- ADD CAMPOS NA REPLICA DE ENDERECOS ESTUDANTES

ALTER TABLE REP_ENDERECOS_ESTUDANTES ADD(
    ENDERECO VARCHAR2(150),
    NUMERO VARCHAR2(10),
    BAIRRO VARCHAR2(100),
    CIDADE VARCHAR2(100),
    UF VARCHAR2(2),
    CEP VARCHAR2(8)
);


-- CRIO A REPLICA DE INFORMACOES BRASILEIROS

CREATE TABLE REP_INFORMACOES_BRASILEIROS (
    ID               NUMBER(20) NOT NULL,
    RG               VARCHAR2(20),
    DELETADO         NUMBER,
    DATA_CRIACAO     TIMESTAMP,
    DATA_ALTERACAO   TIMESTAMP,
    CRIADO_POR       VARCHAR2(255),
    MODIFICADO_POR   VARCHAR2(255)
);
ALTER TABLE REP_INFORMACOES_BRASILEIROS ADD CONSTRAINT KRS_INDICE_01772 PRIMARY KEY ( ID );


-- CRIO A REPLICA DE TELEFONES

CREATE TABLE REP_TELEFONES (
    ID               NUMBER NOT NULL DISABLE NOVALIDATE,
    ID_ESTUDANTE     NUMBER(19) NOT NULL DISABLE NOVALIDATE,
    TELEFONE         VARCHAR2(255 BYTE) NOT NULL DISABLE NOVALIDATE,
    PRINCIPAL        NUMBER(1) DEFAULT 0,
    VERIFICADO       NUMBER(1) DEFAULT 0,
    DATA_CRIACAO     TIMESTAMP NOT NULL,
    DATA_ALTERACAO   TIMESTAMP NOT NULL,
    CRIADO_POR       VARCHAR2(255 BYTE),
    MODIFICADO_POR   VARCHAR2(255 BYTE),
    DELETADO         NUMBER(1),
    TIPO_TELEFONE    VARCHAR2(20 BYTE)
);

CREATE INDEX KRS_INDICE_01773 ON
    REP_TELEFONES (
        ID_ESTUDANTE
    ASC );

CREATE INDEX KRS_INDICE_01774 ON
    REP_TELEFONES (
        TELEFONE
    ASC,
        DELETADO
    ASC );

CREATE INDEX KRS_INDICE_01775 ON
    REP_TELEFONES (
        TIPO_TELEFONE
    ASC );

CREATE INDEX KRS_INDICE_01776 ON
    REP_TELEFONES (
        VERIFICADO
    ASC );

CREATE INDEX KRS_INDICE_01777 ON
    REP_TELEFONES (
        MODIFICADO_POR
    ASC );

ALTER TABLE REP_TELEFONES ADD CONSTRAINT KRS_INDICE_01778 PRIMARY KEY ( ID );                                                
