
CREATE TABLE REP_ENDERECOS_ESCOLAS
(
  ID             NUMBER(19)       NOT NULL,
  ENDERECO       VARCHAR2(150 CHAR),
  CIDADE         VARCHAR2(100 CHAR),
  COMPLEMENTO    VARCHAR2(50 CHAR),
  BAIRRO         VARCHAR2(100 CHAR),
  NUMERO         VARCHAR2(10 CHAR),
  UF             VARCHAR2(2 CHAR),
  TIPO           VARCHAR2(40 CHAR),
  CEP            VARCHAR2(8 CHAR) NOT NULL,
  TIPO_CEP       NUMBER,
  DELETADO       NUMBER(1)        NOT NULL,
  DATA_CRIACAO   TIMESTAMP(6)     NOT NULL,
  DATA_ALTERACAO TIMESTAMP(6)     NOT NULL,
  CRIADO_POR     VARCHAR2(255 CHAR),
  MODIFICADO_POR VARCHAR2(255 CHAR)
);

ALTER TABLE REP_ENDERECOS_ESCOLAS ADD CONSTRAINT krs_indice_01989 PRIMARY KEY (ID) ;

ALTER TABLE REP_CAMPUS
ADD ID_ENDERECO NUMBER;

ALTER TABLE REP_CAMPUS
ADD CONSTRAINT krs_indice_02003 FOREIGN KEY (ID_ENDERECO)
REFERENCES REP_ENDERECOS_ESCOLAS (ID);
