/* Alterações na tabela PRE_CONTRATOS_CURSOS_CAPACITACAO após alinhamentos e mudanças da
 estória Solicitar matrícula do aprendiz CIEE Capacitador
*/
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN TURNO;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN TIPO;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN ID_AREA_ATUACAO;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DESCRICAO_TURMA;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN PERIODO_TEORICO_INICIO;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN PERIODO_TEORICO_FIM;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN PERIODO_PRATICA_INICIO;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN PERIODO_PRATICA_FIM;

ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DATA_CONCLUSAO;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DATA_TEORICO_INICIAL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DATA_PRATICA_INICIAL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DIAS_TEORICO_SEMANA;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DIAS_PRATICA_SEMANA;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN HORARIO_TEORICO_INICIAL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN HORARIO_TEORICO_FINAL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN HORARIO_PRATICA_INICIAL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN HORARIO_PRATICA_FINAL;

ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO ADD DATA_INICIO TIMESTAMP(6) NOT NULL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO ADD DATA_INICIO_PERSONALIZADA TIMESTAMP(6) NOT NULL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO ADD USA_DATA_PERSONALIZADA NUMBER(1) NOT NULL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO ADD HORARIO_CURSO NUMBER(1) NOT NULL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO ADD DIA_CAPACITACAO VARCHAR2(50) NOT NULL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO ADD CARGA_HORARIA_TEORICA NUMBER(5) NOT NULL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO ADD CARGA_HORARIA_PRATICA NUMBER(5) NOT NULL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO ADD TIPO_TURMA VARCHAR2(10) NOT NULL;

--------------------------

ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN TURNO;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN TIPO;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN ID_AREA_ATUACAO;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DESCRICAO_TURMA;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN PERIODO_TEORICO_INICIO;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN PERIODO_TEORICO_FIM;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN PERIODO_PRATICA_INICIO;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN PERIODO_PRATICA_FIM;

ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DATA_CONCLUSAO;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DATA_TEORICO_INICIAL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DATA_PRATICA_INICIAL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DIAS_TEORICO_SEMANA;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN DIAS_PRATICA_SEMANA;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN HORARIO_TEORICO_INICIAL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN HORARIO_TEORICO_FINAL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN HORARIO_PRATICA_INICIAL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO DROP COLUMN HORARIO_PRATICA_FINAL;

ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO ADD DATA_INICIO TIMESTAMP(6) NOT NULL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO ADD DATA_INICIO_PERSONALIZADA TIMESTAMP(6) NOT NULL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO ADD USA_DATA_PERSONALIZADA NUMBER(1) NOT NULL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO ADD HORARIO_CURSO NUMBER(1) NOT NULL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO ADD DIA_CAPACITACAO VARCHAR2(50) NOT NULL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO ADD CARGA_HORARIA_TEORICA NUMBER(5) NOT NULL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO ADD CARGA_HORARIA_PRATICA NUMBER(5) NOT NULL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO ADD TIPO_TURMA VARCHAR2(10) NOT NULL;