CREATE TABLE REP_NACIONALIDADES
(ID NUMBER(19) not null,
CRIADO_POR VARCHAR2(255 char),
DATA_CRIACAO TIMESTAMP(6) not null,
DELETADO NUMBER(1) not null,
MODIFICADO_POR VARCHAR2(255 char),
DATA_ALTERACAO TIMESTAMP(6) not null,
SITUACAO NUMBER(1) not null,
CODIGO_ESOCIAL NUMBER(19) not null,
CODIGO_NACIONALIDADE NUMBER(19),
DESCRICAO_NACIONALIDADE VARCHAR2(150 char) not null
);

ALTER TABLE REP_NACIONALIDADES
    ADD CONSTRAINT KRS_INDICE_03719 primary key (ID);

