 CREATE TABLE REP_ESCOLARIDADES_ESTUDANTES(
    ID NUMBER(19,0) NOT NULL DISABLE, 
    ID_PERIODO_CURSO NUMBER,
    ID_ESTUDANTE NUMBER(19,0) NOT NULL DISABLE,
    DATA_CRIACAO TIMESTAMP (6) NOT NULL ENABLE,
    DATA_ALTERACAO TIMESTAMP (6) NOT NULL ENABLE,
    CRIADO_POR VARCHAR2(255 BYTE),
    MODIFICADO_POR VARCHAR2(255 BYTE),
    DELETADO NUMBER(1,0),
    OAB NUMBER(1,0),
    MATRICULA VARCHAR2(20 BYTE),
    DATA_INICIO DATE,
    DATA_CONCLUSAO DATE,
    PERIODO_ATUAL NUMBER(2,0) DEFAULT NULL,
    NOME_ESCOLA VARCHAR2(350 BYTE),
    ID_CURSO VARCHAR2(255 BYTE),
    TIPO_PERIODO_CURSO VARCHAR2(20 BYTE),
    DURACAO_CURSO NUMBER(10,0),
    TIPO_DURACAO_CURSO VARCHAR2(20 BYTE),
    PRINCIPAL NUMBER(1,0) DEFAULT 0 NOT NULL DISABLE,
    STATUS_ESCOLARIDADE VARCHAR2(20 BYTE) DEFAULT 'CONCLUIDO' NOT NULL DISABLE,
    ULTIMO_PERIODO_CURSADO NUMBER(2,0),
    DATA_PREVISTA_CONCLUSAO DATE,
    SIGLA_NIVEL_EDUCACAO VARCHAR2(2 BYTE),
    LONGITUDE_CAMPUS FLOAT(126),
    LATITUDE_CAMPUS FLOAT(126),
    ID_ESCOLA NUMBER(19,0),
    DATA_CONCLUSAO_CALCULADA TIMESTAMP (6));


ALTER TABLE  REP_ESCOLARIDADES_ESTUDANTES ADD (CONSTRAINT KRS_INDICE_01329 PRIMARY KEY (id));
CREATE INDEX KRS_INDICE_01324 ON REP_ESCOLARIDADES_ESTUDANTES (SIGLA_NIVEL_EDUCACAO);
CREATE INDEX KRS_INDICE_01325 ON REP_ESCOLARIDADES_ESTUDANTES (STATUS_ESCOLARIDADE);
CREATE INDEX KRS_INDICE_01326 ON REP_ESCOLARIDADES_ESTUDANTES (ID_PERIODO_CURSO);
CREATE INDEX KRS_INDICE_01327 ON REP_ESCOLARIDADES_ESTUDANTES (ID_ESTUDANTE);
CREATE INDEX KRS_INDICE_01328 ON REP_ESCOLARIDADES_ESTUDANTES (MODIFICADO_POR);



CREATE TABLE REP_PARAMETROS_PROGRAMA_EST(
    ID NUMBER(19,0) NOT NULL ENABLE,
    CRIADO_POR VARCHAR2(255 CHAR),
    DATA_CRIACAO TIMESTAMP (6) NOT NULL ENABLE,
    DELETADO NUMBER(1,0) NOT NULL ENABLE,
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DATA_ALTERACAO TIMESTAMP (6) NOT NULL ENABLE,
    CODIGO_CIEE NUMBER(19,0) NOT NULL ENABLE,
    JORNADA_MAXIMA_DIARIA NUMBER(5,0) NOT NULL ENABLE,
    JORNADA_DIARIA_MAX_ED_ESPECIAL NUMBER(5,0) NOT NULL ENABLE,
    JORNADA_SEM_MAX_ED_ESPECIAL NUMBER(5,0) NOT NULL ENABLE,
    JORNADA_MAXIMA_SEMANAL NUMBER(5,0) NOT NULL ENABLE,
    QUANTIDADE_MINIMA_ATIVIDADES NUMBER(5,0) NOT NULL ENABLE,
    IDADE_MINIMA NUMBER(2,0),
    IDADE_MAXIMA NUMBER(2,0));

ALTER TABLE  REP_PARAMETROS_PROGRAMA_EST  ADD (CONSTRAINT KRS_INDICE_01331 PRIMARY KEY (id));



 CREATE TABLE REP_PARAMETROS_PROGRAMA_APR(
    ID NUMBER(19,0) NOT NULL ENABLE,
    CRIADO_POR VARCHAR2(255 CHAR),
    DATA_CRIACAO TIMESTAMP (6) NOT NULL ENABLE,
    DELETADO NUMBER(1,0) NOT NULL ENABLE,
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DATA_ALTERACAO TIMESTAMP (6) NOT NULL ENABLE,
    LIMITE_CANCELAMENTO NUMBER(10,0) NOT NULL ENABLE,
    CODIGO_CIEE NUMBER(10,0),
    DIAS_ANTECIPACAO_RESCISAO NUMBER(10,0) NOT NULL ENABLE,
    CI_DESEJAVEL_EMPREGADOR NUMBER(10,2) NOT NULL ENABLE,
    CI_DESEJAVEL_CAPACITADOR NUMBER(10,2) NOT NULL ENABLE,
    CI_DESEJAVEL_LEGAL_EMPREGADOR NUMBER(10,2) NOT NULL ENABLE,
    CI_DESEJAVEL_LEGAL_CAPACITADOR NUMBER(10,2) NOT NULL ENABLE,
    CURSO_FUNDAMENTAL NUMBER(1,0) NOT NULL ENABLE,
    ESCOLA_FUNDAMENTAL_APRENDIZ NUMBER(10,0) NOT NULL ENABLE,
    CURSO_SUPERIOR NUMBER(1,0) NOT NULL ENABLE,
    IDADE_LIMITE_CONTRATACAO_DIA NUMBER(10,0) NOT NULL ENABLE,
    IDADE_LIMITE_CONTRATACAO_MES NUMBER(10,0) NOT NULL ENABLE,
    IDADE_LIMITE_CONTRATACAO_ANO NUMBER(10,0) NOT NULL ENABLE,
    IDADE_MAXIMA_ANO NUMBER(10,0) NOT NULL ENABLE,
    QUANTIDADE_MAXIMA_ATIVIDADES NUMBER(10,0) NOT NULL ENABLE,
    JORNADA_DIA_MAXIMA_FUNDAMENTAL NUMBER(5,0) NOT NULL ENABLE,
    JORNADA_DIA_MAXIMA_MEDIO NUMBER(5,0) NOT NULL ENABLE,
    IDADE_MAXIMA_DIA NUMBER(10,0) NOT NULL ENABLE,
    IDADE_MAXIMA_MES NUMBER(10,0) NOT NULL ENABLE,
    IDADE_MINIMA_ANO NUMBER(10,0) NOT NULL ENABLE,
    QUANTIDADE_MINIMA_ATIVIDADES NUMBER(10,0) NOT NULL ENABLE,
    CI_MINIMO_EMPREGADOR NUMBER(10,2) NOT NULL ENABLE,
    CI_MINIMO_CAPACITADOR NUMBER(10,2) NOT NULL ENABLE,
    MINIMO_DIA_CONTRATO NUMBER(10,0) NOT NULL ENABLE,
    JORNADA_DIA_MINIMA NUMBER(5,0) NOT NULL ENABLE,
    IDADE_MINIMA_DIA NUMBER(10,0) NOT NULL ENABLE,
    CI_MINIMO_LEGAL_EMPREGADOR NUMBER(10,2) NOT NULL ENABLE,
    CI_MINIMO_LEGAL_CAPACITADOR NUMBER(10,2) NOT NULL ENABLE,
    IDADE_MINIMA_MES NUMBER(10,0) NOT NULL ENABLE,
    CURSO_MEDIO NUMBER(1,0) NOT NULL ENABLE,
    CURSO_TECNICO NUMBER(1,0) NOT NULL ENABLE,
    LIMITE_CARTA_RESCISAO NUMBER(10,0) NOT NULL ENABLE);


  ALTER TABLE REP_PARAMETROS_PROGRAMA_APR  ADD (CONSTRAINT KRS_INDICE_01332 PRIMARY KEY (id))
