-- ***Migration Legado contrato Estagio ***

CREATE TABLE REP_EMAIL_EMPRESAS
(
    ID             NUMBER(20)    NOT NULL,
    ENDERECO       VARCHAR2(100) NOT NULL,
    DATA_CRIACAO   TIMESTAMP(6)  NOT NULL,
    DATA_ALTERACAO TIMESTAMP(6)  NOT NULL,
    CRIADO_POR     VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    DELETADO       NUMBER(1)
);

CREATE TABLE REP_ETNIAS
(
    ID             NUMBER(20)    NOT NULL,
    DESCRICAO      VARCHAR2(100) NOT NULL,
    ATIVO          NUMBER(1)     NOT NULL,
    DATA_CRIACAO   TIMESTAMP(6)  NOT NULL,
    DATA_ALTERACAO TIMESTAMP(6)  NOT NULL,
    CRIADO_POR     VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    DELETADO       NUMBER(1)
);

CREATE TABLE REP_TELEFONES_ESCOLA
(
    ID             NUMBER(20)   NOT NULL,
    DDD            VARCHAR2(2)  NOT NULL,
    DESCRICAO      VARCHAR2(100),
    RAMAL          VARCHAR2(9),
    NUMERO         VARCHAR2(9)  NOT NULL,
    TIPO_TELEFONE  VARCHAR2(255),
    DATA_CRIACAO   TIMESTAMP(6) NOT NULL,
    DATA_ALTERACAO TIMESTAMP(6) NOT NULL,
    CRIADO_POR     VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    DELETADO       NUMBER(1)
);

CREATE TABLE REP_ESCOLAS_TELEFONES
(
    ID_IE       NUMBER(19) NOT NULL,
    ID_TELEFONE NUMBER(19) NOT NULL
);

CREATE TABLE REP_SEGURADORAS
(
    ID             NUMBER(20)   NOT NULL,
    NOME           VARCHAR2(150),
    DATA_CRIACAO   TIMESTAMP(6) NOT NULL,
    DATA_ALTERACAO TIMESTAMP(6) NOT NULL,
    CRIADO_POR     VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    DELETADO       NUMBER(1)
);

CREATE TABLE REP_VALORES_APOLICES_EMPRESAS
(
    ID             NUMBER(20)    NOT NULL,
    MORTE          NUMBER(20, 2) NOT NULL,
    INVALIDEZ      NUMBER(20, 2) NOT NULL,
    DMH            NUMBER(20, 2) NOT NULL,
    DATA_CRIACAO   TIMESTAMP(6)  NOT NULL,
    DATA_ALTERACAO TIMESTAMP(6)  NOT NULL,
    CRIADO_POR     VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    DELETADO       NUMBER(1)
);

ALTER TABLE REP_REPRESENTANTES_CONTRATO
    ADD TIPO VARCHAR2(100);

ALTER TABLE REP_REPRESENTANTES
    ADD CPF VARCHAR2(12);
ALTER TABLE REP_REPRESENTANTES
    ADD EMAIL VARCHAR2(100);

ALTER TABLE REP_INFORMACOES_BRASILEIROS
    ADD NATURALIDADE VARCHAR2(255);
ALTER TABLE REP_INFORMACOES_BRASILEIROS
    ADD NATURALIDADE_UF VARCHAR2(255);
ALTER TABLE REP_INFORMACOES_BRASILEIROS
    ADD DATA_EMISSAO DATE;
ALTER TABLE REP_INFORMACOES_BRASILEIROS
    ADD ORGAO_EMISSOR VARCHAR2(20);

ALTER TABLE REP_INFORMACOES_ADICIONAIS
    ADD ID_GENERO NUMBER(20);

ALTER TABLE REP_INSTITUICOES_ENSINOS
    ADD ENDERECO NUMBER(20);

ALTER TABLE REP_CAMPUS
    ADD ID_DIRETOR NUMBER(20);

ALTER TABLE REP_PESSOAS
    ADD CARGO VARCHAR2(100);

ALTER TABLE REP_CAMPUS_CURSOS
    ADD ID_RESPONSAVEL NUMBER(19);
