--
-- PARAMETROS PROGRAMA ESTAGIO
--
ALTER TABLE REP_PARAMETROS_PROGRAMA_EST
DROP (
     DATA_IMPEDIMENTO_INICIO,
     DATA_IMPEDIMENTO_FIM,
     PARAMETRO_IMPEDIMENTO,
     DESCRICAO_IMPEDIMENTO
    );

ALTER TABLE REP_PARAMETROS_PROGRAMA_EST
ADD (
    FAIXA_CANCELAMENTO_INICIO NUMBER(3),
    FAIXA_CANCELAMENTO_FIM NUMBER(3),
    DIAS_MES_ANTERIOR_RESCISAO NUMBER(3)
    );

--
-- PARAMETROS PROGRAMA APRENDIZ
--
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR
    DROP (
          DATA_IMPEDIMENTO_INICIO,
          DATA_IMPEDIMENTO_FIM,
          PARAMETRO_IMPEDIMENTO,
          DESCRICAO_IMPEDIMENTO
        );

ALTER TABLE REP_PARAMETROS_PROGRAMA_APR
    ADD (
        FAIXA_CANCELAMENTO_INICIO NUMBER(3),
        FAIXA_CANCELAMENTO_FIM NUMBER(3),
        DIAS_MES_ANTERIOR_RESCISAO NUMBER(3)
        );




