-- ***Migration Legado contrato Estagio ***

CREATE TABLE REP_APOLICES_EMPRESAS
(
    ID                           NUMBER       NOT NULL,
    NUMERO                       VARCHAR2(20) NOT NULL,
    ID_SEGURADORA                NUMBER,
    ID_VALORES_APOLICES_EMPRESAS NUMBER,
    DATA_CRIACAO                 TIMESTAMP(6) NOT NULL,
    DATA_ALTERACAO               TIMESTAMP(6) NOT NULL,
    CRIADO_POR                   VARCHAR2(255),
    MODIFICADO_POR               VARCHAR2(255),
    DELETADO                     NUMBER(1)
);

CREATE TABLE REP_LOCAIS_TELEFONES
(
    ID_LOCAL_CONTRATO NUMBER NOT NULL,
    ID_TELEFONE       NUMBER NOT NULL
);

CREATE TABLE REP_EMPRESAS_TELEFONES
(
    ID             NUMBER       NOT NULL,
    DDD            VARCHAR2(2)  NOT NULL,
    NUMERO         VARCHAR2(9)  NOT NULL,
    DESCRICAO      VARCHAR2(100),
    RAMAL          VARCHAR2(9),
    TIPO_TELEFONE  VARCHAR2(50) NOT NULL,
    DATA_CRIACAO   TIMESTAMP(6) NOT NULL,
    DATA_ALTERACAO TIMESTAMP(6) NOT NULL,
    CRIADO_POR     VARCHAR2(255),
    MODIFICADO_POR VARCHAR2(255),
    DELETADO       NUMBER(1)
);


ALTER TABLE REP_EMPRESAS
    ADD ID_APOLICES_EMPRESAS NUMBER;
ALTER TABLE REP_EMAIL_EMPRESAS
    ADD CONSTRAINT KRS_INDICE_02343 PRIMARY KEY (ID);
ALTER TABLE REP_EMPRESAS_TELEFONES
    ADD CONSTRAINT KRS_INDICE_02353 PRIMARY KEY (ID);
ALTER TABLE REP_APOLICES_EMPRESAS
    ADD CONSTRAINT KRS_INDICE_02354 PRIMARY KEY (ID);
ALTER TABLE REP_ETNIAS
    ADD CONSTRAINT KRS_INDICE_02344 PRIMARY KEY (ID);
ALTER TABLE REP_TELEFONES_ESCOLA
    ADD CONSTRAINT KRS_INDICE_02345 PRIMARY KEY (ID);
ALTER TABLE REP_ESCOLAS_TELEFONES
    ADD CONSTRAINT KRS_INDICE_02346 PRIMARY KEY (ID_IE, ID_TELEFONE);
ALTER TABLE REP_SEGURADORAS
    ADD CONSTRAINT KRS_INDICE_02348 PRIMARY KEY (ID);
ALTER TABLE REP_VALORES_APOLICES_EMPRESAS
    ADD CONSTRAINT KRS_INDICE_02349 PRIMARY KEY (ID);
ALTER TABLE REP_LOCAIS_TELEFONES
    ADD CONSTRAINT KRS_INDICE_02350 PRIMARY KEY (ID_LOCAL_CONTRATO, ID_TELEFONE);


ALTER TABLE REP_EMPRESAS
    ADD CONSTRAINT KRS_INDICE_02352 FOREIGN KEY (ID_APOLICES_EMPRESAS) REFERENCES REP_APOLICES_EMPRESAS (ID);
ALTER TABLE REP_APOLICES_EMPRESAS
    ADD FOREIGN KEY (ID_SEGURADORA) REFERENCES REP_SEGURADORAS (ID);
ALTER TABLE REP_APOLICES_EMPRESAS
    ADD FOREIGN KEY (ID_VALORES_APOLICES_EMPRESAS) REFERENCES REP_VALORES_APOLICES_EMPRESAS (ID);
ALTER TABLE REP_ESCOLAS_TELEFONES
    ADD FOREIGN KEY (ID_TELEFONE) REFERENCES REP_TELEFONES_ESCOLA (ID);
ALTER TABLE REP_ESCOLAS_TELEFONES
    ADD FOREIGN KEY (ID_IE) REFERENCES REP_INSTITUICOES_ENSINOS (ID);
ALTER TABLE REP_LOCAIS_TELEFONES
    ADD FOREIGN KEY (ID_LOCAL_CONTRATO) REFERENCES REP_LOCAIS_CONTRATO (ID);
ALTER TABLE REP_LOCAIS_TELEFONES
    ADD FOREIGN KEY (ID_TELEFONE) REFERENCES REP_EMPRESAS_TELEFONES (ID);