-- Cria colunas utilizadas para o Termo Aditivo

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA ADD SEQ_TA NUMBER(20) DEFAULT 0;
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA ADD PENDENCIA_TA NUMBER(1) DEFAULT 0;