ALTER TABLE REP_ESTUDANTES
ADD (
   CODIGO_NACIONALIDADE NUMBER,
   BRASILEIRO NUMBER(1,0),
   CODIGO_IBGE_NATURALIDADE VARCHAR2(255 BYTE),
   UF_NATURALIDADE VARCHAR2(255 BYTE) ,
   NATURALIDADE_ESTRANGEIRO VARCHAR2(255 BYTE),
   DATA_EMISSAO_RG DATE,
   RG VARCHAR2(20 BYTE),
   UF_RG VARCHAR2(255 BYTE),
   ORGAO_EMISSOR_RG VARCHAR2(20 BYTE),
   RNE VARCHAR2(255 BYTE),
   DATA_LIMITE_PERMANENCIA DATE,
   CLASSIFICACAO_VISTO NUMBER,
   DATA_CHEGADA DATE,
   CASADO_BRASILEIRO NUMBER(1,0),
   FILHO_BRASILEIRO NUMBER(1,0)
);