ALTER TABLE {{user}}.REP_LOCAIS_CONTRATO
ADD BLOQUEADO NUMBER(1);

create table {{user}}.REP_CONTRATOS
(
	ID NUMBER(20) not null,
	SITUACAO_CONTRATO VARCHAR2(50 char),
	DATA_CRIACAO TIMESTAMP(6) not null,
	DATA_ALTERACAO TIMESTAMP(6) not null,
	CRIADO_POR VARCHAR2(255 char),
	MODIFICADO_POR VARCHAR2(255 char),
	DELETADO NUMBER(1)
);

ALTER TABLE rep_contratos ADD CONSTRAINT KRS_INDICE_01663 PRIMARY KEY ( id );
