ALTER TABLE REP_LOCAIS_CONTRATO ADD TIPO_PESSOA_EMPRESA VARCHAR2(50 CHAR);
ALTER TABLE REP_LOCAIS_CONTRATO ADD RAZAO_SOCIAL VARCHAR2(150 CHAR);
ALTER TABLE REP_ESTUDANTES ADD USA_NOME_SOCIAL NUMBER(1);