ALTER TABLE REP_LOCAIS_CONTRATO ADD (ID_CONSELHO_CLASSES NUMBER NULL);
ALTER TABLE REP_LOCAIS_CONTRATO ADD (ID_ATIVIDADES_CIEE NUMBER NULL);
ALTER TABLE REP_LOCAIS_CONTRATO ADD (CONSELHO_CLASSE_ATIVO NUMBER (1));


ALTER TABLE REP_LOCAIS_CONTRATO ADD CONSTRAINT KRS_INDICE_03734 FOREIGN KEY
    (ID_CONSELHO_CLASSES) REFERENCES REP_CONSELHO_CLASSES (ID);

ALTER TABLE REP_LOCAIS_CONTRATO ADD CONSTRAINT KRS_INDICE_03735 FOREIGN KEY
    (ID_ATIVIDADES_CIEE) REFERENCES REP_ATIVIDADES_CIEE (ID);


