create or replace view V_VINCULO_CLASSIFICACAO as
(
    select distinct
        case when ((RPS.SITUACAO IS NULL AND RPS.ID IS NOT NULL) OR EPS2.ID IS NOT NULL) then 1 else 0 end "POSSUI_ETAPA_PENDENTE",
        VV.ID ID_VINCULO_VAGA,
        EXTRACT(DAY FROM CASE WHEN RPS.SITUACAO IS NULL AND RPS.ID IS NOT NULL
            THEN
                CASE WHEN FS.TIPO_FERRAMENTA_SELECAO = 0 THEN APS.DATA - SYSDATE
                ELSE (
                    SELECT MAX(NVL(DATA_FINAL, DATA_INICIO)) FROM ETAPAS_PERIODOS EP WHERE EPS.ID = EP.ID_ETAPA_PROCESSO_SELETIVO) - SYSDATE
                END
            ELSE
                CASE WHEN EPS2.ID IS NOT NULL THEN
                EPS2.DATA_FINAL_ETAPA - SYSDATE
                ELSE
                SYSDATE - NVL(VE.DATA_CRIACAO, VA.DATA_CRIACAO)
                END
            END
        ) "CALCULO_DATAS",
        NVL(EPS.ORDEM_ETAPA, 1) "ORDEM_ETAPA",
        NVL(EPS.ID, EPS2.ID) ID
    FROM VINCULOS_VAGA VV
        LEFT JOIN VAGAS_ESTAGIO VE ON VE.CODIGO_DA_VAGA = VV.CODIGO_VAGA
        LEFT JOIN VAGAS_APRENDIZ VA ON VA.CODIGO_DA_VAGA = VV.CODIGO_VAGA
        LEFT JOIN ESTUDANTES_AGENDA EA ON VV.ID = EA.ID_VINCULO_VAGA
        LEFT JOIN AGENDA_PROCESSO_SELETIVO APS on EA.ID_AGENDA_PROCESSO_SELETIVO = APS.ID
        LEFT JOIN RESULTADOS_PROCESSO_SELETIVO RPS ON EA.ID = RPS.ID_ESTUDANTE_AGENDA
        LEFT JOIN ETAPAS_PROCESSO_SELETIVO EPS ON APS.ID_ETAPA_PROCESSO_SELETIVO = EPS.ID
        LEFT JOIN FERRAMENTAS_SELECAO FS on EPS.ID_FERRAMENTA_SELECAO = FS.ID
        LEFT JOIN (
            select min(eps1.id) ID, min(eps1.ORDEM_ETAPA) ORDEM_ETAPA, eps1.ID_VAGA, max(nvl(ep1.DATA_FINAL, ep1.DATA_INICIO)) "DATA_FINAL_ETAPA"
            from ETAPAS_PROCESSO_SELETIVO eps1
            inner join ETAPAS_PERIODOS ep1 on eps1.ID = ep1.ID_ETAPA_PROCESSO_SELETIVO
            inner join AGENDA_PROCESSO_SELETIVO APS on eps1.ID = APS.ID_ETAPA_PROCESSO_SELETIVO
            where eps1.deletado = 0 and eps1.status is null
            group by eps1.ID_VAGA
            order by ORDEM_ETAPA
        ) EPS2 ON EPS2.ID_VAGA = VV.CODIGO_VAGA
    where (EA.DELETADO IS NULL OR EA.DELETADO = 0)
)