
ALTER TABLE SOLICITACOES_SERVICENOW
ADD (
        DATA_HORA_ENCERRAMENTO TIMESTAMP(6),
        ENCERRADO_POR VARCHAR2(255)
    );

INSERT INTO TIPO_SOLICITACAO (ID, DESCRICAO, CRIADO_POR, DATA_ALTERACAO, DATA_CRIACAO, DELETADO, MODIFICADO_POR)
VALUES (18, 'Contato para Assistente GMC', 'carga', current_timestamp, current_timestamp, 0, 'carga');