-- Ajustes tabela apolices_ciee
ALTER TABLE REP_APOLICES_CIEE ADD ID_TEL_ACIONAR_SEGURADORA NUMBER;
ALTER TABLE REP_APOLICES_CIEE DROP COLUMN ID_TEL_AUXILIO_FUNERAL;
ALTER TABLE REP_APOLICES_CIEE DROP COLUMN SUCURSAL_SEGURADORA;
--ALTER TABLE REP_APOLICES_CIEE DROP COLUMN GERA_REMESSA;
ALTER TABLE REP_APOLICES_CIEE DROP COLUMN SUSEP_APOLICE;

-- Ajustes tabela corretoras_apolices_ciee
ALTER TABLE REP_CORRETORAS_APOLICES_CIEE_COMPANY ADD EMAIL_ENVIO_ARQUIVO VARCHAR2(100 CHAR);
ALTER TABLE REP_CORRETORAS_APOLICES_CIEE_COMPANY ADD GERA_REMESSA NUMBER(1) DEFAULT 0;
ALTER TABLE REP_CORRETORAS_APOLICES_CIEE_COMPANY DROP COLUMN COBERTURA_APOLICE;

-- Ajustes tabela valores_apolices_ciee
ALTER TABLE REP_VALORES_APOLICES_CIEE ADD TIPO_COBERTURA_APOLICE VARCHAR2(100 CHAR);
ALTER TABLE REP_VALORES_APOLICES_CIEE ADD VALOR_CESTA_BASICA NUMBER(10,2);
ALTER TABLE REP_VALORES_APOLICES_CIEE ADD VALOR_AUXILIO_EMERGENCIAL NUMBER(10,2);
ALTER TABLE REP_VALORES_APOLICES_CIEE ADD VALOR_AUXILIO_FUNERAL NUMBER(10,2);
ALTER TABLE REP_VALORES_APOLICES_CIEE DROP COLUMN IOF;
ALTER TABLE REP_VALORES_APOLICES_CIEE DROP COLUMN CUSTO_TOTAL;
