
CREATE TABLE REP_EMAILS_ESCOLAS
(
    ID             NUMBER(19) NOT NULL,
    CRIADO_POR     VARCHAR2(255 CHAR),
    DATA_CRIACAO   TIMESTAMP(6) NOT NULL,
    DELETADO       NUMBER(1) NOT NULL,
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DATA_ALTERACAO TIMESTAMP(6) NOT NULL,
    ENDERECO       VARCHAR2(100 CHAR) NOT NULL,
    DESCRICAO      VARCHAR2(100 CHAR)
);

ALTER TABLE REP_EMAILS_ESCOLAS ADD CONSTRAINT KRS_INDICE_03784 PRIMARY KEY ( ID );

CREATE SEQUENCE SEQ_REP_EMAILS MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;

CREATE TABLE REP_PESSOAS_EMAILS_ESCOLAS
(
    ID_PESSOA NUMBER(19) NOT NULL,
    ID_EMAIL  NUMBER(19) NOT NULL
);

ALTER TABLE REP_PESSOAS_EMAILS_ESCOLAS ADD CONSTRAINT KRS_INDICE_03785 PRIMARY KEY ( ID_PESSOA, ID_EMAIL );
ALTER TABLE REP_PESSOAS_EMAILS_ESCOLAS ADD CONSTRAINT KRS_INDICE_03786 FOREIGN KEY ( ID_PESSOA )    REFERENCES REP_PESSOAS ( ID );
ALTER TABLE REP_PESSOAS_EMAILS_ESCOLAS ADD CONSTRAINT KRS_INDICE_03787 FOREIGN KEY ( ID_EMAIL )     REFERENCES REP_EMAILS_ESCOLAS ( ID );
