ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
    ADD CARGO_MONITOR VARCHAR2(255);

ALTER TABLE HIST_CONTRATOS_ESTUDANTES_EMPRESA
    ADD CARGO_MONITOR VARCHAR2(255);


ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO
    ADD ID_CBO NUMBER(19);

ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO
    ADD DESCRICAO_CBO VARCHAR2(255);

ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO
    ADD CONSTRAINT KRS_INDICE_04220 FOREIGN KEY (ID_CBO)
        REFERENCES CBOS (ID);


ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO
    ADD ID_CBO NUMBER(19);

ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO
    ADD DESCRICAO_CBO VARCHAR2(255);

ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO
    ADD CONSTRAINT KRS_INDICE_04222 FOREIGN KEY (ID_CBO)
        REFERENCES CBOS (ID);


ALTER TABLE HIST_CONTRATOS_CURSOS_CAPACITACAO
    ADD ID_CBO NUMBER(19);

ALTER TABLE HIST_CONTRATOS_CURSOS_CAPACITACAO
    ADD DESCRICAO_CBO VARCHAR2(255);

ALTER TABLE HIST_CONTRATOS_CURSOS_CAPACITACAO
    ADD CONSTRAINT KRS_INDICE_04223 FOREIGN KEY (ID_CBO)
        REFERENCES CBOS (ID);
