-- Renomeando tabelas relacionadas a funcionalidade de formulário

ALTER TABLE PERGUNTAS_FORMULARIOS RENAME TO PARAMS_PERGUNTAS_FORMULARIOS;
ALTER TABLE RESPOSTAS_FORMULARIOS RENAME TO PARAMS_RESPOSTAS_FORMULARIOS;
ALTER TABLE PERGUNTAS_TIPOS_RELATORIO RENAME TO PARAMS_PERGUNTAS_TIPOS_RELATORIO;
ALTER TABLE RELATORIOS RENAME TO FORMULARIOS_PERGUNTAS;
ALTER TABLE RESPOSTAS_ESTUDANTES RENAME TO RESPOSTAS_FORMS_ESTUDANTES;
ALTER TABLE RELATORIOS_ESTUDANTES RENAME TO FORMULARIOS_ESTUDANTES;
