DROP SEQUENCE SEQ_CONCENDENTES;

CREATE SEQUENCE SEQ_CONCEDENTES  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

DROP TABLE VINCULO_CONTRATOS_CONCENDENTES;

ALTER TABLE CONCEDENTES ADD ID_CONTRATO NUMBER(20) NOT NULL;

ALTER TABLE CONCEDENTES
    ADD CONSTRAINT krs_indice_02860 FOREIGN KEY ( ID_CONTRATO )
        REFERENCES REP_CONTRATOS (ID);