ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA DROP (VALOR_BOLSA_DE,VALOR_BOLSA_ATE);
ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA RENAME COLUMN VALOR_BOLSA_FIXO TO VALOR_BOLSA;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA DROP (VALOR_BOLSA_DE,VALOR_BOLSA_ATE);
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA RENAME COLUMN VALOR_BOLSA_FIXO TO VALOR_BOLSA;