CREATE INDEX KRS_INDICE_01878 ON TRIAGEM_CANDIDATOS_ANALITICO(CODIGO_VAGA);
CREATE INDEX KRS_INDICE_01879 ON VINCULOS_VAGA(CODIGO_VAGA);
CREATE INDEX KRS_INDICE_01880 ON ACOMPANHAMENTOS_VAGAS(CODIGO_VAGA);
CREATE INDEX KRS_INDICE_01881 ON AGENDA_EMPRESA_VAGA(CODIGO_VAGA);
CREATE INDEX KRS_INDICE_01882 ON REP_ESTUDANTES(ID_USUARIO_AUTH);