
  CREATE OR REPLACE VIEW ACOMP_VAGAS_OCORRENCIAS ("CONTRATO", "CODIGO_DA_VAGA", "VAGA_PP", "TIPO_VAGA", "DATA_CRIACAO", "ID_PCD", "NUMERO_VAGAS", "SITUACAO", "PRAZO_TRATAR", "ENCAMINHADOS", "DATA_OCORRENCIA", "DATA_PROCESSO_SELETIVO", "ALERTA") AS 
  (

  (SELECT DISTINCT RC.ID CONTRATO, VE.CODIGO_DA_VAGA, VE.PROCESSO_PERSONALIZADO VAGA_PP, 'E' TIPO_VAGA, VE.DATA_CRIACAO, P.ID ID_PCD, VE.NUMERO_VAGAS, S.SIGLA SITUACAO, RPUC.DIAS_PRAZO_TRATAR PRAZO_TRATAR,
                   (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                   (SELECT MAX(OCE.DATA_OCORRENCIA) FROM OCORRENCIAS_ESTAGIO OCE WHERE OCE.ID_VAGA_ESTAGIO = VE.ID) DATA_OCORRENCIA,
                   (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                   WHERE E.ID_VAGA = VE.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                   (SELECT DISTINCT CASE WHEN (
                                                SELECT MAX(OCE.DATA_OCORRENCIA) FROM OCORRENCIAS_ESTAGIO OCE WHERE OCE.ID_VAGA_ESTAGIO = VE.ID AND OCE.DATA_OCORRENCIA < SYSDATE - DIAS_PRAZO_TRATAR)
                                              IS NOT NULL THEN 1 ELSE 0  END AS ALERTA
                    FROM ETAPAS_PERIODOS) ALERTA

   FROM VAGAS_ESTAGIO VE
     JOIN REP_LOCAIS_CONTRATO RLC ON VE.ID_LOCAL_CONTRATO = RLC.ID
     JOIN REP_CONTRATOS RC ON RLC.ID_CONTRATO = RC.ID
     LEFT JOIN REP_LOCAIS_ENDERECOS RLE ON RLE.ID_LOCAL_CONTRATO = RLC.ID
     LEFT JOIN PCD P ON VE.ID = P.ID_VAGA_ESTAGIO
     JOIN SITUACOES S ON VE.ID_SITUACAO_VAGA = S.ID
     JOIN OCORRENCIAS_ESTAGIO OCE ON VE.ID = OCE.ID_VAGA_ESTAGIO
     JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RLE.ID_UNIDADE_CIEE = RPUC.ID_UNIDADE_CIEE
   WHERE VE.DELETADO = 0)

  UNION

  (SELECT DISTINCT RC.ID CONTRATO, VA.CODIGO_DA_VAGA, NULL VAGA_PP, 'A' TIPO_VAGA, VA.DATA_CRIACAO, P.ID ID_PCD, VA.NUMERO_VAGAS, S.SIGLA SITUACAO, RPUC.DIAS_PRAZO_TRATAR PRAZO_TRATAR,
                   (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                   (SELECT MAX(OCA.DATA_OCORRENCIA) FROM OCORRENCIAS_APRENDIZ OCA WHERE OCA.ID_VAGA_APRENDIZ = VA.ID) DATA_OCORRENCIA,
                   (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                   WHERE E.ID_VAGA = VA.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                   (SELECT DISTINCT CASE WHEN (
                                                SELECT MAX(OCE.DATA_OCORRENCIA) FROM OCORRENCIAS_ESTAGIO OCE WHERE OCE.ID_VAGA_ESTAGIO = VA.ID AND OCE.DATA_OCORRENCIA < SYSDATE - DIAS_PRAZO_TRATAR)
                                              IS NOT NULL THEN 1 ELSE 0  END AS ALERTA
                    FROM ETAPAS_PERIODOS) ALERTA

   FROM VAGAS_APRENDIZ VA
     JOIN REP_LOCAIS_CONTRATO RLC ON VA.ID_LOCAL_CONTRATO = RLC.ID
     JOIN REP_CONTRATOS RC ON RLC.ID_CONTRATO = RC.ID
     LEFT JOIN REP_LOCAIS_ENDERECOS RLE ON RLE.ID_LOCAL_CONTRATO = RLC.ID
     LEFT JOIN PCD_APRENDIZ P ON VA.ID = P.ID_VAGA_APENDIZ
     JOIN SITUACOES S ON VA.ID_SITUACAO_VAGA = S.ID
     JOIN OCORRENCIAS_APRENDIZ OCA ON VA.ID = OCA.ID_VAGA_APRENDIZ
     JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RLE.ID_UNIDADE_CIEE = RPUC.ID_UNIDADE_CIEE
   WHERE VA.DELETADO = 0)

);


  CREATE OR REPLACE VIEW V_ESTUDANTE_CONVOCADO ("CODIGO_VAGA", "NUMERO_CONTRATO", "NUMERO_LOCAL", "NUMERO_VAGAS", "RAZAO_SOCIAL", "CODIGO_UNIDADE", "NOME_UNIDADE", "HORARIO_INICIO", "HORARIO_TERMINO", "PROCESSO_PERSONALIZADO", "DATA_EMAIL", "DATA_SMS", "NUMERO_CARTEIRA", "RESPONSAVEL_CARTEIRA", "DATA_CONVOCACAO", "PRIORIZACAO_CTO", "IDENTIFICACAO_CTO", "ID_ESTUDANTE", "CODIGO_ESTUDANTE", "CODIGO_VINCULO", "NOME_ESTUDANTE", "TELEFONE", "CELULAR", "EMAIL", "DATA_ABERTURA") AS 
  (
       SELECT
      CODIGO_VAGA,
      NUMERO_CONTRATO,
      NUMERO_LOCAL,
      NUMERO_VAGAS,
      RAZAO_SOCIAL,
      CODIGO_UNIDADE,
      NOME_UNIDADE,
      HORARIO_INICIO,
      HORARIO_TERMINO,
      PROCESSO_PERSONALIZADO,
      DATA_EMAIL,
      DATA_SMS,
      NUMERO_CARTEIRA,
      RESPONSAVEL_CARTEIRA,
      DATA_CONVOCACAO,
      PRIORIZACAO_CTO,
      IDENTIFICACAO_CTO,
      ID_ESTUDANTE,
      CODIGO_ESTUDANTE,
      CODIGO_VINCULO,
      NOME_ESTUDANTE,
      TELEFONE,
      CELULAR,
      EMAIL,
      DATA_ABERTURA
    FROM (
           SELECT
             VV.CODIGO_VAGA,
             VV.NUMERO_CONTRATO,
             RLC.ID AS NUMERO_LOCAL,
             VE.NUMERO_VAGAS,
             RE.RAZAO_SOCIAL,
             RLE.ID_UNIDADE_CIEE AS CODIGO_UNIDADE,
             RUC.DESCRICAO AS NOME_UNIDADE,
             VE.HORARIO_ENTRADA AS HORARIO_INICIO,
             VE.HORARIO_SAIDA AS HORARIO_TERMINO,
             VE.PROCESSO_PERSONALIZADO,
             VV.DATA_COMUNICACAO_CONVOCACAO AS DATA_EMAIL,
             VV.DATA_COMUNICACAO_CONVOCACAO AS DATA_SMS,
             RC.ID_UNIDADE_CIEE AS NUMERO_CARTEIRA,
             RP.NOME AS RESPONSAVEL_CARTEIRA,
             VV.DATA_CONVOCACAO,
             VV.PRIORIZACAO_CTO,
             VV.IDENTIFICACAO_CTO,
             REE.ID AS ID_ESTUDANTE,
             REE.CODIGO_ESTUDANTE,
             VV.ID AS CODIGO_VINCULO,
             REE.NOME AS NOME_ESTUDANTE,
             (select listagg(TELEFONE, '|') within group(order by DATA_ALTERACAO desc) from REP_TELEFONES where principal = 1 and ID_ESTUDANTE = REE.ID and TIPO_TELEFONE = 'FIXO') TELEFONE,
             (select listagg(TELEFONE, '|') within group(order by DATA_ALTERACAO desc) from REP_TELEFONES where principal = 1 and ID_ESTUDANTE = REE.ID and TIPO_TELEFONE = 'CELULAR') CELULAR,
             (select REEM.EMAIL from REP_EMAILS REEM inner join REP_ESTUDANTES REPE on REEM.ID_ESTUDANTE = REPE.ID where reem.PRINCIPAL = 1 and REEM.ID_ESTUDANTE = REE.ID) EMAIL,
             VE.DATA_CRIACAO AS DATA_ABERTURA
           FROM VINCULOS_VAGA VV
                  INNER JOIN REP_ESTUDANTES REE on VV.ID_ESTUDANTE = REE.ID
                  INNER JOIN VAGAS_ESTAGIO VE on VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA
                  INNER JOIN VINCULOS_CONVOCACAO VC on VV.ID = VC.ID_VINCULO
                  INNER JOIN SITUACOES S on VE.ID_SITUACAO_VAGA = S.ID
                  INNER JOIN REP_LOCAIS_CONTRATO RLC on VE.ID_LOCAL_CONTRATO = RLC.ID
                  INNER JOIN REP_CONTRATOS C on RLC.ID_CONTRATO = C.ID
                  INNER JOIN REP_INFO_CONTRATO_EMPRESAS RICE on C.ID = RICE.ID_CONTRATO
                  INNER JOIN REP_EMPRESAS RE on RICE.ID_EMPRESA = RE.ID
                  INNER JOIN REP_LOCAIS_ENDERECOS RLE on RLC.ID = RLE.ID_LOCAL_CONTRATO
                  INNER JOIN REP_UNIDADES_CIEE RUC on RLE.ID_UNIDADE_CIEE = RUC.ID
                  INNER JOIN REP_CARTEIRAS RC on RUC.ID = RC.ID_UNIDADE_CIEE
                  INNER JOIN REP_ASSISTENTES RA on RC.ID_ASSISTENTE = RA.ID
                  INNER JOIN REP_PESSOAS RP on RA.ID_PESSOA = RP.ID
           WHERE VV.SITUACAO_VINCULO = 0 AND S.SIGLA = 'A'
           UNION
           SELECT
             VVG.CODIGO_VAGA ,
             VVG.NUMERO_CONTRATO,
             LCA.ID AS NUMERO_LOCAL,
             VA.NUMERO_VAGAS,
             REA.RAZAO_SOCIAL,
             RLEA.ID_UNIDADE_CIEE AS CODIGO_UNIDADE,
             RUCA.DESCRICAO AS NOME_UNIDADE,
             VA.HORARIO_INICIO ,
             VA.HORARIO_TERMINO,
             NULL as PROCESSO_PERSONALIZADO,
             VVG.DATA_COMUNICACAO_CONVOCACAO AS DATA_EMAIL,
             VVG.DATA_COMUNICACAO_CONVOCACAO AS DATA_SMS,
             RCA.ID_UNIDADE_CIEE AS NUMERO_CARTEIRA,
             RPA.NOME AS RESPONSAVEL_CARTEIRA,
             VVG.DATA_CONVOCACAO,
             VVG.PRIORIZACAO_CTO,
             VVG.IDENTIFICACAO_CTO,
             REEA.ID AS ID_ESTUDANTE,
             REEA.CODIGO_ESTUDANTE,
             VVG.ID AS CODIGO_VINCULO,
             REEA.NOME AS NOME_ESTUDANTE,
             (select listagg(TELEFONE, '|') within group(order by DATA_ALTERACAO desc) from REP_TELEFONES where principal = 1 and ID_ESTUDANTE = REEA.ID and TIPO_TELEFONE = 'FIXO') TELEFONE,
             (select listagg(TELEFONE, '|') within group(order by DATA_ALTERACAO desc) from REP_TELEFONES where principal = 1 and ID_ESTUDANTE = REEA.ID and TIPO_TELEFONE = 'CELULAR') CELULAR,
            (select REEMA.EMAIL from REP_EMAILS REEMA inner join REP_ESTUDANTES REPEA on REEMA.ID_ESTUDANTE = REPEA.ID where REEMA.PRINCIPAL = 1 and REEMA.ID_ESTUDANTE = REEA.ID) EMAIL,
             VA.DATA_CRIACAO AS DATA_ABERTURA
           FROM VINCULOS_VAGA VVG
                  INNER JOIN REP_ESTUDANTES REEA on VVG.ID_ESTUDANTE = REEA.ID
                  INNER JOIN VAGAS_APRENDIZ VA on VVG.CODIGO_VAGA = VA.CODIGO_DA_VAGA
                  INNER JOIN VINCULOS_CONVOCACAO VCA on VVG.ID = VCA.ID_VINCULO
                  INNER JOIN SITUACOES SS on VA.ID_SITUACAO_VAGA = SS.ID
                  INNER JOIN REP_LOCAIS_CONTRATO LCA on VA.ID_LOCAL_CONTRATO = LCA.ID
                  INNER JOIN REP_CONTRATOS CA on LCA.ID_CONTRATO = CA.ID
                  INNER JOIN REP_INFO_CONTRATO_EMPRESAS RICEA on CA.ID = RICEA.ID_CONTRATO
                  INNER JOIN REP_EMPRESAS REA on RICEA.ID_EMPRESA = REA.ID
                  INNER JOIN REP_LOCAIS_ENDERECOS RLEA on LCA.ID = RLEA.ID_LOCAL_CONTRATO
                  INNER JOIN REP_UNIDADES_CIEE RUCA on RLEA.ID_UNIDADE_CIEE = RUCA.ID
                  INNER JOIN REP_CARTEIRAS RCA on RUCA.ID = RCA.ID_UNIDADE_CIEE
                  INNER JOIN REP_ASSISTENTES RAA on RCA.ID_ASSISTENTE = RAA.ID
                  INNER JOIN REP_PESSOAS RPA on RAA.ID_PESSOA = RPA.ID

           WHERE VVG.SITUACAO_VINCULO = 0 AND SS.SIGLA = 'A'
         )
  );


