--
--Ajusta coluna EMPRESA_COM_ACESSIBILIDADE para valor default 0
--

ALTER TABLE VAGAS_ESTAGIO MODIFY EMPRESA_COM_ACESSIBILIDADE NUMBER DEFAULT 0;

ALTER TABLE VAGAS_APRENDIZ MODIFY EMPRESA_COM_ACESSIBILIDADE NUMBER DEFAULT 0;


--
--Ajusta os valoes de null para 0 nas colunas valido_cota e EMPRESA_COM_ACESSIBILIDADE tabela VAGAS_ESTAGIO
--

update VAGAS_ESTAGIO set VALIDO_COTA = 0, EMPRESA_COM_ACESSIBILIDADE = 0
where VALIDO_COTA is null and EMPRESA_COM_ACESSIBILIDADE is null;

--
--Ajusta os valoes de null para 0 nas colunas valido_cota e EMPRESA_COM_ACESSIBILIDADE tabela VAGAS_APRENDIZ
--

update VAGAS_APRENDIZ set VALIDO_COTA = 0, EMPRESA_COM_ACESSIBILIDADE = 0
where VALIDO_COTA is null and EMPRESA_COM_ACESSIBILIDADE is null;

--
--Ajusta a view V_VAGAS_ESTAGIO para garantir se houver algum valor null na coluna empresa_com_acessibilidade
--
CREATE OR REPLACE VIEW V_VAGAS_ESTAGIO AS
  SELECT
    v.ID,
    CASE WHEN (nvl(V.EMPRESA_COM_ACESSIBILIDADE,0) = 0) THEN 'NORMAL' ELSE 'PCD' END AS TIPO,
    v.codigo_da_vaga,
    v.data_criacao,
    s.id as ID_SITUACAO,
    s.sigla,
    s.DESCRICAO,
    RAP.CODIGO_AREA_PROFISSIONAL,
    RAP.DESCRICAO_AREA_PROFISSIONAL,
    RLC.ID as ID_LOCAL_CONTRATO,
    RLE.ID as ID_LOCAL_ENDERECO,
    RE.iD as ID_ENDERECO,
    RE.ENDERECO||' '||RE.BAIRRO||' '||RE.CIDADE||' '||RE.UF||' '||RE.CEP as ENDERECO,
    v.IDADE_MINIMA,
    v.IDADE_MAXIMA
FROM
    VAGAS_ESTAGIO v
    JOIN situacoes s ON v.id_situacao_vaga = s.id
    JOIN REP_LOCAIS_CONTRATO RLC ON V.ID_LOCAL_CONTRATO = RLC.ID
    JOIN REP_LOCAIS_ENDERECOS RLE ON RLC.ID = RLE.ID_LOCAL_CONTRATO
    JOIN REP_ENDERECOS RE ON RLE.ID_ENDERECO = RE.ID
    JOIN REP_AREAS_PROFISSIONAIS RAP  ON RAP.CODIGO_AREA_PROFISSIONAL = V.CODIGO_AREA_PROFISSIONAL;


--
--Ajusta a view V_VAGAS_APRENDIZ para garantir se houver algum valor null na coluna empresa_com_acessibilidade
--
 CREATE OR REPLACE  VIEW V_VAGAS_APRENDIZ AS
  SELECT
    v.ID,
    CASE WHEN (NVL(V.EMPRESA_COM_ACESSIBILIDADE,0) = 0) THEN 'NORMAL' ELSE 'PCD' END AS TIPO,
    v.codigo_da_vaga,
    v.data_criacao,
    s.id as ID_SITUACAO,
    s.sigla,
    s.DESCRICAO,
    T.CARGA_HORARIA_DIARIA,
    TO_CHAR (T.CARGA_HORARIA_DIARIA, 'HH24:MI') as CARGA_HORARIA,
    T.ID_CURSO,
    T.NOME_CURSO,
    RLC.ID as ID_LOCAL_CONTRATO,
    RLE.ID as ID_LOCAL_ENDERECO,
    RE.iD as ID_ENDERECO,
    RE.ENDERECO||' '||RE.BAIRRO||' '||RE.CIDADE||' '||RE.UF||' '||RE.CEP as ENDERECO,
    v.IDADE_MINIMA,
    v.IDADE_MAXIMA
FROM
    vagas_aprendiz v
    JOIN situacoes s ON v.id_situacao_vaga = s.id
    JOIN REP_LOCAIS_CONTRATO RLC ON V.ID_LOCAL_CONTRATO = RLC.ID
    JOIN REP_LOCAIS_ENDERECOS RLE ON RLC.ID = RLE.ID_LOCAL_CONTRATO
    JOIN REP_ENDERECOS RE ON RLE.ID_ENDERECO = RE.ID
    JOIN TURMAS T ON T.ID_VAGA_APRENDIZ = V.iD
    JOIN CURSOS_CAPACITACAO CC ON T.ID_CURSO = CC.ID
WHERE
    CC.SITUACAO = 1;