ALTER TABLE RELATORIOS_ESTUDANTES MODIFY ID_ENVELOPE VARCHAR(20);
ALTER TABLE SOLICITACOES_SERVICENOW DROP COLUMN SITUACAO_FINAL_TICKET;
ALTER TABLE RELATORIOS_ESTUDANTES ADD DATA_PREENCHIMENTO TIMESTAMP;