alter table PRE_CONTRATOS_ESTUDANTES_EMPRESA add HORARIO_INICIO_EXPDIENTE_APRENDIZ  TIMESTAMP;
alter table PRE_CONTRATOS_ESTUDANTES_EMPRESA add HORARIO_TERMINO_EXPDIENTE_APRENDIZ TIMESTAMP;
alter table PRE_CONTRATOS_ESTUDANTES_EMPRESA add CONTRAPARTIDA_AUX_TRANSPORTE_APRENDIZ VARCHAR(100);

alter table CONTRATOS_ESTUDANTES_EMPRESA add HORARIO_INICIO_EXPDIENTE_APRENDIZ  TIMESTAMP;
alter table CONTRATOS_ESTUDANTES_EMPRESA add HORARIO_TERMINO_EXPDIENTE_APRENDIZ TIMESTAMP;
alter table CONTRATOS_ESTUDANTES_EMPRESA add CONTRAPARTIDA_AUX_TRANSPORTE_APRENDIZ VARCHAR(100);

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
  MODIFY (
    
    PERIODO_ATUAL null,
    CODIGO_CURSO_ESTUDANTE null,
    PERIODO_CURSO_ESTUDANTE null,
    NOME_CURSO_ESTUDANTE null,
    PREVISAO_CONCL_CURSO_ESTUDANTE null,
    ID_IE null,
    NOME_IE null,
    ID_CAMPUS null,
    NOME_CAMPUS null,
    ENDERECO_CAMPUS null,
    NUMERO_CAMPUS null,    
    BAIRRO_CAMPUS null,
    CEP_CAMPUS null,
    CIDADE_CAMPUS null,
    UF_CAMPUS null,
    ID_EMPRESA null,
    NOME_EMPRESA null,
    DESCRICAO_VAGA null,
    CONDICAO_ESTAGIO null,
    DATA_INICIO_ESTAGIO null,
    DATA_FINAL_ESTAGIO null,
    TIPO_AUXILIO_BOLSA null,
    TIPO_AUXILIO_TRANSPORTE null	
  );