ALTER TABLE FORMULARIOS_ESTUDANTES RENAME COLUMN CONTATO TO NOME_SUPERVISOR;

ALTER TABLE FORMULARIOS_ESTUDANTES ADD EMAIL_SUPERVISOR VARCHAR2(300 CHAR);
ALTER TABLE FORMULARIOS_ESTUDANTES ADD TIPO_ASSINATURA NUMBER(1);

COMMENT ON COLUMN FORMULARIOS_ESTUDANTES.TIPO_ASSINATURA IS
    'Enum:

    0 - Assinatura Manual
    1 - Assinatura Eletrônica';
