
ALTER TABLE REP_PARAMETROS_PROGRAMA_EST ADD LIMITE_CONTRATO NUMBER(2);

UPDATE REP_PARAMETROS_PROGRAMA_EST SET LIMITE_CONTRATO = 24 WHERE CODIGO_CIEE = 1 OR CODIGO_CIEE = 2;

ALTER TABLE REP_PARAMETROS_PROGRAMA_EST MODIFY LIMITE_CONTRATO NUMBER(2) NOT NULL;

