CREATE SEQUENCE SEQ_CAMPOS_FORMULARIOS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;
CREATE SEQUENCE SEQ_RELATORIOS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (1, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'Código estagiário');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (2, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'Nome estagiário');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (3, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'Data de nascimento');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (4, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'RG');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (5, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'CPF');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (6, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'Empresa');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (7, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'Escola');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (8, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'Curso');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (9, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'Período do estágio');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (10, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'Relatório número');
INSERT INTO CAMPOS (ID, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO, CAMPO) VALUES (11, current_timestamp, current_timestamp, 'FLYWAY', 'FLYWAY', 0, 'Nome supervisor de estágio');
