--
-- #### Alterando tamanho das colunas de Mensagem do Parametro IE
--
ALTER TABLE {{user}}.PARAMETROS_IE MODIFY MSG_BACKOFFICE VARCHAR2(700);
ALTER TABLE {{user}}.PARAMETROS_IE MODIFY MSG_EMPRESA VARCHAR2(700);
ALTER TABLE {{user}}.PARAMETROS_IE MODIFY MSG_ESTUDANTE VARCHAR2(700);