-- VALORES IMPORTADOS DO LEGADO

UPDATE BENEFICIOS
SET TEM_VALOR_MONETARIO = 1,
    UTILIZA_NA_CONTRATACAO = 0,
    DATA_ALTERACAO = CURRENT_TIMESTAMP,
    MODIFICADO_POR = 'IMPORTACAO'
WHERE DESCRICAO = 'Vale Refeição';

UPDATE BENEFICIOS
SET TEM_VALOR_MONETARIO = 1,
    UTILIZA_NA_CONTRATACAO = 0,
    DATA_ALTERACAO = CURRENT_TIMESTAMP,
    MODIFICADO_POR = 'IMPORTACAO'
WHERE DESCRICAO = 'Vale Alimentação';

UPDATE BENEFICIOS
SET DESCRICAO = 'Vale Transporte',
    TEM_VALOR_MONETARIO = 0,
    UTILIZA_NA_CONTRATACAO = 0,
    DATA_ALTERACAO = CURRENT_TIMESTAMP,
    MODIFICADO_POR = 'IMPORTACAO'
WHERE DESCRICAO = 'Transporte extra';

UPDATE BENEFICIOS
SET DESCRICAO = 'Assistência Médica',
    TEM_VALOR_MONETARIO = 0,
    UTILIZA_NA_CONTRATACAO = 0,
    DATA_ALTERACAO = CURRENT_TIMESTAMP,
    MODIFICADO_POR = 'IMPORTACAO'
WHERE DESCRICAO = 'Convênio Médico';

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Restaurante no Local',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Cesta Básica',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Lanche na Empresa',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Ônibus da Empresa',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Ambulatório Médico',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Convênio com Farmácia',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'13 Bolsa',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Férias',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Ajuda de Custo Escolar',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Refeitório no Local',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Reembolso de Combustível',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Assistência Odontológica',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Possibilidade Prorrogação',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Possibilidade Efetivação',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Ajuda de Custo',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Auxílio Transporte Mensal',1,1,1,'M','TRANSPORTE',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Auxílio Transporte',1,1,2,'M','TRANSPORTE',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Auxílio Transporte Por Dia',1,1,1,'D','TRANSPORTE',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Seguro de Vida (APRENDIZ)',0,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Auxílio Alimentação Mensal',1,1,1,'M','REFEICAO',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Recesso Remunerado',0,1,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Auxílio Alimentação Diário',1,1,1,'D','REFEICAO',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');

INSERT INTO BENEFICIOS
(ID,DESCRICAO,TEM_VALOR_MONETARIO,UTILIZA_NA_CONTRATACAO,MOSTRA_VALOR,PERIODO_PAGAMENTO,TIPO_BENEFICIO,DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES(SEQ_BENEFICIOS.NEXTVAL,'Passe Livre (METRO)',1,0,0,'','',0,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP,'IMPORTACAO','01102019');