ALTER TABLE REP_PARAMETROS_PROGRAMA_EST ADD PRAZO_VALIDACAO_CSE NUMBER(3) DEFAULT 180;
ALTER TABLE REP_PARAMETROS_PROGRAMA_EST ADD PRAZO_ESTUDANTE_REGULARIZAR_CSE NUMBER(3) DEFAULT 30;
ALTER TABLE REP_PARAMETROS_PROGRAMA_EST ADD DATA_PROCESSO_CSE NUMBER(2) DEFAULT 1;