ALTER TABLE REP_ESTUDANTES ADD (VIDEO_URL VARCHAR2(250));

CREATE TABLE REP_TEMAS_REDACAO 
   (	
    ID NUMBER NOT NULL, 
	DESCRICAO VARCHAR2(255) NOT NULL, 
	DATA_CRIACAO TIMESTAMP (6) NOT NULL, 
	DATA_ALTERACAO TIMESTAMP (6) NOT NULL, 
	CRIADO_POR VARCHAR2(255), 
	MODIFICADO_POR VARCHAR2(255), 
	DELETADO NUMBER(1)	 
	);

ALTER TABLE REP_TEMAS_REDACAO ADD CONSTRAINT  KRS_INDICE_04461 PRIMARY KEY (ID);	
	
CREATE TABLE REP_REDACOES
   (	
    ID NUMBER(19) NOT NULL, 
	ID_ESTUDANTE NUMBER(19) NOT NULL , 
	ID_TEMA NUMBER(19), 
	CONTEUDO CLOB, 
	DATA_TERMINO TIMESTAMP (6), 
	DATA_CRIACAO TIMESTAMP (6) NOT NULL , 
	DATA_ALTERACAO TIMESTAMP (6) NOT NULL, 
	CRIADO_POR VARCHAR2(255), 
	MODIFICADO_POR VARCHAR2(255), 
	DELETADO NUMBER(1) 
	);

ALTER TABLE REP_REDACOES ADD CONSTRAINT KRS_INDICE_04462 PRIMARY KEY (ID);	

ALTER TABLE REP_REDACOES ADD CONSTRAINT KRS_INDICE_04463 FOREIGN KEY
    (ID_ESTUDANTE) REFERENCES REP_ESTUDANTES (ID);

ALTER TABLE REP_REDACOES ADD CONSTRAINT KRS_INDICE_04464 FOREIGN KEY
    (ID_TEMA) REFERENCES REP_TEMAS_REDACAO (ID);



