ALTER TABLE RESPOSTAS_FORMS_ESTUDANTES ADD TIPO_RESPOSTA NUMBER(1);
ALTER TABLE RESPOSTAS_FORMS_ESTUDANTES ADD DESCRITIVO_RESPOSTA VARCHAR2(200 CHAR);

COMMENT ON COLUMN RESPOSTAS_FORMS_ESTUDANTES.tipo_resposta IS
    'ENUM:

0-FECHADA
1-ABERTA';
