ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO MODIFY ID_CBO NUMBER(20);
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO MODIFY ID_CBO NUMBER(20);
ALTER TABLE HIST_CONTRATOS_CURSOS_CAPACITACAO MODIFY ID_CBO NUMBER(20);

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA DROP COLUMN CARGO_MONITOR_APRENDIZ;
ALTER TABLE HIST_CONTRATOS_ESTUDANTES_EMPRESA DROP COLUMN CARGO_MONITOR_APRENDIZ;
