CREATE TABLE REP_TIPOS_DE_PROCESSO
(ID NUMBER(19) not null,
CRIADO_POR VARCHAR2(255 char),
DATA_CRIACAO TIMESTAMP(6) not null,
DELETADO NUMBER(1) not null,
MODIFICADO_POR VARCHAR2(255 char),
DATA_ALTERACAO TIMESTAMP(6) not null,
DESCRICAO VARCHAR2(35 char) not null);

ALTER TABLE REP_TIPOS_DE_PROCESSO ADD CONSTRAINT KRS_INDICE_03779 PRIMARY KEY (ID);