CREATE OR REPLACE VIEW "SERVICE_VAGAS_DEV"."V_VAGAS_ESTAGIO" ("ID", "TIPO", "CODIGO_DA_VAGA", "DATA_CRIACAO", "ID_SITUACAO", "SIGLA", "DESCRICAO", "CODIGO_AREA_PROFISSIONAL", "DESCRICAO_AREA_PROFISSIONAL", "ID_LOCAL_CONTRATO", "ID_LOCAL_ENDERECO", "ID_ENDERECO", "ENDERECO", "IDADE_MINIMA", "IDADE_MAXIMA") AS
SELECT
    v.ID,
    CASE WHEN (nvl(V.PCD,0) = 0) THEN 'NORMAL' ELSE 'PCD' END AS TIPO,
    v.codigo_da_vaga,
    v.data_criacao,
    s.id as ID_SITUACAO,
    s.sigla,
    s.DESCRICAO,
    RAP.CODIGO_AREA_PROFISSIONAL,
    RAP.DESCRICAO_AREA_PROFISSIONAL,
    RLC.ID as ID_LOCAL_CONTRATO,
    RLE.ID as ID_LOCAL_ENDERECO,
    RE.iD as ID_ENDERECO,
    RE.ENDERECO||' '||RE.BAIRRO||' '||RE.CIDADE||' '||RE.UF||' '||RE.CEP as ENDERECO,
    v.IDADE_MINIMA,
    v.IDADE_MAXIMA
FROM
    VAGAS_ESTAGIO v
        JOIN situacoes s ON v.id_situacao_vaga = s.id
        JOIN REP_LOCAIS_CONTRATO RLC ON V.ID_LOCAL_CONTRATO = RLC.ID
        JOIN REP_LOCAIS_ENDERECOS RLE ON RLC.ID = RLE.ID_LOCAL_CONTRATO
        JOIN REP_ENDERECOS RE ON RLE.ID_ENDERECO = RE.ID
        JOIN REP_AREAS_PROFISSIONAIS RAP  ON RAP.CODIGO_AREA_PROFISSIONAL = V.CODIGO_AREA_PROFISSIONAL;