-- Arrumando as FKs da tabela PARAMETROS_EMPRESA_CONTRATO

ALTER TABLE {{user}}.PARAMETROS_EMPRESA_CONTRATO
DROP CONSTRAINT KRS_INDICE_01507;

ALTER TABLE {{user}}.PARAMETROS_EMPRESA_CONTRATO
    ADD CONSTRAINT KRS_INDICE_01507 FOREIGN KEY ( ID_CONTRATO )
        REFERENCES REP_CONTRATOS ( ID )
    NOT DEFERRABLE;

ALTER TABLE {{user}}.PARAMETROS_EMPRESA_CONTRATO
    ADD CONSTRAINT KRS_INDICE_01723 FOREIGN KEY ( ID_LOCAL_CONTRATO )
        REFERENCES REP_LOCAIS_CONTRATO ( ID )
    NOT DEFERRABLE;