
ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
  RENAME COLUMN ANO_ATUAL_CURSO_ESTUDANTE TO PERIODO_ATUAL;

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
  RENAME COLUMN SEMESTRE_ATUAL_CURSO_ESTUDANTE TO TIPO_DURACAO_CURSO;

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
  MODIFY (
    TIPO_DURACAO_CURSO VARCHAR2(10) null,
    PERIODO_ATUAL null,
    NOME_SOCIAL_ESTUDANTE null,
    NOME_ESTUDANTE null,
    CPF_ESTUDANTE null,
    NOME_MAE_ESTUDANTE null,
    EMAIL_ESTUDANTE null,
    TELEFONE_ESTUDANTE null,
    ENDERECO_ESTUDANTE null,
    NUMERO_END_ESTUDANTE null,
    COMPLEMENTO_END_ESTUDANTE null,
    BAIRRO_END_ESTUDANTE null,
    CEP_END_ESTUDANTE null,
    CIDADE_END_ESTUDANTE null,
    UF_END_ESTUDANTE null,
    CODIGO_CURSO_ESTUDANTE null,
    PERIODO_CURSO_ESTUDANTE null,
    NOME_CURSO_ESTUDANTE null,
    PREVISAO_CONCL_CURSO_ESTUDANTE null,
    ID_IE null,
    NOME_IE null,
    ID_CAMPUS null,
    NOME_CAMPUS null,
    ENDERECO_CAMPUS null,
    NUMERO_CAMPUS null,
    COMPLEMENTO_CAMPUS null,
    BAIRRO_CAMPUS null,
    CEP_CAMPUS null,
    CIDADE_CAMPUS null,
    UF_CAMPUS null,
    ID_EMPRESA null,
    NOME_EMPRESA null,
    CODIGO_DA_VAGA null,
    DESCRICAO_VAGA null,
    CONDICAO_ESTAGIO null,
    DATA_INICIO_ESTAGIO null,
    DATA_FINAL_ESTAGIO null,
    TIPO_AUXILIO_BOLSA null,
    TIPO_AUXILIO_TRANSPORTE null
  );





