--Cria view de vagas estágio com estudantes vinculados

CREATE OR REPLACE VIEW 
    V_ESTAGIARIOS_VINCULADOS
AS
SELECT
    V.ID, V.ID_LOCAL_CONTRATO, V.CODIGO_DA_VAGA, V.DATA_CRIACAO, V.ID_SITUACAO_VAGA, S.SIGLA AS SIGLA_SITUACAO,
    S.DESCRICAO AS SITUACAO, V.NUMERO_VAGAS, COUNT(VV.ID) AS CANDIDATOS_VINCULADOS, V.CODIGO_AREA_PROFISSIONAL,
    A.DESCRICAO_AREA_PROFISSIONAL
FROM
    VAGAS_ESTAGIO V
INNER JOIN
    SITUACOES S ON V.ID_SITUACAO_VAGA = S.ID
INNER JOIN
    REP_AREAS_PROFISSIONAIS A ON A.CODIGO_AREA_PROFISSIONAL = V.CODIGO_AREA_PROFISSIONAL
LEFT JOIN
    VINCULOS_VAGA VV on V.CODIGO_DA_VAGA = VV.CODIGO_VAGA
GROUP BY
    V.ID, V.ID_LOCAL_CONTRATO, V.CODIGO_DA_VAGA, V.DATA_CRIACAO, V.ID_SITUACAO_VAGA, S.SIGLA, S.DESCRICAO,
    V.NUMERO_VAGAS, V.CODIGO_AREA_PROFISSIONAL, A.DESCRICAO_AREA_PROFISSIONAL
