CREATE TABLE {{user}}.REP_EMAILS 
   (
    ID NUMBER(19) NOT NULL ENABLE, 
	ID_ESTUDANTE NUMBER(19) NOT NULL ENABLE, 
	EMAIL VARCHAR2(100) NOT NULL ENABLE, 
	PRINCIPAL NUMBER DEFAULT 0, 
	VERIFICADO NUMBER DEFAULT 0, 
	DATA_CRIACAO TIMESTAMP (6) NOT NULL ENABLE, 
	DATA_ALTERACAO TIMESTAMP (6) NOT NULL ENABLE, 
	CRIADO_POR VARCHAR2(255), 
	MODIFICADO_POR VARCHAR2(255), 
	DELETADO NUMBER
	);

ALTER TABLE {{user}}.REP_EMAILS ADD CONSTRAINT KRS_INDICE_01724 PRIMARY KEY ( id );
