CREATE TABLE {{user}}.DOCUMENTOS_ETAPAS_ESTUDANTES (
    ID NUMBER(20) NOT NULL,
    CRIADO_POR VARCHAR2(255 CHAR),
    DATA_CRIACAO TIMESTAMP(6) NOT NULL,
    DELETADO NUMBER(1) NOT NULL,
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DATA_ALTERACAO TIMESTAMP(6) NOT NULL,
    ID_ESTUDANTE NUMBER(20) NOT NULL,
    ID_ETAPA_PROCESSO_SELETIVO NUMBER(20) NOT NULL,
    CODIGO_VAGA NUMBER(20) NOT NULL,
    ID_DOCUMENTO NUMBER(20) NOT NULL
);
ALTER TABLE {{user}}.DOCUMENTOS_ETAPAS_ESTUDANTES
    ADD CONSTRAINT KRS_INDICE_04824 FOREIGN KEY (ID_ETAPA_PROCESSO_SELETIVO)
        REFERENCES ETAPAS_PROCESSO_SELETIVO (id);
ALTER TABLE {{user}}.DOCUMENTOS_ETAPAS_ESTUDANTES
    ADD CONSTRAINT KRS_INDICE_04823 FOREIGN KEY (ID_ESTUDANTE)
        REFERENCES REP_ESTUDANTES (id);
CREATE SEQUENCE {{user}}.SEQ_DOCUMENTOS_ETAPAS_ESTUDANTES MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;