------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ACOMP_VAGAS_CONTATO_AGENDADO as
    (

        (SELECT DISTINCT RC.ID CONTRATO, VE.CODIGO_DA_VAGA, VE.PROCESSO_PERSONALIZADO VAGA_PP, 'E' TIPO_VAGA, VE.DATA_CRIACAO, P.ID ID_PCD, S.SIGLA SITUACAO, RPUC.LIMITE_MIN_ENCAMINHADOS_VAGA,
                         (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                         (SELECT MAX(AGE.DATA_CRIACAO) FROM AGENDA_EMPRESA_VAGA AGE WHERE AGE.CODIGO_VAGA = VE.CODIGO_DA_VAGA) DATA_ULTIMO_CONTATO,
                         (SELECT AGE.DATA_HORA FROM AGENDA_EMPRESA_VAGA AGE WHERE AGE.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND AGE.DATA_CRIACAO =
                                                                                                                          (SELECT MAX(AGE.DATA_CRIACAO) FROM AGENDA_EMPRESA_VAGA AGE WHERE AGE.CODIGO_VAGA = VE.CODIGO_DA_VAGA)) DATA_AGENDAMENTO,
                         (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                          WHERE E.ID_VAGA = VE.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                         (SELECT DISTINCT CASE WHEN (
                                                        SELECT MIN(EP.DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                                                        WHERE (EP.DATA_INICIO = SYSDATE + 1 OR EP.DATA_INICIO < SYSDATE) AND E.ID_VAGA = VE.CODIGO_DA_VAGA
                                                          AND LIMITE_MIN_ENCAMINHADOS_VAGA > (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0)) IS NOT NULL THEN 1 ELSE 0  END AS ALERTA
                          FROM ETAPAS_PERIODOS) ALERTA

         FROM VAGAS_ESTAGIO VE
                  JOIN REP_LOCAIS_CONTRATO ON VE.ID_LOCAL_CONTRATO = REP_LOCAIS_CONTRATO.ID
                  JOIN REP_CONTRATOS RC ON REP_LOCAIS_CONTRATO.ID_CONTRATO = RC.ID
                  LEFT JOIN PCD_ESTAGIO P ON VE.ID = P.ID_VAGA_ESTAGIO
                  JOIN SITUACOES S ON VE.ID_SITUACAO_VAGA = S.ID
                  JOIN REP_LOCAIS_ENDERECOS RLE on REP_LOCAIS_CONTRATO.ID = RLE.ID_LOCAL_CONTRATO
                  JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
                  JOIN AGENDA_EMPRESA_VAGA AEG ON AEG.CODIGO_VAGA = VE.CODIGO_DA_VAGA
         WHERE S.SIGLA <> 'P' AND S.SIGLA <> 'C' AND (AEG.DATA_HORA BETWEEN SYSDATE - 5 AND SYSDATE) AND VE.DELETADO = 0)

        UNION

        (SELECT DISTINCT RC.ID CONTRATO, VA.CODIGO_DA_VAGA, NULL VAGA_PP, 'A' TIPO_VAGA, VA.DATA_CRIACAO, P.ID ID_PCD, S.SIGLA SITUACAO, RPUC.LIMITE_MIN_ENCAMINHADOS_VAGA,
                         (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                         (SELECT MAX(AGE.DATA_CRIACAO) FROM AGENDA_EMPRESA_VAGA AGE WHERE AGE.CODIGO_VAGA = VA.CODIGO_DA_VAGA) DATA_ULTIMO_CONTATO,
                         (SELECT AGE.DATA_HORA FROM AGENDA_EMPRESA_VAGA AGE WHERE AGE.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND AGE.DATA_CRIACAO =
                                                                                                                          (SELECT MAX(AGE.DATA_CRIACAO) FROM AGENDA_EMPRESA_VAGA AGE WHERE AGE.CODIGO_VAGA = VA.CODIGO_DA_VAGA)) DATA_AGENDAMENTO ,
                         (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                          WHERE E.ID_VAGA = VA.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                         (SELECT DISTINCT CASE WHEN (
                                                        SELECT MIN(EP.DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                                                        WHERE (EP.DATA_INICIO = SYSDATE + 1 OR EP.DATA_INICIO < SYSDATE) AND E.ID_VAGA = VA.CODIGO_DA_VAGA
                                                          AND LIMITE_MIN_ENCAMINHADOS_VAGA > (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0)) IS NOT NULL THEN 1 ELSE 0  END AS ALERTA
                          FROM ETAPAS_PERIODOS) ALERTA

         FROM VAGAS_APRENDIZ VA
                  JOIN REP_LOCAIS_CONTRATO ON VA.ID_LOCAL_CONTRATO = REP_LOCAIS_CONTRATO.ID
                  JOIN REP_CONTRATOS RC ON REP_LOCAIS_CONTRATO.ID_CONTRATO = RC.ID
                  LEFT JOIN PCD_APRENDIZ P ON VA.ID = P.ID_VAGA_APRENDIZ
                  JOIN SITUACOES S ON VA.ID_SITUACAO_VAGA = S.ID
                  JOIN REP_LOCAIS_ENDERECOS RLE on REP_LOCAIS_CONTRATO.ID = RLE.ID_LOCAL_CONTRATO
                  JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
                  JOIN AGENDA_EMPRESA_VAGA AEG ON AEG.CODIGO_VAGA = VA.CODIGO_DA_VAGA
         WHERE S.SIGLA <> 'P' AND S.SIGLA <> 'C' AND (AEG.DATA_HORA BETWEEN SYSDATE - 5 AND SYSDATE) AND  VA.DELETADO = 0)

    );

------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ACOMP_VAGAS_NOVAS as
    (
        (SELECT DISTINCT RC.ID CONTRATO, VE.CODIGO_DA_VAGA, VE.PROCESSO_PERSONALIZADO VAGA_PP, 'E' TIPO_VAGA, VE.DATA_CRIACAO, VE.NUMERO_VAGAS, P.ID ID_PCD, RPUC.NUMERO_MIN_ESTUDANTES_TRIAGEM,
                         (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                         (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VIV.DELETADO = 0) TRIADOS,
                         (SELECT COUNT(ACOMP.ID) FROM ACOMPANHAMENTOS_VAGAS ACOMP WHERE ACOMP.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND ACOMP.DELETADO = 0) FOLLOW_UP,
                         (SELECT COUNT(ACOMP.ID) FROM ACOMPANHAMENTOS_VAGAS ACOMP WHERE ACOMP.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND ACOMP.DELETADO = 0 and ACOMP.TIPO_REGISTRO = 0) FOLLOW_UP_MANUAL,
                         (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                          WHERE E.ID_VAGA = VE.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                         (SELECT DISTINCT CASE WHEN (
                                                        SELECT MIN(EP.DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                                                        WHERE (EP.DATA_INICIO = SYSDATE + 1 OR EP.DATA_INICIO < SYSDATE) AND E.ID_VAGA = VE.CODIGO_DA_VAGA
                                                          AND NUMERO_MIN_ESTUDANTES_TRIAGEM > (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VIV.DELETADO = 0)) IS NOT NULL THEN 1 ELSE 0  END AS ALERTA
                          FROM ETAPAS_PERIODOS) ALERTA

         FROM VAGAS_ESTAGIO VE
                  JOIN REP_LOCAIS_CONTRATO ON VE.ID_LOCAL_CONTRATO = REP_LOCAIS_CONTRATO.ID
                  JOIN REP_CONTRATOS RC ON REP_LOCAIS_CONTRATO.ID_CONTRATO = RC.ID
                  LEFT JOIN PCD_ESTAGIO P ON VE.ID = P.ID_VAGA_ESTAGIO
                  JOIN REP_LOCAIS_ENDERECOS RLE on REP_LOCAIS_CONTRATO.ID = RLE.ID_LOCAL_CONTRATO
                  JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
         WHERE VE.ID_SITUACAO_VAGA = (SELECT ID FROM SITUACOES WHERE SIGLA = 'A') AND VE.DELETADO = 0)

        UNION

        (SELECT DISTINCT RC.ID CONTRATO, VA.CODIGO_DA_VAGA, NULL VAGA_PP, 'A' TIPO_VAGA, VA.DATA_CRIACAO, VA.NUMERO_VAGAS, P.ID ID_PCD, RPUC.NUMERO_MIN_ESTUDANTES_TRIAGEM,
                         (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                         (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VIV.DELETADO = 0) TRIADOS,
                         (SELECT COUNT(ACOMP.ID) FROM ACOMPANHAMENTOS_VAGAS ACOMP WHERE ACOMP.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND ACOMP.DELETADO = 0) FOLLOW_UP,
                         (SELECT COUNT(ACOMP.ID) FROM ACOMPANHAMENTOS_VAGAS ACOMP WHERE ACOMP.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND ACOMP.DELETADO = 0 AND ACOMP.TIPO_REGISTRO = 0) FOLLOW_UP_MANUAL,
                         (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                          WHERE E.ID_VAGA = VA.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                         (SELECT DISTINCT CASE WHEN (
                                                        SELECT MIN(EP.DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                                                        WHERE (EP.DATA_INICIO = SYSDATE + 1 OR EP.DATA_INICIO < SYSDATE) AND E.ID_VAGA = VA.CODIGO_DA_VAGA
                                                          AND NUMERO_MIN_ESTUDANTES_TRIAGEM > (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VIV.DELETADO = 0)) IS NOT NULL THEN 1 ELSE 0 END AS ALERTA
                          FROM ETAPAS_PERIODOS) ALERTA

         FROM VAGAS_APRENDIZ VA
                  JOIN REP_LOCAIS_CONTRATO ON VA.ID_LOCAL_CONTRATO = REP_LOCAIS_CONTRATO.ID
                  JOIN REP_CONTRATOS RC ON REP_LOCAIS_CONTRATO.ID_CONTRATO = RC.ID
                  LEFT JOIN PCD_APRENDIZ P ON P.ID_VAGA_APRENDIZ = VA.ID
                  JOIN REP_LOCAIS_ENDERECOS RLE on REP_LOCAIS_CONTRATO.ID = RLE.ID_LOCAL_CONTRATO
                  JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
         WHERE VA.ID_SITUACAO_VAGA = (SELECT ID FROM SITUACOES WHERE SIGLA = 'A') AND VA.DELETADO = 0)
    );


------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ACOMP_VAGAS_OCORRENCIAS as
    (

        (SELECT DISTINCT RC.ID CONTRATO, VE.CODIGO_DA_VAGA, VE.PROCESSO_PERSONALIZADO VAGA_PP, 'E' TIPO_VAGA, VE.DATA_CRIACAO, P.ID ID_PCD, VE.NUMERO_VAGAS, S.SIGLA SITUACAO, RPUC.DIAS_PRAZO_TRATAR PRAZO_TRATAR,
                         (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                         (SELECT MAX(OCE.DATA_OCORRENCIA) FROM OCORRENCIAS_ESTAGIO OCE WHERE OCE.ID_VAGA_ESTAGIO = VE.ID) DATA_OCORRENCIA,
                         (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                          WHERE E.ID_VAGA = VE.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                         (SELECT DISTINCT CASE WHEN (
                                                        SELECT MAX(OCE.DATA_OCORRENCIA) FROM OCORRENCIAS_ESTAGIO OCE WHERE OCE.ID_VAGA_ESTAGIO = VE.ID AND OCE.DATA_OCORRENCIA < SYSDATE - DIAS_PRAZO_TRATAR)
                             IS NOT NULL THEN 1 ELSE 0  END AS ALERTA
                          FROM ETAPAS_PERIODOS) ALERTA

         FROM VAGAS_ESTAGIO VE
                  JOIN REP_LOCAIS_CONTRATO RLC ON VE.ID_LOCAL_CONTRATO = RLC.ID
                  JOIN REP_CONTRATOS RC ON RLC.ID_CONTRATO = RC.ID
                  LEFT JOIN REP_LOCAIS_ENDERECOS RLE ON RLE.ID_LOCAL_CONTRATO = RLC.ID
                  LEFT JOIN PCD_ESTAGIO P ON VE.ID = P.ID_VAGA_ESTAGIO
                  JOIN SITUACOES S ON VE.ID_SITUACAO_VAGA = S.ID
                  JOIN OCORRENCIAS_ESTAGIO OCE ON VE.ID = OCE.ID_VAGA_ESTAGIO
                  JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RLE.ID_UNIDADE_CIEE = RPUC.ID_UNIDADE_CIEE
         WHERE VE.DELETADO = 0 AND OCE.DELETADO=0)

        UNION

        (SELECT DISTINCT RC.ID CONTRATO, VA.CODIGO_DA_VAGA, NULL VAGA_PP, 'A' TIPO_VAGA, VA.DATA_CRIACAO, P.ID ID_PCD, VA.NUMERO_VAGAS, S.SIGLA SITUACAO, RPUC.DIAS_PRAZO_TRATAR PRAZO_TRATAR,
                         (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                         (SELECT MAX(OCA.DATA_OCORRENCIA) FROM OCORRENCIAS_APRENDIZ OCA WHERE OCA.ID_VAGA_APRENDIZ = VA.ID) DATA_OCORRENCIA,
                         (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                          WHERE E.ID_VAGA = VA.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                         (SELECT DISTINCT CASE WHEN (
                                                        SELECT MAX(OCE.DATA_OCORRENCIA) FROM OCORRENCIAS_ESTAGIO OCE WHERE OCE.ID_VAGA_ESTAGIO = VA.ID AND OCE.DATA_OCORRENCIA < SYSDATE - DIAS_PRAZO_TRATAR)
                             IS NOT NULL THEN 1 ELSE 0  END AS ALERTA
                          FROM ETAPAS_PERIODOS) ALERTA

         FROM VAGAS_APRENDIZ VA
                  JOIN REP_LOCAIS_CONTRATO RLC ON VA.ID_LOCAL_CONTRATO = RLC.ID
                  JOIN REP_CONTRATOS RC ON RLC.ID_CONTRATO = RC.ID
                  LEFT JOIN REP_LOCAIS_ENDERECOS RLE ON RLE.ID_LOCAL_CONTRATO = RLC.ID
                  LEFT JOIN PCD_APRENDIZ P ON VA.ID = P.ID_VAGA_APRENDIZ
                  JOIN SITUACOES S ON VA.ID_SITUACAO_VAGA = S.ID
                  JOIN OCORRENCIAS_APRENDIZ OCA ON VA.ID = OCA.ID_VAGA_APRENDIZ
                  JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RLE.ID_UNIDADE_CIEE = RPUC.ID_UNIDADE_CIEE
         WHERE VA.DELETADO = 0 AND OCA.DELETADO=0)

    );



------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ACOMP_VAGAS_PROCESSO_SELETIVO as
    (

        (SELECT DISTINCT RC.ID CONTRATO, VE.CODIGO_DA_VAGA, VE.PROCESSO_PERSONALIZADO VAGA_PP, 'E' TIPO_VAGA, VE.DATA_CRIACAO, VE.NUMERO_VAGAS, P.ID ID_PCD, RPUC.LIMITE_MIN_ENCAMINHADOS_VAGA, S.SIGLA SITUACAO,
                         (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                         (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VIV.DELETADO = 0) TRIADOS,
                         (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                          WHERE E.ID_VAGA = VE.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                         (SELECT DISTINCT CASE WHEN (
                                                        SELECT MIN(EP.DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                                                        WHERE (EP.DATA_INICIO = SYSDATE + 1 OR EP.DATA_INICIO < SYSDATE) AND E.ID_VAGA = VE.CODIGO_DA_VAGA
                                                          AND LIMITE_MIN_ENCAMINHADOS_VAGA > (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0)) IS NOT NULL THEN 1 ELSE 0  END AS ALERTA
                          FROM ETAPAS_PERIODOS) ALERTA

         FROM VAGAS_ESTAGIO VE
                  JOIN REP_LOCAIS_CONTRATO ON VE.ID_LOCAL_CONTRATO = REP_LOCAIS_CONTRATO.ID
                  JOIN REP_CONTRATOS RC ON REP_LOCAIS_CONTRATO.ID_CONTRATO = RC.ID
                  LEFT JOIN PCD_ESTAGIO P ON VE.ID = P.ID_VAGA_ESTAGIO
                  JOIN REP_LOCAIS_ENDERECOS RLE on REP_LOCAIS_CONTRATO.ID = RLE.ID_LOCAL_CONTRATO
                  JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
                  JOIN SITUACOES S on VE.ID_SITUACAO_VAGA = S.ID
         WHERE VE.ID_SITUACAO_VAGA IN (SELECT ID FROM SITUACOES WHERE SIGLA = 'E' OR SIGLA = 'S') AND VE.DELETADO = 0)

        UNION

        (SELECT DISTINCT RC.ID CONTRATO, VA.CODIGO_DA_VAGA, NULL VAGA_PP, 'A' TIPO_VAGA, VA.DATA_CRIACAO, VA.NUMERO_VAGAS, P.ID ID_PCD, RPUC.LIMITE_MIN_ENCAMINHADOS_VAGA, S.SIGLA SITUACAO,
                         (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                         (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VIV.DELETADO = 0) TRIADOS,
                         (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                          WHERE E.ID_VAGA = VA.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                         (SELECT DISTINCT CASE WHEN (
                                                        SELECT MIN(EP.DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                                                        WHERE (EP.DATA_INICIO = SYSDATE + 1 OR EP.DATA_INICIO < SYSDATE) AND E.ID_VAGA = VA.CODIGO_DA_VAGA
                                                          AND LIMITE_MIN_ENCAMINHADOS_VAGA > (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0)) IS NOT NULL THEN 1 ELSE 0 END AS ALERTA
                          FROM ETAPAS_PERIODOS) ALERTA

         FROM VAGAS_APRENDIZ VA
                  JOIN REP_LOCAIS_CONTRATO ON VA.ID_LOCAL_CONTRATO = REP_LOCAIS_CONTRATO.ID
                  JOIN REP_CONTRATOS RC ON REP_LOCAIS_CONTRATO.ID_CONTRATO = RC.ID
                  LEFT JOIN PCD_APRENDIZ P ON P.ID_VAGA_APRENDIZ = VA.ID
                  JOIN REP_LOCAIS_ENDERECOS RLE on REP_LOCAIS_CONTRATO.ID = RLE.ID_LOCAL_CONTRATO
                  JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
                  JOIN SITUACOES S on VA.ID_SITUACAO_VAGA = S.ID
         WHERE VA.ID_SITUACAO_VAGA IN (SELECT ID FROM SITUACOES WHERE SIGLA = 'E' OR SIGLA = 'S') AND VA.DELETADO = 0)

    );


------------------------------------------------------------------------------
CREATE OR REPLACE VIEW ACOMP_VAGAS_RES_ASSISTENTE as
    (SELECT DISTINCT RC.ID CONTRATO, VE.CODIGO_DA_VAGA, VE.PROCESSO_PERSONALIZADO VAGA_PP, 'E' TIPO_VAGA, VE.DATA_CRIACAO, P.ID ID_PCD, RPUC.DIAS_RET_ASSISTENTE, AC.DATA_CRIACAO DATA_ENVIO,

                     (SELECT MIN(P.NOME) FROM REP_ASSISTENTES RAC
                                                  JOIN REP_PESSOAS P on RAC.ID_PESSOA = P.ID
                                                  JOIN REP_CARTEIRAS CAR on RAC.ID = CAR.ID_ASSISTENTE
                                                  JOIN REP_LOCAIS_ENDERECOS RLE ON RLE.ID_CARTEIRA = CAR.ID
                                                  JOIN REP_LOCAIS_CONTRATO RLC on RLE.ID_LOCAL_CONTRATO = RLC.ID
                      WHERE VE.ID_LOCAL_CONTRATO = RLC.ID
                      GROUP BY RLE.ID_LOCAL_CONTRATO) ASSISTENTE,

                     (SELECT DISTINCT CASE WHEN (
                                                    SELECT V.ID FROM VAGAS_ESTAGIO V WHERE VE.DATA_ALTERACAO + DIAS_RET_ASSISTENTE <= SYSDATE AND V.ID = VE.ID) IS NOT NULL THEN 1 ELSE 0 END AS ALERTA
                      FROM VAGAS_ESTAGIO) ALERTA

     FROM VAGAS_ESTAGIO VE
              JOIN REP_LOCAIS_CONTRATO LCT ON VE.ID_LOCAL_CONTRATO = LCT.ID
              JOIN REP_CONTRATOS RC ON LCT.ID_CONTRATO = RC.ID
              LEFT JOIN PCD_ESTAGIO P ON VE.ID = P.ID_VAGA_ESTAGIO
              JOIN REP_LOCAIS_ENDERECOS RLE on LCT.ID = RLE.ID_LOCAL_CONTRATO
              JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
              JOIN SITUACOES S on VE.ID_SITUACAO_VAGA = S.ID
              JOIN ACOMPANHAMENTOS_VAGAS AC ON AC.CODIGO_VAGA = VE.CODIGO_DA_VAGA
     WHERE S.SIGLA = 'I' AND VE.DELETADO = 0
       AND AC.DATA_CRIACAO = (SELECT MAX(A.DATA_CRIACAO) FROM ACOMPANHAMENTOS_VAGAS A WHERE A.CODIGO_VAGA = VE.CODIGO_DA_VAGA))

    UNION

    (SELECT DISTINCT RC.ID CONTRATO, VA.CODIGO_DA_VAGA, NULL VAGA_PP, 'A' TIPO_VAGA, VA.DATA_CRIACAO, P.ID ID_PCD, RPUC.DIAS_RET_ASSISTENTE, AC.DATA_CRIACAO DATA_ENVIO,

                     (SELECT MIN(P.NOME) FROM REP_ASSISTENTES RAC
                                                  JOIN REP_PESSOAS P on RAC.ID_PESSOA = P.ID
                                                  JOIN REP_CARTEIRAS CAR on RAC.ID = CAR.ID_ASSISTENTE
                                                  JOIN REP_LOCAIS_ENDERECOS RLE ON RLE.ID_CARTEIRA = CAR.ID
                                                  JOIN REP_LOCAIS_CONTRATO RLC on RLE.ID_LOCAL_CONTRATO = RLC.ID
                      WHERE VA.ID_LOCAL_CONTRATO = RLC.ID
                      GROUP BY RLE.ID_LOCAL_CONTRATO) ASSISTENTE,

                     (SELECT DISTINCT CASE WHEN (
                                                    SELECT V.ID FROM VAGAS_ESTAGIO V WHERE VA.DATA_ALTERACAO + DIAS_RET_ASSISTENTE <= SYSDATE AND V.ID = VA.ID) IS NOT NULL THEN 1 ELSE 0 END AS ALERTA
                      FROM VAGAS_ESTAGIO) ALERTA

     FROM VAGAS_APRENDIZ VA
              JOIN REP_LOCAIS_CONTRATO LCT ON VA.ID_LOCAL_CONTRATO = LCT.ID
              JOIN REP_CONTRATOS RC ON LCT.ID_CONTRATO = RC.ID
              LEFT JOIN PCD_APRENDIZ P ON P.ID_VAGA_APRENDIZ = VA.ID
              JOIN REP_LOCAIS_ENDERECOS RLE on LCT.ID = RLE.ID_LOCAL_CONTRATO
              JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
              JOIN SITUACOES S on VA.ID_SITUACAO_VAGA = S.ID
              JOIN ACOMPANHAMENTOS_VAGAS AC ON AC.CODIGO_VAGA = VA.CODIGO_DA_VAGA
     WHERE S.SIGLA = 'I' AND VA.DELETADO = 0
       AND AC.DATA_CRIACAO = (SELECT MAX(A.DATA_CRIACAO) FROM ACOMPANHAMENTOS_VAGAS A WHERE A.CODIGO_VAGA = VA.CODIGO_DA_VAGA));

------------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_VAGAS_PRIORIZACAO_SISTEMA_POM as
    (
        (
            SELECT DISTINCT RC.ID                      ID_CONTRATO,
                            VE.CODIGO_DA_VAGA          CODIGO_DA_VAGA,
                            VE.PROCESSO_PERSONALIZADO  VAGA_PP,
                            'E'                        TIPO_VAGA,
                            VE.DATA_CRIACAO            DATA_ABERTURA,
                            VE.NUMERO_VAGAS            NUMERO_VAGAS,
                            P.ID                       ID_PCD,
                            (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VV.DELETADO = 0) TRIADOS,
                            VE.PRIORIZA_POM            PRIORIZA_POM
            FROM VAGAS_ESTAGIO VE
                     JOIN REP_LOCAIS_CONTRATO  LC   ON      (VE.ID_LOCAL_CONTRATO = LC.ID)
                     JOIN REP_CONTRATOS        RC   ON      (LC.ID_CONTRATO = RC.ID)
                     LEFT JOIN PCD_ESTAGIO     P    ON      (VE.ID = P.ID_VAGA_ESTAGIO)
            WHERE   VE.ID_SITUACAO_VAGA = (SELECT ID FROM SITUACOES WHERE SIGLA = 'A')
              AND     VE.DELETADO = 0
        )

        UNION

        (
            SELECT DISTINCT RC.ID              ID_CONTRATO,
                            VA.CODIGO_DA_VAGA  CODIGO_DA_VAGA,
                            NULL               VAGA_PP,
                            'A'                TIPO_VAGA,
                            VA.DATA_CRIACAO    DATA_ABERTURA,
                            VA.NUMERO_VAGAS    NUMERO_VAGAS,
                            P.ID               ID_PCD,
                            (SELECT COUNT(VV.ID)   FROM VINCULOS_VAGA VV   WHERE VV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VV.DELETADO = 0) TRIADOS,
                            VA.PRIORIZA_POM    PRIORIZA_POM
            FROM VAGAS_APRENDIZ VA
                     JOIN REP_LOCAIS_CONTRATO  LC  ON (VA.ID_LOCAL_CONTRATO = LC.ID)
                     JOIN REP_CONTRATOS        RC  ON (LC.ID_CONTRATO = RC.ID)
                     LEFT JOIN PCD_APRENDIZ    P   ON (P.ID_VAGA_APRENDIZ = VA.ID)
            WHERE   VA.ID_SITUACAO_VAGA = (SELECT ID FROM SITUACOES WHERE SIGLA = 'A')
              AND     VA.DELETADO = 0)
    );



------------------------------------------------------------------------------
CREATE OR REPLACE VIEW V_VAGAS_VINCULADAS_ESTUDANTE as
    (

        SELECT VINC_E.ID_ESTUDANTE as ID_ESTUDANTE,
               VINC_E.CODIGO_VAGA AS CODIGO_VAGA,
               VAGA_E.ID_LOCAL_CONTRATO AS ID_LOCAL_CONTRATO,
               LOC_C.CNPJ AS CNPJ,
               'ESTAGIO' AS TIPO_VAGA,
               VAGA_E.TIPO_DIVULGACAO AS TIPO_DIVULGACAO,
               AP.DESCRICAO_AREA_PROFISSIONAL AS AREA_PROFISSIONAL,
               NULL AS AREA_ATUACAO,
               NULL AS CURSO_CAPACITACAO,
               VAGA_E.VALOR_BOLSA_FIXO AS VALOR_BOLSA,
               VAGA_E.VALOR_BOLSA_DE AS VALOR_BOLSA_DE,
               VAGA_E.VALOR_BOLSA_ATE AS VALOR_BOLSA_ATE,
               VAGA_E.TIPO_VALOR_BOLSA AS TIPO_VALOR_BOLSA,
               END.LATITUDE AS LATITUDE_EMPRESA,
               END.LONGITUDE AS LONGITUDE_EMPRESA,
               COUNT(B.ID) AS BENEFICIOS,
               pcd.ID AS ID_PCD,
               loc_c.razao_social as NOME_EMPRESA_PJ,
               loc_c.nome as NOME_EMPRESA_PL
        FROM VINCULOS_VAGA VINC_E
                 INNER JOIN VAGAS_ESTAGIO VAGA_E ON VAGA_E.CODIGO_DA_VAGA = VINC_E.CODIGO_VAGA
                 INNER JOIN REP_AREAS_PROFISSIONAIS AP ON AP.CODIGO_AREA_PROFISSIONAL = VAGA_E.CODIGO_AREA_PROFISSIONAL
                 INNER JOIN REP_LOCAIS_CONTRATO LOC_C ON LOC_C.ID = VAGA_E.ID_LOCAL_CONTRATO
                 INNER JOIN REP_LOCAIS_ENDERECOS LOC_E ON LOC_C.ID = LOC_E.ID_LOCAL_CONTRATO AND LOC_E.DELETADO = 0
                 INNER JOIN REP_ENDERECOS END ON LOC_E.ID_ENDERECO = END.ID
                 LEFT JOIN BENEFICIOS_ADICIONAIS B ON B.ID_VAGA_ESTAGIO = VAGA_E.ID
                 LEFT JOIN PCD_ESTAGIO pcd ON pcd.ID_VAGA_ESTAGIO = VAGA_E.ID
        WHERE VINC_E.SITUACAO_VINCULO <> 5
        GROUP BY ID_ESTUDANTE, CODIGO_VAGA, VAGA_E.ID_LOCAL_CONTRATO, CNPJ, 'ESTAGIO', TIPO_DIVULGACAO, DESCRICAO_AREA_PROFISSIONAL,
                 VALOR_BOLSA_FIXO, VALOR_BOLSA_DE, VALOR_BOLSA_ATE, TIPO_VALOR_BOLSA, LATITUDE, LONGITUDE, pcd.ID, loc_c.razao_social,loc_c.nome

        UNION

        SELECT VINC_A.ID_ESTUDANTE as ID_ESTUDANTE,
               VINC_A.CODIGO_VAGA AS CODIGO_VAGA,
               VAGA_A.ID_LOCAL_CONTRATO AS ID_LOCAL_CONTRATO,
               LOC_C.CNPJ AS CNPJ,
               'APRENDIZ' AS TIPO_VAGA,
               VAGA_A.TIPO_DIVULGACAO AS TIPO_DIVULGACAO,
               NULL AS AREA_PROFISSIONAL,
               VAGA_A.ID_AREA_ATUACAO_APRENDIZ AS AREA_ATUACAO,
               T.NOME_CURSO AS CURSO_CAPACITACAO,
               VAGA_A.VALOR_SALARIO AS VALOR_BOLSA,
               VAGA_A.VALOR_SALARIO_DE AS VALOR_BOLSA_DE,
               VAGA_A.VALOR_SALARIO_ATE AS VALOR_BOLSA_ATE,
               VAGA_A.TIPO_SALARIO_VALOR AS TIPO_VALOR_BOLSA,
               END.LATITUDE AS LATITUDE_EMPRESA,
               END.LONGITUDE AS LONGITUDE_EMPRESA,
               COUNT(B.ID) AS BENEFICIOS,
               pcd_aprendiz.ID AS ID_PCD,
               loc_c.razao_social as NOME_EMPRESA_PJ,
               loc_c.nome as NOME_EMPRESA_PL
        FROM VINCULOS_VAGA VINC_A
                 INNER JOIN VAGAS_APRENDIZ VAGA_A ON VAGA_A.CODIGO_DA_VAGA = VINC_A.CODIGO_VAGA
                 INNER JOIN TURMAS T ON T.ID_VAGA_APRENDIZ = VAGA_A.ID
                 INNER JOIN REP_LOCAIS_CONTRATO LOC_C ON LOC_C.ID = VAGA_A.ID_LOCAL_CONTRATO
                 INNER JOIN REP_LOCAIS_ENDERECOS LOC_E ON LOC_C.ID = LOC_E.ID_LOCAL_CONTRATO AND LOC_E.DELETADO = 0
                 INNER JOIN REP_ENDERECOS END ON LOC_E.ID_ENDERECO = END.ID
                 LEFT JOIN BENEFICIOS_ADIC_APRENDIZ B ON B.ID_VAGA_APRENDIZ = VAGA_A.ID
                 LEFT JOIN pcd_aprendiz  ON pcd_aprendiz.ID_VAGA_APRENDIZ = VAGA_A.ID
        WHERE VINC_A.SITUACAO_VINCULO <> 5
        GROUP BY ID_ESTUDANTE, CODIGO_VAGA, VAGA_A.ID_LOCAL_CONTRATO, CNPJ, 'APRENDIZ', TIPO_DIVULGACAO, ID_AREA_ATUACAO_APRENDIZ, NOME_CURSO,
                 VALOR_SALARIO, VALOR_SALARIO_DE, VALOR_SALARIO_ATE, TIPO_SALARIO_VALOR, END.LATITUDE, END.LONGITUDE, pcd_aprendiz.ID, loc_c.razao_social,loc_c.nome

    );

