
ALTER TABLE PARAMETROS_EMPRESA_CONTRATO
    ADD (
        MSG_ADICIONAL_BACKOFFICE VARCHAR2(500) NULL,
        MSG_ADICIONAL_EMPRESA VARCHAR2(500) NULL,
        MSG_ADICIONAL_ESTUDANTE VARCHAR2(500) NULL
        );

