CREATE TABLE REP_LOCAIS_REPRESENTANTES
(ID NUMBER not null,
ID_LOCAL_CONTRATO NUMBER not null,
ID_REPRESENTANTE  NUMBER not null,
TIPO VARCHAR2(50),
DATA_CRIACAO TIMESTAMP(6) not null,
DATA_ALTERACAO TIMESTAMP(6) not null,
CRIADO_POR VARCHAR2(255),
MODIFICADO_POR VARCHAR2(255),
DELETADO NUMBER(1));

ALTER TABLE REP_LOCAIS_REPRESENTANTES ADD CONSTRAINT KRS_INDICE_03736 PRIMARY KEY (ID);

ALTER TABLE REP_LOCAIS_REPRESENTANTES ADD CONSTRAINT KRS_INDICE_03737 FOREIGN KEY
    (ID_LOCAL_CONTRATO) REFERENCES REP_LOCAIS_CONTRATO (ID);

ALTER TABLE REP_LOCAIS_REPRESENTANTES ADD CONSTRAINT KRS_INDICE_03738 FOREIGN KEY
    (ID_REPRESENTANTE) REFERENCES REP_REPRESENTANTES (ID);
