
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
ADD ID_VINCULO_VAGA NUMBER(20) NULL;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
  ADD CONSTRAINT krs_indice_02231 FOREIGN KEY ( ID_VINCULO_VAGA )
    REFERENCES VINCULOS_VAGA ( id )
      NOT DEFERRABLE;