comment on column VINCULOS_VAGA.ENVIADO_URA is 'Enum:
0 - PENDENTE ENVIO URA
1 - ENVIADO PARA URA
2 - LIBERADO PARA URA';

ALTER TABLE {{user}}.VINCULOS_VAGA ADD DATA_EMAIL TIMESTAMP(6);
ALTER TABLE {{user}}.VINCULOS_VAGA ADD DATA_SMS TIMESTAMP(6);
ALTER TABLE {{user}}.VINCULOS_VAGA ADD PRIORIZACAO_CTO NUMBER;
ALTER TABLE {{user}}.VINCULOS_VAGA ADD IDENTIFICACAO_CTO VARCHAR(2);
