ALTER TABLE QUALIFICACOES_ESTUDANTE DROP COLUMN MOTIVOS_QUALIFICACAO;
ALTER TABLE QUALIFICACOES_ESTUDANTE DROP COLUMN NOME;
ALTER TABLE QUALIFICACOES_ESTUDANTE MODIFY NOTA_OBTIDA NUMBER(4,1);
ALTER TABLE QUALIFICACOES_ESTUDANTE ADD DATA_ALTERACAO TIMESTAMP;

CREATE TABLE QUALIFICACOES_MOTIVOS (
       ID                           NUMBER(20) NOT NULL,
       ID_QUALIFICACAO_ESTUDANTE    NUMBER(20) NOT NULL,
       MOTIVO                       VARCHAR2(255) NOT NULL,
       CRIADO_POR                   VARCHAR2(255),
       DATA_CRIACAO                 TIMESTAMP NOT NULL,
       DATA_ALTERACAO               TIMESTAMP,
       MODIFICADO_POR               VARCHAR2(255),
       DELETADO                     NUMBER(1)
);

ALTER TABLE QUALIFICACOES_MOTIVOS ADD CONSTRAINT KRS_INDICE_02641 PRIMARY KEY (ID);
ALTER TABLE QUALIFICACOES_MOTIVOS ADD CONSTRAINT KRS_INDICE_02642 FOREIGN KEY (ID_QUALIFICACAO_ESTUDANTE)
    REFERENCES QUALIFICACOES_ESTUDANTE (ID);

CREATE SEQUENCE SEQ_QUALIFICACOES_MOTIVOS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
