
--
-- REMOVENDO E RENOMENADO COLUNAS DE DESTAQUES
--
ALTER TABLE DESTAQUES_AREAS_PROF_TCE DROP (ID_AREA_ATUACAO,DESCRICAO_AREA_ATUACAO);
ALTER TABLE DESTAQUES_AREAS_PROF_TCE RENAME COLUMN MUNICIPIO TO CIDADE;

ALTER TABLE DESTAQUES_AREAS_PROF_TCE_EMP DROP (ID_AREA_ATUACAO,DESCRICAO_AREA_ATUACAO,ID_CONTRATO);
ALTER TABLE DESTAQUES_AREAS_PROF_TCE_EMP RENAME COLUMN MUNICIPIO TO CIDADE;

ALTER TABLE DESTAQUES_AREAS_ATUA_TCE DROP COLUMN ID_CONTRATO;
ALTER TABLE DESTAQUES_AREAS_ATUA_TCE RENAME COLUMN MUNICIPIO TO CIDADE;

ALTER TABLE DESTAQUES_AREAS_ATUA_TCE_EMP DROP COLUMN ID_CONTRATO;
ALTER TABLE DESTAQUES_AREAS_ATUA_TCE_EMP RENAME COLUMN MUNICIPIO TO CIDADE;
