--
-- #### Renomeando colunas da tabela FERRAMENTAS_SELECAO
--
alter table {{user}}.FERRAMENTAS_SELECAO RENAME COLUMN FERRAMENTA_PRESENCIAL TO TIPO_FERRAMENTA_SELECAO;
alter table {{user}}.FERRAMENTAS_SELECAO RENAME COLUMN DISPONIVEL TO RESPONSAVEL_FERRAMENTA;