ALTER TABLE REP_PARAMETROS_PROGRAMA_EST ADD DIAS_TERMINO_CONTR_PRORROGACAO_EMP NUMBER(3);
UPDATE REP_PARAMETROS_PROGRAMA_EST SET DIAS_TERMINO_CONTR_PRORROGACAO_EMP = 30 WHERE CODIGO_CIEE = 1 OR CODIGO_CIEE = 2;
