-- Criando coluna de Sigla de Nivel Educacao para Pre-Contrato/Contrato

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA ADD SIGLA_NIVEL_EDUCACAO_ESTUDANTE VARCHAR2(2 BYTE);
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA ADD SIGLA_NIVEL_EDUCACAO_ESTUDANTE VARCHAR2(2 BYTE);