--
-- #### Renomeando colunas e criando coluna na tabela TIPO_PROVA
--
ALTER TABLE {{user}}.TIPO_PROVA RENAME COLUMN INSTRUCOES_APOIO TO INSTRUCOES_ACESSO;
ALTER TABLE {{user}}.TIPO_PROVA RENAME COLUMN VALIDADE_PROVA TO DATA_VALIDADE_PROVA;
ALTER TABLE {{user}}.TIPO_PROVA ADD (HORA_VALIDADE_PROVA TIMESTAMP (6));
