CREATE TABLE REP_CIEES
(ID NUMBER(19) not null,
CRIADO_POR VARCHAR2(255 char),
DATA_CRIACAO TIMESTAMP(6) not null,
DELETADO NUMBER(1) not null,
MODIFICADO_POR VARCHAR2(255 char),
DATA_ALTERACAO TIMESTAMP(6) not null,
ATIVO NUMBER(1) not null,
CNPJ VARCHAR2(14 char)  not null,
DESCRICAO VARCHAR2(100 char) not null,
UF VARCHAR2(2 char),
ID_DOMINIO NUMBER(19)
);

ALTER TABLE REP_CIEES ADD CONSTRAINT KRS_INDICE_03720 PRIMARY KEY (ID);
ALTER TABLE REP_CIEES ADD CONSTRAINT  KRS_INDICE_03721 UNIQUE (DESCRICAO);


