ALTER TABLE REP_TEMAS_REDACAO MODIFY ID NUMBER(20);

ALTER TABLE REP_REDACOES MODIFY ID NUMBER(20);
ALTER TABLE REP_REDACOES MODIFY ID_ESTUDANTE NUMBER(20);
ALTER TABLE REP_REDACOES MODIFY ID_TEMA NUMBER(20);