CREATE TABLE PERGUNTAS_TIPOS_RELATORIO
(
    ID_PERGUNTA NUMBER(19) not null,
    TIPO_RELATORIO NUMBER(1)
);

COMMENT ON COLUMN PERGUNTAS_TIPOS_RELATORIO.TIPO_RELATORIO IS
    'ENUM:

0-Relatorio de Atividades
1-Relatorio de Estagio
2-Termo de Realizacao de Estagio';

ALTER TABLE PERGUNTAS_TIPOS_RELATORIO ADD CONSTRAINT KRS_INDICE_04040 PRIMARY KEY (ID_PERGUNTA, TIPO_RELATORIO);

ALTER TABLE PERGUNTAS_TIPOS_RELATORIO ADD CONSTRAINT KRS_INDICE_04041 FOREIGN KEY (ID_PERGUNTA)
    REFERENCES perguntas_formularios (id);

ALTER TABLE perguntas_formularios DROP COLUMN tipo_relatorio;

