ALTER TABLE SOLICITACOES_SERVICENOW MODIFY SITUACAO_TICKET NUMBER(2);

COMMENT ON COLUMN SOLICITACOES_SERVICENOW.SITUACAO_TICKET IS
'ENUM:

1 - Novo
2 - Em andamento
3 - Em espera
4 - Aguardando solicitante
5 - Aguardando informação
6 - Resolvido
7 - Fechado
8 - Cancelado';


COMMENT ON COLUMN GRUPOS_ATENDIMENTOS.SITUACAO IS  'FLAG:

0-INATIVO
1-ATIVO'

