COMMENT ON COLUMN VINCULOS_VAGA.RESP_SELECAO_CONVOCACAO IS
  'Enum:

0 - CIEE-NOTURNA
1 - CIEE-INTERNO
2 - EMPRESA
3 - ESTUDANTE';

COMMENT ON COLUMN VINCULOS_VAGA.RESP_SELECAO_ENCAMINHAMENTO IS
  'Enum:

0 - CIEE-NOTURNA
1 - CIEE-INTERNO
2 - EMPRESA
3 - ESTUDANTE';

COMMENT ON COLUMN VINCULOS_VAGA.RESP_SELECAO_CONTRATO IS
  'Enum:

0 - CIEE-NOTURNA
1 - CIEE-INTERNO
2 - EMPRESA
3 - ESTUDANTE';