ALTER TABLE HIST_CONTRATOS_ESTUDANTES_EMPRESA ADD ID_CONTR_EMP_EST NUMBER(20) NOT NULL;

ALTER TABLE HIST_CONTRATOS_ESTUDANTES_EMPRESA ADD CONSTRAINT KRS_INDICE_03534 FOREIGN KEY
    (ID_CONTR_EMP_EST) REFERENCES CONTRATOS_ESTUDANTES_EMPRESA(ID);