ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA RENAME COLUMN ANO_ATUAL_CURSO_ESTUDANTE TO PERIODO_ATUAL;
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA RENAME COLUMN SEMESTRE_ATUAL_CURSO_ESTUDANTE TO TIPO_DURACAO_CURSO;  
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA ADD contrapartida_aux_transporte VARCHAR2(100);  
