
ALTER TABLE REP_UNIDADES_CIEE ADD ID_PESSOA_RESPONSAVEL   NUMBER(19);

ALTER TABLE REP_UNIDADES_CIEE ADD CONSTRAINT KRS_INDICE_04009 FOREIGN KEY (ID_PESSOA_RESPONSAVEL)
    references REP_PESSOAS(ID);