
-- Renomeando ASSUNTO para DESCRICAO para fazer mais sentido com a regra de negocios
ALTER TABLE AGENDAS_EMPRESAS_CONTRATADOS RENAME COLUMN ASSUNTO TO DESCRICAO;

-- Limpando a tabela para ter certeza que não ocorrerá problemas para adicionar colunas com NOT NULL;
TRUNCATE TABLE AGENDAS_EMPRESAS_CONTRATADOS;

-- Adicionando colunas faltantes
ALTER TABLE AGENDAS_EMPRESAS_CONTRATADOS ADD NOME_CONTATO VARCHAR2(60) NOT NULL;
ALTER TABLE AGENDAS_EMPRESAS_CONTRATADOS ADD DEPARTAMENTO VARCHAR2(40);
ALTER TABLE AGENDAS_EMPRESAS_CONTRATADOS ADD EMAIL VARCHAR2(40);
ALTER TABLE AGENDAS_EMPRESAS_CONTRATADOS ADD TELEFONE VARCHAR2(20);
ALTER TABLE AGENDAS_EMPRESAS_CONTRATADOS ADD AGENDAR_PARA TIMESTAMP;
