
---
--- PRE CONTRATO
---
ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN NOME_SUPERVIDOR TO NOME_SUPERVISOR;

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN CPF_SUPERVIDOR TO CPF_SUPERVISOR;

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN CARGO_SUPERVIDOR TO CARGO_SUPERVISOR;

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN FORMACAO_SUPERVIDOR TO FORMACAO_SUPERVISOR;

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN ID_CONSELHO_CLASSE_SUPERVIDOR TO ID_CONSELHO_CLASSE_SUPERVISOR;

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
ADD CONTA_CORRENTE_DIGITO VARCHAR2(2);

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
MODIFY CONTA_CORRENTE VARCHAR2(50);

---
--- CONTRATO
---
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN NOME_SUPERVIDOR TO NOME_SUPERVISOR;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN CPF_SUPERVIDOR TO CPF_SUPERVISOR;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN CARGO_SUPERVIDOR TO CARGO_SUPERVISOR;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN FORMACAO_SUPERVIDOR TO FORMACAO_SUPERVISOR;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
RENAME COLUMN ID_CONSELHO_CLASSE_SUPERVIDOR TO ID_CONSELHO_CLASSE_SUPERVISOR;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
ADD CONTA_CORRENTE_DIGITO VARCHAR2(2);

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
MODIFY CONTA_CORRENTE VARCHAR2(50);
