ALTER TABLE REP_PARAMETROS_PROGRAMA_APR ADD MINIMO_FERIAS_MES NUMBER(5);
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR ADD MAXIMO_FERIAS_MES NUMBER(5);
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR ADD LIMITE_RETROATIVO NUMBER(5);
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR ADD HORARIO_INICIO NUMBER(2);
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR ADD HORARIO_MAXIMO NUMBER(2);
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR ADD HORARIO_MAXIMO_MENOR NUMBER(2);

UPDATE REP_PARAMETROS_PROGRAMA_APR SET MINIMO_FERIAS_MES = 10 WHERE CODIGO_CIEE = 1 OR CODIGO_CIEE = 2;
UPDATE REP_PARAMETROS_PROGRAMA_APR SET MAXIMO_FERIAS_MES = 30 WHERE CODIGO_CIEE = 1 OR CODIGO_CIEE = 2;
UPDATE REP_PARAMETROS_PROGRAMA_APR SET LIMITE_RETROATIVO = 30 WHERE CODIGO_CIEE = 1 OR CODIGO_CIEE = 2;
UPDATE REP_PARAMETROS_PROGRAMA_APR SET HORARIO_INICIO = 6 WHERE CODIGO_CIEE = 1 OR CODIGO_CIEE = 2;
UPDATE REP_PARAMETROS_PROGRAMA_APR SET HORARIO_MAXIMO = 22 WHERE CODIGO_CIEE = 1 OR CODIGO_CIEE = 2;
UPDATE REP_PARAMETROS_PROGRAMA_APR SET HORARIO_MAXIMO_MENOR = 18 WHERE CODIGO_CIEE = 1 OR CODIGO_CIEE = 2;

ALTER TABLE REP_PARAMETROS_PROGRAMA_APR MODIFY MINIMO_FERIAS_MES NUMBER(5) NOT NULL;
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR MODIFY MAXIMO_FERIAS_MES NUMBER(5) NOT NULL;
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR MODIFY LIMITE_RETROATIVO NUMBER(5) NOT NULL;
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR MODIFY HORARIO_INICIO NUMBER(2) NOT NULL;
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR MODIFY HORARIO_MAXIMO NUMBER(2) NOT NULL;
ALTER TABLE REP_PARAMETROS_PROGRAMA_APR MODIFY HORARIO_MAXIMO_MENOR NUMBER(2) NOT NULL;