ALTER TABLE ACOMPANHAMENTOS_VAGAS ADD (TEMP_DESCRICAO  CLOB);

UPDATE ACOMPANHAMENTOS_VAGAS SET TEMP_DESCRICAO = DESCRICAO;

ALTER TABLE ACOMPANHAMENTOS_VAGAS DROP COLUMN DESCRICAO;

ALTER TABLE ACOMPANHAMENTOS_VAGAS RENAME COLUMN TEMP_DESCRICAO TO DESCRICAO;