
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA
ADD STATUS_TRE NUMBER(1) DEFAULT 0;

COMMENT ON COLUMN CONTRATOS_ESTUDANTES_EMPRESA.STATUS_TRE IS
    'Flag:

    0 - Não
    1 - Sim';

ALTER TABLE HIST_CONTRATOS_ESTUDANTES_EMPRESA
ADD STATUS_TRE NUMBER(1) DEFAULT 0;

COMMENT ON COLUMN HIST_CONTRATOS_ESTUDANTES_EMPRESA.STATUS_TRE IS
    'Flag:

    0 - Não
    1 - Sim';