
ALTER TABLE REP_PARAMETROS_PROGRAMA_EST ADD LIMITE_RETROATIVO NUMBER(5);

UPDATE REP_PARAMETROS_PROGRAMA_EST SET LIMITE_RETROATIVO = 30 WHERE CODIGO_CIEE = 1 OR CODIGO_CIEE = 2;

ALTER TABLE REP_PARAMETROS_PROGRAMA_EST MODIFY LIMITE_RETROATIVO NUMBER(5) NOT NULL;

