ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA MODIFY ID_ESTUDANTE null;
ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA MODIFY CODIGO_ESTUDANTE null;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO MODIFY DATA_INICIO NULL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO MODIFY DATA_INICIO_PERSONALIZADA NULL;
ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO MODIFY HORARIO_CURSO VARCHAR2(20);

ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO MODIFY DATA_INICIO NULL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO MODIFY DATA_INICIO_PERSONALIZADA NULL;
ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO MODIFY HORARIO_CURSO VARCHAR2(20);


