
ALTER TABLE HIST_CONTRATOS_ESTUDANTES_EMPRESA ADD DATA_FINAL_APRENDIZ  TIMESTAMP(6);

ALTER TABLE HIST_CONTRATOS_ESTUDANTES_EMPRESA ADD DATA_ORIGINAL  TIMESTAMP(6);

ALTER TABLE HIST_CONTRATOS_ESTUDANTES_EMPRESA ADD TIPO_CALCULO_SALARIO_APRENDIZ  NUMBER(1);
