INSERT INTO RECUSA (
    ID,
    DESCRICAO_MOTIVO,
    DESCRICAO_EXTERNA,
    ENVIA_COMUNICACAO,
    DISPONIVEL_ESTUDANTE,
    DISPONIVEL_EMPRESA,
    SITUACAO_MOTIVO,
    DELETADO,
    DATA_CRIACAO,
    DATA_ALTERACAO,
    CRIADO_POR,
    MODIFICADO_POR
) VALUES (
    19,
    'TELEFONE INEXISTENTE OU INVALIDO',
    'TELEFONE INEXISTENTE OU INVALIDO',
    0,
    0,
    1,
    1,
    0,
    TO_TIMESTAMP('2019-02-12 16:50:48.543000', 'YYYY-MM-DD HH24:MI:SS.FF6'),
    TO_TIMESTAMP('2019-02-12 16:50:52.393000', 'YYYY-MM-DD HH24:MI:SS.FF6'),
    'carga',
    'carga'
);