ALTER TABLE REP_ENDERECOS_ESTUDANTES ADD GEO_POINT SDO_GEOMETRY;
ALTER TABLE REP_ESCOLARIDADES_ESTUDANTES ADD GEO_POINT SDO_GEOMETRY;
ALTER TABLE REP_ENDERECOS ADD GEO_POINT SDO_GEOMETRY;
ALTER TABLE REP_ENDERECOS_ESCOLAS ADD GEO_POINT SDO_GEOMETRY;