ALTER TABLE QUALIFICACAO DROP COLUMN id_assunto;
ALTER TABLE QUALIFICACAO ADD tipo NUMBER(1) NOT NULL;

COMMENT ON COLUMN QUALIFICACAO.tipo IS
'ENUM:
0 - sem nota
1 - com nota';

CREATE TABLE QUALIFICACOES_ASSUNTOS (
    id_qualificacao NUMBER(20) NOT NULL,
    id_assunto NUMBER(20) NOT NULL
);

ALTER TABLE QUALIFICACOES_ASSUNTOS ADD CONSTRAINT krs_indice_02580 PRIMARY KEY (id_qualificacao, id_assunto);
ALTER TABLE QUALIFICACOES_ASSUNTOS ADD CONSTRAINT krs_indice_02581 FOREIGN KEY  (id_qualificacao) REFERENCES QUALIFICACAO (ID);
ALTER TABLE QUALIFICACOES_ASSUNTOS ADD CONSTRAINT krs_indice_02582 FOREIGN KEY  (id_assunto) REFERENCES ASSUNTOS_QUALIFICACAO (ID);

ALTER TABLE QUALIFICACAO MODIFY NOME VARCHAR2(255) UNIQUE;

INSERT INTO ASSUNTOS_QUALIFICACAO (ID, DISCIPLINA, CRIADO_POR, DATA_CRIACAO, DATA_ALTERACAO, MODIFICADO_POR, DELETADO) VALUES (SEQ_ASSUNTOS_QUALIFICACAO.nextval, 'Português', 'FLYWAY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'FLYWAY', 0);
INSERT INTO ASSUNTOS_QUALIFICACAO (ID, DISCIPLINA, CRIADO_POR, DATA_CRIACAO, DATA_ALTERACAO, MODIFICADO_POR, DELETADO) VALUES (SEQ_ASSUNTOS_QUALIFICACAO.nextval, 'Matemática', 'FLYWAY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'FLYWAY', 0);
INSERT INTO ASSUNTOS_QUALIFICACAO (ID, DISCIPLINA, CRIADO_POR, DATA_CRIACAO, DATA_ALTERACAO, MODIFICADO_POR, DELETADO) VALUES (SEQ_ASSUNTOS_QUALIFICACAO.nextval, 'Conhecimentos gerais', 'FLYWAY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'FLYWAY', 0);
INSERT INTO ASSUNTOS_QUALIFICACAO (ID, DISCIPLINA, CRIADO_POR, DATA_CRIACAO, DATA_ALTERACAO, MODIFICADO_POR, DELETADO) VALUES (SEQ_ASSUNTOS_QUALIFICACAO.nextval, 'Conhecimentos específicos', 'FLYWAY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'FLYWAY', 0);
INSERT INTO ASSUNTOS_QUALIFICACAO (ID, DISCIPLINA, CRIADO_POR, DATA_CRIACAO, DATA_ALTERACAO, MODIFICADO_POR, DELETADO) VALUES (SEQ_ASSUNTOS_QUALIFICACAO.nextval, 'Redação', 'FLYWAY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP,  'FLYWAY', 0);
