
ALTER TABLE REP_INFORMACOES_ADICIONAIS
    ADD NUMERO_RESERVISTA NUMBER(20);

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA
    ADD KIT_CONTRATACAO NUMBER(1) DEFAULT 0;

--
-- CRIACAO REP_ENDERECOS_EMPRESAS_CONTRATO
--

CREATE TABLE REP_ENDERECOS_EMPRESAS_CONTRATO
(
    ID                       NUMBER       not null,
    ID_ENDERECO              NUMBER,
    ENDERECO_PRINCIPAL       NUMBER(1),
    ID_INFO_EMPRESA_CONTRATO NUMBER,
    DATA_CRIACAO             TIMESTAMP(6) not null,
    DATA_ALTERACAO           TIMESTAMP(6) not null,
    CRIADO_POR               VARCHAR2(255 char),
    MODIFICADO_POR           VARCHAR2(255 char),
    DELETADO                 NUMBER(1),
    ID_UNIDADE_CIEE          NUMBER,
    ID_GERENCIA              NUMBER,
    DESCRICAO_GERENCIA       VARCHAR2(100 char),
    DESCRICAO_UNIDADE_CIEE   VARCHAR2(150 char)
);

ALTER TABLE REP_ENDERECOS_EMPRESAS_CONTRATO
    ADD CONSTRAINT krs_indice_03437 PRIMARY KEY (ID);

ALTER TABLE REP_ENDERECOS_EMPRESAS_CONTRATO
    ADD CONSTRAINT krs_indice_03438 FOREIGN KEY (ID_ENDERECO)
        REFERENCES REP_ENDERECOS (ID);

ALTER TABLE REP_ENDERECOS_EMPRESAS_CONTRATO
    ADD CONSTRAINT krs_indice_03439 FOREIGN KEY (ID_INFO_EMPRESA_CONTRATO)
        REFERENCES REP_INFO_CONTRATO_EMPRESAS (ID);

