-- CRIANDO OS CAMPOS NAS REPLICAS ENVOLVIDAS

ALTER TABLE REP_APOLICES_CIEE ADD subfatura_seguradora VARCHAR2(2 CHAR);

-- GERAR CERTIFICADO DA APOLICE DE SEGUROS DO ESTAGIARIO CIEE

CREATE OR REPLACE VIEW V_APOLICE_SEGURO_ESTAGIARIO_CIEE AS
    (
        SELECT DISTINCT
            TCE.ID_ESTUDANTE AS ID_ESTUDANTE,
        	TCE.NUMERO_EMPRESA AS NUMERO_EMPRESA,
        	REM.NOME AS EMPRESA,
        	REM.CNPJ AS CNPJ,
        	RLT.ID_TELEFONE AS ID_TELEFONE_LOCAL_CONTRATO,
        	RUC.ID AS CODIGO_CIEE,
        	RUC.DESCRICAO AS DESCRICAO_CIEE,
        	RCA.NOME_FANTASIA AS CAMPUS_CIEE,
        	RCI.CNPJ AS CNPJ_CIEE,
            RAC.DATA_TERMINO AS DATA_TERMINO,
        	RAC.DATA_INICIO AS DATA_INICIO,
        	RAC.SUSEP_APOLICE AS SUSEP_APOLICE,
        	RAC.SUSEP_SEGURADORA AS SUSEP_SEGURADORA,
        	RAC.SUCURSAL_SEGURADORA AS SUCURSAL_SEGURADORA,
        	RAC.SUBFATURA_SEGURADORA AS SUBFATURA_SEGURADORA,
        	RAC.NUMERO AS NUMERO_APOLICE,
        	RVAC.MORTE AS VALOR_MORTE,
        	RVAC.INVALIDEZ AS VALOR_INVALIDEZ,
        	RVAC.PREMIO AS VALOR_PREMIO,
        	RVAC.IOF AS VALOR_IOF,
        	RVAC.CUSTO_TOTAL AS VALOR_CUSTO_TOTAL,
        	RVAC.COBERTURA AS VALOR_COBERTURA,
        	TCE.NUMERO_END_ESTUDANTE AS NUMERO_ESTUDANTE,
        	TCE.CPF_ESTUDANTE AS CPF_ESTUDANTE,
        	TCE.TELEFONE_CONTATO AS TELEFONE_CONTATO,
        	TCE.TELEFONE_ESTUDANTE AS TELEFONE_ESTUDANTE,
        	TCE.TELEFONE_MONITOR AS TELEFONE_MONITOR,
        	TCE.CEP_END_ESTUDANTE AS CEP_END_ESTUDANTE,
        	TCE.CIDADE_END_ESTUDANTE AS CIDADE_END_ESTUDANTE,
        	TCE.BAIRRO_END_ESTUDANTE AS BAIRRO_END_ESTUDANTE,
        	TCE.UF_END_ESTUDANTE AS UF_END_ESTUDANTE,
        	TCE.COMPLEMENTO_END_ESTUDANTE AS COMPLEMENTO_END_ESTUDANTE,
        	TCE.ENDERECO_ESTUDANTE AS ENDERECO_ESTUDANTE,
        	RAC.ID_TEL_AUXILIO_FUNERAL AS ID_TEL_AUXILIO_FUNERAL,
        	RAC.ID_TEL_OUVIDORIA_SEGURADORA AS ID_TEL_OUVIDORIA_SEGURADORA
        FROM CONTRATOS_ESTUDANTES_EMPRESA    TCE
             JOIN REP_LOCAIS_CONTRATO        RLC   ON  (TCE.ID_LOCAL_CONTRATO = RLC.ID)
             JOIN REP_LOCAIS_ENDERECOS       RLE   ON  (RLE.ID_LOCAL_CONTRATO = RLC.ID)
             JOIN REP_EMPRESAS               REM   ON  (REM.CNPJ = RLC.CNPJ)
             JOIN REP_LOCAIS_TELEFONES       RLT   ON  (RLT.ID_LOCAL_CONTRATO = RLC.ID)
             JOIN REP_CONTRATOS              RCT   ON  (RCT.ID = RLC.ID_CONTRATO)
             JOIN REP_UNIDADES_CIEE          RUC   ON  (RUC.ID = RLE.ID_UNIDADE_CIEE)
			 JOIN REP_CAMPUS                 RCA   ON  (RCA.ID_ENDERECO = RLE.ID_ENDERECO)
			 JOIN REP_CIEES                  RCI   ON  (RCI.ID = RLE.ID_UNIDADE_CIEE)
             JOIN REP_APOLICES_CIEE          RAC   ON  (RAC.ID = RCT.ID_APOLICES_CIEE)
             JOIN REP_APOLICES_VALORES       RAV   ON  (RAV.ID_APOLICE = RAC.ID)
             JOIN REP_VALORES_APOLICES_CIEE  RVAC  ON  (RAV.ID_APOLICE = RAC.ID)
    WHERE   RLC.DELETADO = 0 AND RCT.DELETADO = 0 AND REM.DELETADO = 0
 );


