CREATE TABLE REP_CONFIGURACAO_CONTRATOS
(ID NUMBER not null,
NUMERO_CONTRATO VARCHAR2(50 char),
ID_CONTRATO NUMBER not null,
TIPO_DOCUMENTO  VARCHAR2(10 char),
INFORMACOES_GERAIS VARCHAR2(150 char),
CENTRALIZAR_ADM_FINANCEIRA NUMBER(1) default 0,
PROCESSO_SELETIVO NUMBER(1) default 0,
CONTRATO_UNICO NUMBER(1) default 0,
ID_UNIDADE_CIEE NUMBER,
ID_ASSISTENTE NUMBER,
QTDE_EMPREGADOS NUMBER(5),
QTDE_PRESTADORES_SERVICO NUMBER(5),
DATA_INICIO_CONTRATO TIMESTAMP(6),
DATA_ASSINATURA_CONTRATO TIMESTAMP(6),
VALIDADE_CONTRATO TIMESTAMP(6),
VALIDADE_PROVISORIA_CONTRATO TIMESTAMP(6),
DATA_CRIACAO TIMESTAMP(6) not null,
DATA_ALTERACAO TIMESTAMP(6) not null,
CRIADO_POR VARCHAR2(255 char),
MODIFICADO_POR VARCHAR2(255 char),
DELETADO NUMBER(1),
ID_CARTEIRA NUMBER
);

ALTER TABLE REP_CONFIGURACAO_CONTRATOS ADD CONSTRAINT KRS_INDICE_03776 PRIMARY KEY (ID);

ALTER TABLE REP_CONFIGURACAO_CONTRATOS ADD CONSTRAINT KRS_INDICE_03777 FOREIGN KEY
    (ID_CONTRATO) REFERENCES REP_CONTRATOS (ID);

ALTER TABLE REP_CONFIGURACAO_CONTRATOS ADD CONSTRAINT KRS_INDICE_03778 UNIQUE
    (ID_UNIDADE_CIEE, CENTRALIZAR_ADM_FINANCEIRA, ID_CONTRATO);





