--Adiciona campos a view de aprendiz vinculados

CREATE OR REPLACE VIEW SERVICE_VAGAS_DEV.V_APRENDIZES_VINCULADOS
(ID,ID_LOCAL_CONTRATO,CODIGO_DA_VAGA,DATA_CRIACAO,NUMERO_VAGAS,SITUACAO,SIGLA_SITUACAO,ID_SITUACAO_VAGA,DESCRICAO_AREA_ATUACAO,CANDIDATOS_VINCULADOS)
AS
SELECT
    VAGAS_APRENDIZ.id, VAGAS_APRENDIZ.id_local_contrato, VAGAS_APRENDIZ.codigo_da_vaga, VAGAS_APRENDIZ.DATA_CRIACAO, VAGAS_APRENDIZ.numero_vagas,
    SITUACOES.descricao AS SITUACAO, SITUACOES.sigla AS SIGLA_SITUACAO, SITUACOES.id as ID_SITUACAO_VAGA,
    AREAS_ATUACAO_APRENDIZ.descricao_area_atuacao,
    COUNT(VINCULOS_VAGA.id) AS CANDIDATOS_VINCULADOS
FROM VAGAS_APRENDIZ
    JOIN SITUACOES ON VAGAS_APRENDIZ.ID_SITUACAO_VAGA = SITUACOES.id
    JOIN AREAS_ATUACAO_APRENDIZ ON VAGAS_APRENDIZ.id_area_atuacao_aprendiz = AREAS_ATUACAO_APRENDIZ.id
    LEFT JOIN VINCULOS_VAGA on VAGAS_APRENDIZ.CODIGO_DA_VAGA = VINCULOS_VAGA.CODIGO_VAGA
    GROUP BY
        VAGAS_APRENDIZ.id, VAGAS_APRENDIZ.id_local_contrato, VAGAS_APRENDIZ.codigo_da_vaga, VAGAS_APRENDIZ.DATA_CRIACAO, VAGAS_APRENDIZ.numero_vagas,
        SITUACOES.descricao, SITUACOES.sigla, SITUACOES.id,
        AREAS_ATUACAO_APRENDIZ.descricao_area_atuacao

