-- Arrumando os IDs das tabelas OCORRENCIAS_APRENDIZ e OCORRENCIAS_ESTAGIO

ALTER TABLE {{user}}.OCORRENCIAS_APRENDIZ
DROP CONSTRAINT KRS_INDICE_01500;

ALTER TABLE {{user}}.OCORRENCIAS_APRENDIZ
ADD ID NUMBER(20) not null;

ALTER TABLE {{user}}.OCORRENCIAS_APRENDIZ
ADD CONSTRAINT KRS_INDICE_01500 PRIMARY KEY (ID);

ALTER TABLE {{user}}.OCORRENCIAS_ESTAGIO
DROP CONSTRAINT KRS_INDICE_01012;

ALTER TABLE {{user}}.OCORRENCIAS_ESTAGIO
ADD ID NUMBER(20) not null;

ALTER TABLE {{user}}.OCORRENCIAS_ESTAGIO
ADD CONSTRAINT KRS_INDICE_01012 PRIMARY KEY (ID);

CREATE SEQUENCE SEQ_OCORRENCIAS_APRENDIZ MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  ;
CREATE SEQUENCE SEQ_OCORRENCIAS_ESTAGIO MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE  ;

ALTER TABLE {{user}}.OCORRENCIAS_APRENDIZ
RENAME COLUMN DATA_COCRRENCIA TO DATA_OCORRENCIA;

ALTER TABLE {{user}}.OCORRENCIAS_APRENDIZ
MODIFY DATA_OCORRENCIA TIMESTAMP(6);

ALTER TABLE {{user}}.OCORRENCIAS_ESTAGIO
RENAME COLUMN DATA_COCRRENCIA TO DATA_OCORRENCIA;

ALTER TABLE {{user}}.OCORRENCIAS_ESTAGIO
MODIFY DATA_OCORRENCIA TIMESTAMP(6);

