CREATE TABLE PARAMETROS_URA (
  ID NUMBER(20) NOT NULL,
  SERVICO_DISPONIVEL NUMBER(1) NOT NULl,
  VAGAS_URA NUMBER NOT NULL,
  DIAS_LIBERACAO_URA NUMBER NOT NULL,
  DELETADO                  NUMBER(1),
  DATA_CRIACAO              TIMESTAMP NOT NULL,
  DATA_ALTERACAO            TIMESTAMP,
  CRIADO_POR                VARCHAR2(255),
  MODIFICADO_POR            VARCHAR2(255)
);

ALTER TABLE PARAMETROS_URA ADD CONSTRAINT KRS_INDICE_01843 PRIMARY KEY (ID);

CREATE SEQUENCE SEQ_PARAMETROS_URA MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER NOCYCLE;

INSERT INTO PARAMETROS_URA VALUES (SEQ_PARAMETROS_URA.nextval, 1, 5, 5, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'FLYWAY', 'FLYWAY')