
ALTER TABLE VAGAS_APRENDIZ
ADD ID_SITUACAO_VAGA NUMBER(20);

ALTER TABLE VAGAS_APRENDIZ
    ADD CONSTRAINT krs_indice_01320 FOREIGN KEY ( id_situacao_vaga )
        REFERENCES SITUACOES_APRENDIZ ( id );

ALTER TABLE VAGAS_APRENDIZ
ADD ID_LOCAL_CONTRATO NUMBER(20);

ALTER TABLE VAGAS_APRENDIZ
  ADD CONSTRAINT krs_indice_01330 FOREIGN KEY ( id_local_contrato )
      REFERENCES REP_LOCAIS_CONTRATO ( id )
  NOT DEFERRABLE;

