--PK-13206 Seguros Gerenciar Apólices CIEE
--Service Vagas
ALTER TABLE REP_VALORES_APOLICES_CIEE DROP (COBERTURA,TIPO_COBERTURA_APOLICE);
ALTER TABLE REP_VALORES_APOLICES_CIEE ADD COBERTURA_FAE NUMBER(20,2);
ALTER TABLE REP_VALORES_APOLICES_CIEE ADD COBERTURA_DMHO NUMBER(20,2);