--pk 14889
INSERT INTO PARAMETROS_ICN (ID, ID_PADRAO, DESCRICAO, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO) VALUES (SEQ_PARAMETROS_ICN.nextval, '999999', 'CURSO NÃO ATUALIZADO, PENDENTE DE TRATAMENTO', SYSDATE, SYSDATE, 'script', 'script', '0');
INSERT INTO PARAMETROS_ICN (ID, ID_PADRAO, DESCRICAO, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO) VALUES (SEQ_PARAMETROS_ICN.nextval, '6888', 'ESCOLA EM TRATAMENTO JUNTO A BASE CIEE', SYSDATE, SYSDATE, 'script', 'script', '0');
INSERT INTO PARAMETROS_ICN (ID, ID_PADRAO, DESCRICAO, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO) VALUES (SEQ_PARAMETROS_ICN.nextval, '9999', 'EM TRATAMENTO JUNTO A BASE CIEE', SYSDATE, SYSDATE, 'script', 'script', '0');
