-- REMOVER A PROC DE PROCESSAMENTO ANTIGA
DECLARE  
  EXISTE_PROC_PROCESSA_FILA_TRIAGEM_ESTUDANTE int :=0;
BEGIN
	Select count(*) into EXISTE_PROC_PROCESSA_FILA_TRIAGEM_ESTUDANTE
    from user_procedures where upper(OBJECT_NAME) = 'PROC_PROCESSA_FILA_TRIAGEM_ESTUDANTE';
	    if (EXISTE_PROC_PROCESSA_FILA_TRIAGEM_ESTUDANTE = 1) then
           EXECUTE IMMEDIATE 'drop procedure "SERVICE_VAGAS_DEV"."PROC_PROCESSA_FILA_TRIAGEM_ESTUDANTE"';		 
        end if;	    
END;