--
-- Criação das colunas 'CODIGO_OPERACAO' e 'TIPO_CONTA' na tabela PRE_CONTRATOS_ESTUDANTES_EMPRESA na tabela de CONTRATOS_ESTUDANTES_EMPRESA
--

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA ADD CODIGO_OPERACAO VARCHAR2(5);

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA ADD TIPO_CONTA VARCHAR2(1) DEFAULT 'C' NOT NULL;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA ADD CODIGO_OPERACAO VARCHAR2(5);

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA ADD TIPO_CONTA VARCHAR2(1) DEFAULT 'C' NOT NULL;
