

ALTER TABLE acompanhamentos_gmc ADD ID_UNIDADE_ORIGEM NUMBER(20,0);

ALTER TABLE acompanhamentos_gmc ADD ID_UNIDADE_LOCAL NUMBER(20,0);

ALTER TABLE acompanhamentos_gmc ADD ID_CARTEIRA_ORIGEM NUMBER(20,0);

ALTER TABLE acompanhamentos_gmc ADD ID_CARTEIRA_LOCAL NUMBER(20,0);