

-- Deletar os vínculos de Vagas com os Idiomas
DELETE IDIOMAS_ESTAGIO;

-- Deletar os Idiomas
DELETE IDIOMAS;

-- Equalizar todos os idiomas nos ambientes e incluir o de Libras
INSERT INTO IDIOMAS (ID, IDIOMA, DELETADO, DATA_ALTERACAO) VALUES (1, 'Italiano', 0, CURRENT_TIMESTAMP);
INSERT INTO IDIOMAS (ID, IDIOMA, DELETADO, DATA_ALTERACAO) VALUES (2, 'Inglês', 0, CURRENT_TIMESTAMP);
INSERT INTO IDIOMAS (ID, IDIOMA, DELETADO, DATA_ALTERACAO) VALUES (3, 'Japonês', 0, CURRENT_TIMESTAMP);
INSERT INTO IDIOMAS (ID, IDIOMA, DELETADO, DATA_ALTERACAO) VALUES (4, 'Espanhol', 0, CURRENT_TIMESTAMP);
INSERT INTO IDIOMAS (ID, IDIOMA, DELETADO, DATA_ALTERACAO) VALUES (5, 'Alemão', 0, CURRENT_TIMESTAMP);
INSERT INTO IDIOMAS (ID, IDIOMA, DELETADO, DATA_ALTERACAO) VALUES (6, 'Francês', 0, CURRENT_TIMESTAMP);
INSERT INTO IDIOMAS (ID, IDIOMA, DELETADO, DATA_ALTERACAO) VALUES (7, 'Libras', 0, CURRENT_TIMESTAMP);
