CREATE OR REPLACE PROCEDURE PROC_CLASSIFICACOES_ESTUDANTES_INC_FILA
(
  PARAM_ID_ESTUDANTE IN NUMBER
, PARAM_ID_REGRA IN NUMBER
) AS

QTD_ESTUDANTE NUMBER;
BEGIN
    -- verifica se existe o estudante está ativo e custando su || te
    SELECT COUNT(E.ID) INTO QTD_ESTUDANTE FROM REP_ESCOLARIDADES_ESTUDANTES EE
    INNER JOIN REP_ESTUDANTES E ON E.ID = EE.ID_ESTUDANTE
    WHERE
    E.DELETADO = 0
    AND EE.DELETADO = 0
    AND E.SITUACAO = 'ATIVO'
    AND SIGLA_NIVEL_EDUCACAO IN('SU', 'TE')
    AND STATUS_ESCOLARIDADE IN('CURSANDO')
    AND E.ID = PARAM_ID_ESTUDANTE;

    -- inclue o estu na fila
    IF(QTD_ESTUDANTE = 1) THEN

        INSERT INTO ESTUDANTES_PASSIVEIS_CLASSIFICACOES
        (ID, ID_ESTUDANTE, ID_CLASSIFICACOES_PARAMETROS_ITENS, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, DELETADO)
        VALUES(
            SEQ_ESTUDANTES_PASSIVEIS_CLASSIFICACOES.NEXTVAL,
            PARAM_ID_ESTUDANTE,
            PARAM_ID_REGRA,
            CURRENT_DATE,
            CURRENT_DATE,
            'PROC_CLASSIFICACOES_ESTUDANTES_INC_FILA',
            'PROC_CLASSIFICACOES_ESTUDANTES_INC_FILA',
            0
        );

    END IF;
END;