DECLARE
    CONSTRAINT_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT (CONSTRAINT_NOT_EXISTS , -2443);
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.REP_LOCAIS_TELEFONES
    DROP CONSTRAINT REP_LOCAIS_TELEFONES_FK1';
    EXCEPTION WHEN CONSTRAINT_NOT_EXISTS THEN NULL;
END;
/

DECLARE
    CONSTRAINT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT (CONSTRAINT_EXISTS , -02275);
BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.REP_LOCAIS_TELEFONES
	ADD CONSTRAINT REP_LOCAIS_TELEFONES_FK1 FOREIGN KEY
	(ID_TELEFONE)
	REFERENCES SERVICE_VAGAS_DEV.REP_TELEFONES_COMPANY
	(ID) DISABLE';
    EXCEPTION WHEN CONSTRAINT_EXISTS THEN NULL;
END;
/

ALTER TABLE SERVICE_VAGAS_DEV.REP_ATIVIDADES
MODIFY (DESCRICAO_ATIVIDADE VARCHAR2(200 CHAR) );

ALTER TABLE SERVICE_VAGAS_DEV.REP_PARAMETROS_CIEE_COMPANY  
MODIFY (QTD_DIA_APOS_INICIO_CONTRATO NUMBER(15, 0) );

ALTER TABLE SERVICE_VAGAS_DEV.REP_PARAMETROS_CIEE_COMPANY  
MODIFY (QTD_DIA_MAX_ASSINAR_CONTRATO NUMBER(15, 0) );

COMMENT ON TABLE "SERVICE_VAGAS_DEV"."REP_VIDEOS_CURRICULOS_ESTUDANTES_STUDENT"  IS 'STUDENT_DEV:SERVICE_STUDENT_DEV:VIDEOS_CURRICULOS_ESTUDANTES';