-- PK-14129 - Cancelar vagas automatico (Job)
CREATE TABLE CONTRATOS_EMPRESAS_SEM_CANCELAMENTOS (
    ID             NUMBER(20) NOT NULL,
    DATA_CRIACAO   TIMESTAMP NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    CRIADO_POR     VARCHAR2(255 CHAR),
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DELETADO       NUMBER(1) DEFAULT 0,
    ID_EMPRESA     NUMBER(20),
    ID_CONTRATO    NUMBER(20)
);
ALTER TABLE CONTRATOS_EMPRESAS_SEM_CANCELAMENTOS ADD CONSTRAINT KRS_INDICE_07740 PRIMARY KEY (ID);
ALTER TABLE CONTRATOS_EMPRESAS_SEM_CANCELAMENTOS ADD CONSTRAINT KRS_INDICE_07741 FOREIGN KEY (ID_EMPRESA) REFERENCES REP_EMPRESAS (ID);
ALTER TABLE CONTRATOS_EMPRESAS_SEM_CANCELAMENTOS ADD CONSTRAINT KRS_INDICE_07742 FOREIGN KEY (ID_CONTRATO) REFERENCES REP_CONTRATOS (ID);
CREATE SEQUENCE SEQ_CONTRATOS_EMPRESAS_SEM_CANCELAMENTOS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;