-- Criação de novas colunas de nivel do relatorio na tabela formulario

ALTER TABLE FORMULARIOS DROP COLUMN NIVEL_RELATORIO;
ALTER TABLE FORMULARIOS ADD NIVEL_RELATORIO_SUPERIOR NUMBER(1,0);
ALTER TABLE FORMULARIOS ADD NIVEL_RELATORIO_TECNICO NUMBER(1,0);
ALTER TABLE FORMULARIOS ADD NIVEL_RELATORIO_MEDIO_OUTROS NUMBER(1,0);