------------------------------------------------------

-- Criar tabela de DESCANSO_SEMANAL_APRENDIZ

------------------------------------------------------

-- Tabela
create table DESCANSO_SEMANAL_APRENDIZ (
  ID NUMBER(20) NOT NULL,
  ID_CONTRATO NUMBER(20) NOT NULL,
  MODELO_CALENDARIO VARCHAR2(20),
  FOLGAS VARCHAR2(100),
  TIPO_DOMINGO VARCHAR2(20),
  PRIMEIRA_FOLGA VARCHAR2(20),
  DOMINGOS_TRABALHADOS NUMBER(5),
  TROCAR_FOLGA VARCHAR2(20),
  TROCAR_FOLGA_DIA VARCHAR2(20),
  DATA_CRIACAO TIMESTAMP(6),
  DATA_ALTERACAO TIMESTAMP(6),
  CRIADO_POR VARCHAR2(255 CHAR),
  MODIFICADO_POR VARCHAR2(255 CHAR),
  DELETADO NUMBER(1)
);

-- PK 
ALTER TABLE DESCANSO_SEMANAL_APRENDIZ ADD CONSTRAINT KRS_INDICE_11260 PRIMARY KEY (ID);


-- Criação da sequencia para a tabela DESCANSO_SEMANAL_APRENDIZ coluna ID

CREATE SEQUENCE  SEQ_DESCANSO_SEMANAL_APRENDIZ
MINVALUE 1 
MAXVALUE 9999999999999999999999999999 
INCREMENT BY 1 
START WITH 1 
CACHE 20 
NOORDER  
NOCYCLE;