UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'A empresa não possui previsão para definição da vaga', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'A EMPRESA NAO POSSUI PREVISAO P/ DEFINICAO DA VAGA';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Adequações internas nova lei de estágio', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'ADEQUACOES INTERNAS NOVA LEI DE ESTAGIO';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Alteração de razão social da empresa', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'ALTERACAO DE RAZAO SOCIAL DA EMPRESA';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Alteração plano/estrutura', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'ALTERACAO PLANO/ESTRUTURA ';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Atividades extintas ou remanejadas', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'ATIVIDADES EXTINTAS OU REMANEJADAS';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Contenção de custos', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'CONTENCAO DE CUSTOS';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Covid-19', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'COVID-19'; 

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Débito de FCB - sem previsão para pagamento', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'DEBITO DE FCB - SEM PREVISAO PARA PAGAMENTO';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Dificuldade no preenchimento por parte do CIEE', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'DIFICULDADE NO PREENCHIMENTO POR PARTE DO CIEE';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Diminuição de vagas', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'Diminuicao de Vagas';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Duplicidade de OE', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'DUPLICIDADE DE OE';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Empresa não responde aos contatos e visitas do CIEE', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'EMPRESA NAO RESPONDE AOS CONTATOS E VISITAS DO CIEE';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Empresa possui restrição Serasa', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'EMPRESA POSSUI RESTRICAO SERASA';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Estímulo banco processo seletivo público', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'ESTIMULO BANCO PS PUBLICO';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Estudante demorou para providenciar documentação', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'ESTUDANTE DEMOROU P/ PROVIDENCIAR DOCUMENTACAO';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Mudança no perfil da OE', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'MUDANCA NO PERFIL DA OE';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Não concorda com novos critérios - ensino médio', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'NAO CONCORDA C/ NOVOS CRITERIOS - ENSINO MEDIO';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Nível fraco dos estudantes', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'NIVEL FRACO DOS ESTUDANTES';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'OE aberta em duplicidade - via Internet', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'OE ABERTA EM DUPLICIDADE - VIA INTERNET';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'OE cancelada - não renovação de contrato empresa', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'OE CANCELADA - NAO RENOVACAO DE CONTRATO EMPRESA';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'OE preenchida por concorrente e outros meios', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'OE PREENCHIDA POR CONCORRENTE E OUTROS MEIOS';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Processo Especial - empresa não faz TCE pelo CIEE', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'PE - EMPRESA NAO FAZ TCE PELO CIEE';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Preenchida via CLT', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'PREENCHIDA VIA CLT';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Preenchimento previsto para início próximo ano', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'PREENCHIMENTO PREVISTO P/ INICIO PROX.ANO';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Sazonalidade', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'SAZONALIDADE';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Sem interesse do estudante. Bolsa-Auxílio baixa, sem benefícios', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'SEM INTERESSE DO ESTUD.-BA BAIXA, SEM BENEFICIOS';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Sem retorno da solicitação de visita', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'SEM RETORNO DA SOLICITACAO DE VISITA';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Solicitado pela CEF via portal', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'SOLICITADO PELA CEF VIA PORTAL';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Uso indevido dos serviços do CIEE', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'USO INDEVIDO DOS SERVICOS DO CIEE'; 

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Vaga aberta para convênio errado',  DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'VAGA ABERTA PARA CONVENIO ERRADO';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Vaga não caracteriza estágio', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'VAGA NAO CARACTERIZA ESTAGIO ';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Vaga PRD - estudante desistiu', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'VAGA PRD - ESTUDANTE DESISTIU';

UPDATE MOTIVOS_CANCELAMENTO_VAGA
SET DESCRICAO = 'Vaga será trabalhada pelo Processo Especial', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19164' WHERE DESCRICAO = 'VAGA SERA TRABALHADA PELO P.E.';

INSERT INTO MOTIVOS_CANCELAMENTO_VAGA
(ID, DESCRICAO, ORIGEM, ATIVO, DELETADO,DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR)
SELECT SEQ_MOTIVOS_CANCELAMENTO_VAGA.nextval,'Curso de aprendizagem em processo de validação', 1, 1, 0, sysdate ,sysdate,'PK-19164', 'PK-19164' FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM MOTIVOS_CANCELAMENTO_VAGA WHERE DESCRICAO = 'Curso de aprendizagem em processo de validação' AND ATIVO = 1 );