
declare
    column_exists exception;
    pragma exception_init (column_exists , -01430);
begin
    execute immediate 'ALTER TABLE CURSOS_MTE ADD ID_LOCAL_CAPACITACAO NUMBER(19,0) NULL';
    exception when column_exists then null;
end;
/

ALTER TABLE CURSOS_MTE ADD CONSTRAINT KRS_INDICE_11280 FOREIGN KEY ( ID_LOCAL_CAPACITACAO ) REFERENCES LOCAIS_CAPACITACAO( ID ) NOT DEFERRABLE;

create table CONTRATOS_CURSOS_MTE (
ID			NUMBER(19,0) NOT NULL,
ID_CURSO_MTE	NUMBER(19,0) NOT NULL,
ID_CONTRATO		NUMBER(19,0) NOT NULL,
CRIADO_POR		VARCHAR2(255 CHAR) NOT NULL,
DATA_CRIACAO		TIMESTAMP NOT NULL,
MODIFICADO_POR		VARCHAR2(255 CHAR),
DATA_ALTERACAO		TIMESTAMP,
DELETADO		NUMBER(1) NOT NULL
);

ALTER TABLE CONTRATOS_CURSOS_MTE ADD CONSTRAINT KRS_INDICE_11281 PRIMARY KEY ( ID );
ALTER TABLE CONTRATOS_CURSOS_MTE ADD CONSTRAINT KRS_INDICE_11282 FOREIGN KEY ( ID_CURSO_MTE ) REFERENCES CURSOS_MTE( ID ) NOT DEFERRABLE;

CREATE SEQUENCE SEQ_CONTRATOS_CURSOS_MTE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;