--
-- Alteração temporária da coluna 'TIPO_CONTA' na tabela PRE_CONTRATOS_ESTUDANTES_EMPRESA e CONTRATOS_ESTUDANTES_EMPRESA
--

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA MODIFY TIPO_CONTA NULL;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA MODIFY TIPO_CONTA NULL;
