ALTER TABLE REP_PARAMETROS_PROGRAMA_EST
    ADD (
        JORNADA_MINIMA_DIARIA NUMBER(2),
        JORNADA_MINIMA_SEMANAL NUMBER(2),
        JORNADA_MINIMA_MENSAL NUMBER(3),
        JORNADA_MAXIMA_MENSAL NUMBER(3),
        QUANTIDADE_MAXIMA_ATIVIDADES NUMBER(2),
        JORNADA_DIARIA_MIN_ED_ESPECIAL NUMBER(2),
        JORNADA_SEM_MIN_ED_ESPECIAL NUMBER(2),
        JORNADA_MENSAL_MIN_ED_ESPECIAL NUMBER(3),
        JORNADA_MENSAL_MAX_ED_ESPECIAL NUMBER(3),
        HORARIO_INICIO NUMBER(2),
        HORARIO_TERMINO NUMBER(2),
        DIAS_MINIMO_PRORROGAR_GMC NUMBER(3)
        );