create table HABILIDADES_CONTRATO
(
	ID			NUMBER(19,0) NOT NULL,
	DESCRICAO		VARCHAR2(255 CHAR) NOT NULL,
	SITUACAO		NUMBER(1) NOT NULL,
	CRIADO_POR		VARCHAR2(255 CHAR) NOT NULL,
	DATA_CRIACAO		TIMESTAMP NOT NULL,
	MODIFICADO_POR		VARCHAR2(255 CHAR),
	DATA_ALTERACAO		TIMESTAMP,
	DELETADO		NUMBER(1) NOT NULL
);

ALTER TABLE HABILIDADES_CONTRATO ADD CONSTRAINT KRS_INDICE_10840 PRIMARY KEY ( ID );

INSERT INTO HABILIDADES_CONTRATO (ID, DESCRICAO, SITUACAO, CRIADO_POR, DATA_CRIACAO, DELETADO, MODIFICADO_POR, DATA_ALTERACAO)
VALUES (1, 'Comunicação', 1, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP, 0, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP);

INSERT INTO HABILIDADES_CONTRATO (ID, DESCRICAO, SITUACAO, CRIADO_POR, DATA_CRIACAO, DELETADO, MODIFICADO_POR, DATA_ALTERACAO)
VALUES (2, 'Resolução de problemas', 1, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP, 0, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP);

INSERT INTO HABILIDADES_CONTRATO (ID, DESCRICAO, SITUACAO, CRIADO_POR, DATA_CRIACAO, DELETADO, MODIFICADO_POR, DATA_ALTERACAO)
VALUES (3, 'Trabalho em equipe', 1, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP, 0, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP);

INSERT INTO HABILIDADES_CONTRATO (ID, DESCRICAO, SITUACAO, CRIADO_POR, DATA_CRIACAO, DELETADO, MODIFICADO_POR, DATA_ALTERACAO)
VALUES (4, 'Inteligência emocional', 1, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP, 0, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP);

INSERT INTO HABILIDADES_CONTRATO (ID, DESCRICAO, SITUACAO, CRIADO_POR, DATA_CRIACAO, DELETADO, MODIFICADO_POR, DATA_ALTERACAO)
VALUES (5, 'Negociação', 1, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP, 0, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP);

INSERT INTO HABILIDADES_CONTRATO (ID, DESCRICAO, SITUACAO, CRIADO_POR, DATA_CRIACAO, DELETADO, MODIFICADO_POR, DATA_ALTERACAO)
VALUES (6, 'Criatividade', 1, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP, 0, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP);

INSERT INTO HABILIDADES_CONTRATO (ID, DESCRICAO, SITUACAO, CRIADO_POR, DATA_CRIACAO, DELETADO, MODIFICADO_POR, DATA_ALTERACAO)
VALUES (7, 'Relacionamento interpessoal', 1, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP, 0, 'SCRIPT DE CRIAÇÃO', CURRENT_TIMESTAMP);
