BEGIN
    DBMS_OUTPUT.ENABLE;
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.REP_CURSOS MODIFY (DESCRICAO_CURSO VARCHAR2(150 CHAR) )';
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.REP_CURSOS MODIFY (DESCRICAO_ABREVIADA_CURSO VARCHAR2(60 CHAR) )';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignora todas as exceções and retorna pro block principal
        DBMS_OUTPUT.PUT_LINE('Problema ao executar: Ajuste REP_CURSOS');
        NULL;
END;
/

BEGIN
    DBMS_OUTPUT.ENABLE;
    EXECUTE IMMEDIATE 'INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES (''REP_ENDERECOS'',''GEO_POINT'',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT(''Longitude'', -180, 180, 0.005), MDSYS.SDO_DIM_ELEMENT(''Latitude'', -90, 90, 0.005)),''8307'')';
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.REP_ENDERECOS ADD GEO_POINT SDO_GEOMETRY';
    EXECUTE IMMEDIATE 'CREATE INDEX KRS_INDICE_06967 ON SERVICE_VAGAS_DEV.REP_ENDERECOS (GEO_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignora todas as exceções and retorna pro block principal
        DBMS_OUTPUT.PUT_LINE('Problema ao executar: Ajuste REP_ENDERECOS');
        NULL;
END;
/

BEGIN
    DBMS_OUTPUT.ENABLE;
    EXECUTE IMMEDIATE 'INSERT INTO USER_SDO_GEOM_METADATA (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) VALUES (''REP_ENDERECOS_ESTUDANTES'',''GEO_POINT'',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT(''Longitude'', -180, 180, 0.005), MDSYS.SDO_DIM_ELEMENT(''Latitude'', -90, 90, 0.005)),''8307'')';
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.REP_ENDERECOS_ESTUDANTES ADD GEO_POINT SDO_GEOMETRY';
    EXECUTE IMMEDIATE 'CREATE INDEX KRS_INDICE_06968 ON SERVICE_VAGAS_DEV.REP_ENDERECOS_ESTUDANTES (GEO_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignora todas as exceções and retorna pro block principal
        DBMS_OUTPUT.PUT_LINE('Problema ao executar: Ajuste REP_ENDERECOS_ESTUDANTES');
        NULL;
END;
/

BEGIN
    DBMS_OUTPUT.ENABLE;
    EXECUTE IMMEDIATE 'Insert into user_sdo_geom_metadata (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) values (''REP_ENDERECOS_ESCOLAS'',''GEO_POINT'',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT(''Longitude'', -180, 180, 0.005), MDSYS.SDO_DIM_ELEMENT(''Latitude'', -90, 90, 0.005)),''8307'')';
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.REP_ENDERECOS_ESCOLAS ADD GEO_POINT SDO_GEOMETRY';
    EXECUTE IMMEDIATE 'CREATE INDEX KRS_INDICE_06969 ON SERVICE_VAGAS_DEV.REP_ENDERECOS_ESCOLAS (GEO_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignora todas as exceções and retorna pro block principal
        DBMS_OUTPUT.PUT_LINE('Problema ao executar: Ajuste REP_ENDERECOS_ESCOLAS');
        NULL;
END;
/

BEGIN
    DBMS_OUTPUT.ENABLE;
    EXECUTE IMMEDIATE 'Insert into user_sdo_geom_metadata (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) values (''LOCAIS_CAPACITACAO'',''GEO_POINT'',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT(''Longitude'', -180, 180, 0.005), MDSYS.SDO_DIM_ELEMENT(''Latitude'', -90, 90, 0.005)),''8307'')';
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.LOCAIS_CAPACITACAO ADD GEO_POINT SDO_GEOMETRY';
    EXECUTE IMMEDIATE 'CREATE INDEX KRS_INDICE_06970 ON SERVICE_VAGAS_DEV.LOCAIS_CAPACITACAO (GEO_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignora todas as exceções and retorna pro block principal
        DBMS_OUTPUT.PUT_LINE('Problema ao executar: Ajuste LOCAIS_CAPACITACAO');
        NULL;
END;
/

BEGIN
    DBMS_OUTPUT.ENABLE;
    EXECUTE IMMEDIATE 'Insert into user_sdo_geom_metadata (TABLE_NAME,COLUMN_NAME,DIMINFO,SRID) values (''REP_ESCOLARIDADES_ESTUDANTES'',''GEO_POINT'',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT(''Longitude'', -180, 180, 0.005), MDSYS.SDO_DIM_ELEMENT(''Latitude'', -90, 90, 0.005)),''8307'')';
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.REP_ESCOLARIDADES_ESTUDANTES ADD GEO_POINT SDO_GEOMETRY';
    EXECUTE IMMEDIATE 'CREATE INDEX KRS_INDICE_06971 ON SERVICE_VAGAS_DEV.REP_ESCOLARIDADES_ESTUDANTES (GEO_POINT) INDEXTYPE IS MDSYS.SPATIAL_INDEX';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignora todas as exceções and retorna pro block principal
        DBMS_OUTPUT.PUT_LINE('Problema ao executar: Ajuste REP_ESCOLARIDADES_ESTUDANTES');
        NULL;
END;
/

BEGIN
    DBMS_OUTPUT.ENABLE;
    EXECUTE IMMEDIATE 'ALTER TABLE SERVICE_VAGAS_DEV.REP_ENDERECOS_ESTUDANTES MODIFY (NUMERO VARCHAR2(10 CHAR) )';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignora todas as exceções and retorna pro block principal
        DBMS_OUTPUT.PUT_LINE('Problema ao executar: Ajuste REP_ENDERECOS_ESTUDANTES');
        NULL;
END;
/

BEGIN
    DBMS_OUTPUT.ENABLE;
    EXECUTE IMMEDIATE 'CREATE TABLE BENEFICIOS_CONTR_EMP
   (	
    ID NUMBER(20,0) NOT NULL ENABLE, 
	ID_CONTR_EMP_EST NUMBER(20,0) NOT NULL ENABLE, 
	ID_BENEFICIO NUMBER(20,0) NOT NULL ENABLE, 
	VALOR NUMBER(10,2), 
	DELETADO NUMBER, 
	DATA_CRIACAO TIMESTAMP (6), 
	DATA_ALTERACAO TIMESTAMP (6), 
	CRIADO_POR VARCHAR2(255 BYTE), 
	MODIFICADO_POR VARCHAR2(255 BYTE), 
	 CONSTRAINT KRS_INDICE_01937 PRIMARY KEY (ID)
    )';
EXCEPTION
    WHEN OTHERS THEN
        -- Ignora todas as exceções and retorna pro block principal
        DBMS_OUTPUT.PUT_LINE('Problema ao executar: Ajuste BENEFICIOS_CONTR_EMP');
        NULL;
END;
/