CREATE TABLE DADOS_PAGAMENTOS_CONTRATOS_ESTUDANTES_EMPRESAS(
	ID               		NUMBER(20) NOT NULL,	
    CRIADO_POR       		VARCHAR2(255 CHAR),
	DATA_CRIACAO     		TIMESTAMP NOT NULL,
    DATA_ALTERACAO   		TIMESTAMP,   
    MODIFICADO_POR   		VARCHAR2(255 CHAR),
    DELETADO         		NUMBER(1) DEFAULT 0,	
	ID_BANCO				NUMBER(3),	
	ID_AGENCIA				NUMBER(4),	
	CONTA_CORRENTE			VARCHAR2(50 CHAR),
	CONTA_CORRENTE_DIGITO	VARCHAR2(2 CHAR),
	CODIGO_OPERACAO			VARCHAR2(5 CHAR),
	TIPO_CONTA				VARCHAR2(1 CHAR),
	SITUACAO				NUMBER(1,0) DEFAULT 1
);

CREATE SEQUENCE SEQ_DADOS_PAGAMENTOS_CONTRATOS_ESTUDANTES_EMPRESAS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;

ALTER TABLE DADOS_PAGAMENTOS_CONTRATOS_ESTUDANTES_EMPRESAS
    ADD CONSTRAINT "KRS_INDICE_07944" FOREIGN KEY ( ID_BANCO )
        REFERENCES BANCOS ( ID_BANCO );
        
ALTER TABLE DADOS_PAGAMENTOS_CONTRATOS_ESTUDANTES_EMPRESAS
    ADD CONSTRAINT "KRS_INDICE_07945" FOREIGN KEY ( ID_AGENCIA )
        REFERENCES AGENCIAS ( ID_AGENCIA );
        
ALTER TABLE DADOS_PAGAMENTOS_CONTRATOS_ESTUDANTES_EMPRESAS ADD CONSTRAINT "KRS_INDICE_07946" PRIMARY KEY ( id );
CREATE TABLE VINCULOS_DADOS_PAGAMENTOS_CONTRATOS_ESTUDANTES_EMPRESAS(	
	ID_DADOS_PAG_CONTR_EST_EMPR NUMBER(20) NOT NULL,
	ID_CONTR_EST_EMPR 			NUMBER(20) NOT NULL
);

ALTER TABLE VINCULOS_DADOS_PAGAMENTOS_CONTRATOS_ESTUDANTES_EMPRESAS
    ADD CONSTRAINT "KRS_INDICE_07947" FOREIGN KEY ( ID_CONTR_EST_EMPR )
        REFERENCES CONTRATOS_ESTUDANTES_EMPRESA ( ID );
        
ALTER TABLE VINCULOS_DADOS_PAGAMENTOS_CONTRATOS_ESTUDANTES_EMPRESAS
    ADD CONSTRAINT "KRS_INDICE_07948" FOREIGN KEY ( ID_DADOS_PAG_CONTR_EST_EMPR )
        REFERENCES DADOS_PAGAMENTOS_CONTRATOS_ESTUDANTES_EMPRESAS ( ID );