-- Ajusta tamanho descricao pergunta
ALTER TABLE PARAMS_PERGUNTAS_FORMULARIOS MODIFY DESCRICAO_PERGUNTA VARCHAR2(1000 char);

-- Ajusta tamanho descricao resposta
ALTER TABLE PARAMS_RESPOSTAS_FORMULARIOS MODIFY RESPOSTA_DESCRICAO VARCHAR2(1000 char);