DECLARE
tabela_existente int:=0;
BEGIN
  SELECT count(*) into tabela_existente FROM all_tables where table_name = 'REP_PESSOAS_TELEFONES_COMPANY'; 

  if tabela_existente<=0 then
     EXECUTE IMMEDIATE 'CREATE TABLE REP_PESSOAS_TELEFONES_COMPANY (ID_PESSOA NUMBER(19) not null, ID_TELEFONE NUMBER(19) not null)';
     EXECUTE IMMEDIATE 'ALTER TABLE REP_PESSOAS_TELEFONES_COMPANY ADD PRIMARY KEY (ID_PESSOA, ID_TELEFONE)';
     EXECUTE IMMEDIATE 'COMMENT ON TABLE REP_PESSOAS_TELEFONES_COMPANY  IS ''COMPANY_DEV:SERVICE_COMPANY_DEV:PESSOAS_TELEFONES:''';
  end if;
END;