

INSERT INTO QUALIFICACAO (ID, NOME, NIVEL, SITUACAO, DATA_CRIACAO, DATA_ALTERACAO, DELETADO, TIPO) VALUES (SEQ_QUALIFICACAO.nextval, 'Carteira OAB', 1, 1, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0);