INSERT INTO OCORRENCIAS ("ID",
                         "DESCRICAO",
                         "BLOQUEIA_VAGA",
                         "BLOQUEIA_CONTRATACAO",
                         "ATIVO",
                         "DELETADO",
                         "DATA_CRIACAO",
                         "DATA_ALTERACAO",
                         "CRIADO_POR",
                         "MODIFICADO_POR")
VALUES (54,
        'Vaga com pendência de agenda',
        1,
        1,
        0,
        0,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP,
        'FLYWAY',
        'FLYWAY');