BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        JOB_NAME => 'JOB_CLASSIFICACOES_ESTUDANTES',
        JOB_TYPE => 'PLSQL_BLOCK',
        JOB_ACTION => 'PROC_CLASSIFICACOES_ESTUDANTES_CONSUMIR_FILA;',
        START_DATE => SYSTIMESTAMP,
        ENABLED => TRUE,
        REPEAT_INTERVAL => 'FREQ=MINUTELY;INTERVAL=30',
        auto_drop => FALSE
    );
END;
/