ALTER TABLE REP_PARAMETROS_ESCOLARES MODIFY (DESC_PARAMETRO_ESCOLAR VARCHAR2(100 CHAR) );
ALTER TABLE REP_PARAMETROS_ESCOLARES MODIFY (DESC_PARAM_ESCOLAR_REDUZIDA VARCHAR2(35 CHAR) );
ALTER TABLE REP_PARAMETROS_ESCOLARES MODIFY (MENSAGEM VARCHAR2(100 CHAR) );
ALTER TABLE REP_PARAMETROS_ESCOLARES MODIFY (CRIADO_POR VARCHAR2(255 CHAR) );
ALTER TABLE REP_PARAMETROS_ESCOLARES MODIFY (MODIFICADO_POR VARCHAR2(255 CHAR) );