

ALTER TABLE acompanhamentos_gmc DROP (ID_UNIDADE_ORIGEM, ID_UNIDADE_LOCAL, ID_CARTEIRA_ORIGEM, ID_CARTEIRA_LOCAL);

ALTER TABLE acompanhamentos_gmc ADD ID_UNIDADE_ORIGEM_LOCAL NUMBER(20,0);

ALTER TABLE acompanhamentos_gmc ADD ID_CARTEIRA_ORIGEM_LOCAL NUMBER(20,0);