--PK-12795 Criar faixa de horario ao gerenciar / cadastrar local de capacitacao
--Service Vagas
CREATE TABLE LOCAIS_CAPACITACAO_HORARIO (ID_LOCAL_CAPACITACAO_HORARIO NUMBER(20) NOT NULL,
                                         ID_LOCAL_CAPACITACAO NUMBER(20) NOT NULL,
										 HORA_INICIO TIMESTAMP(6) NOT NULL,
										 HORA_FINAL TIMESTAMP(6) NOT NULL,
										 DATA_CRIACAO     TIMESTAMP NOT NULL,
										 DATA_ALTERACAO   TIMESTAMP NOT NULL,
										 CRIADO_POR       VARCHAR2(255 CHAR),
										 MODIFICADO_POR   VARCHAR2(255 CHAR),
										 DELETADO         NUMBER(1) DEFAULT 0
);
ALTER TABLE LOCAIS_CAPACITACAO_HORARIO  ADD CONSTRAINT KRS_INDICE_07260 PRIMARY KEY (ID_LOCAL_CAPACITACAO_HORARIO) ENABLE;
ALTER TABLE LOCAIS_CAPACITACAO_HORARIO  ADD CONSTRAINT KRS_INDICE_07261 FOREIGN KEY (ID_LOCAL_CAPACITACAO) REFERENCES SERVICE_VAGAS_DEV.LOCAIS_CAPACITACAO(ID) ENABLE;