DECLARE
    tabela_existente int:=0;
BEGIN
  SELECT count(*) into tabela_existente FROM all_tables where table_name = 'REP_CIEES_CARTEIRAS_TERRITORIOS_UNIT'; 
  if tabela_existente<=0 then
     EXECUTE IMMEDIATE 'CREATE TABLE SERVICE_VAGAS_DEV.REP_CIEES_CARTEIRAS_TERRITORIOS_UNIT 
(	
    ID NUMBER(20,0) NOT NULL ENABLE, 
    CODIGO_MUNICIPIO NUMBER(19,0) NOT NULL ENABLE, 
    CORRENTE NUMBER(1,0) NOT NULL ENABLE, 
    CEP VARCHAR2(8 CHAR) NOT NULL ENABLE, 
    ID_CIEE NUMBER(19,0) NOT NULL ENABLE, 
    ID_CARTEIRA NUMBER(19,0) NOT NULL ENABLE, 
    ID_CARTEIRA_LOCAL NUMBER(19,0) NOT NULL ENABLE, 
    ID_UNIDADE_CIEE NUMBER(20,0) NOT NULL ENABLE, 
    ID_UNIDADE_CIEE_LOCAL NUMBER(20,0) NOT NULL ENABLE, 
    CRIADO_POR VARCHAR2(255 CHAR) NOT NULL ENABLE, 
    DATA_CRIACAO TIMESTAMP (6) NOT NULL ENABLE, 
    DELETADO NUMBER(1,0) DEFAULT 0, 
    MODIFICADO_POR VARCHAR2(255 CHAR) NOT NULL ENABLE, 
    DATA_ALTERACAO TIMESTAMP (6) NOT NULL ENABLE, 
    CONSTRAINT KRS_INDICE_11324 PRIMARY KEY (ID)
)';
  end if;
END;

/

COMMENT ON TABLE "SERVICE_VAGAS_DEV"."REP_CIEES_CARTEIRAS_TERRITORIOS_UNIT"  IS 'UNIT_DEV:SERVICE_UNIT_DEV:CIEES_CARTEIRAS_TERRITORIOS:id';