CREATE TABLE REP_PROGRAMAS_SOCIAIS_CORE
(
    ID                           NUMBER(19,0) NOT NULL,
    CRIADO_POR                   VARCHAR2(255),
    DATA_CRIACAO                 TIMESTAMP(6) NOT NULL,
    DELETADO                     NUMBER(1,0) NOT NULL,
    MODIFICADO_POR               VARCHAR2(255),
    DATA_ALTERACAO               TIMESTAMP(6) NOT NULL,
    ATIVO                        NUMBER(1,0) NOT NULL,
    DESCRICAO                    VARCHAR2(300) NOT NULL,
    ID_MUNICIPIO                 NUMBER(19,0),
    ID_ABRANGENCIA               NUMBER(19,0) NOT NULL,
    ID_TIPO_INFORMACAO_SOCIAL    NUMBER(19,0) NOT NULL
);
ALTER TABLE REP_PROGRAMAS_SOCIAIS_CORE ADD CONSTRAINT KRS_INDICE_1010061 PRIMARY KEY (ID);
COMMENT ON TABLE REP_PROGRAMAS_SOCIAIS_CORE IS 'CORE_DEV:SERVICE_CORE_DEV:PROGRAMAS_SOCIAIS:id';