CREATE OR REPLACE TRIGGER TRIGGER_02_VAGAS_APRENDIZ_INSERT_UPDATE
    AFTER INSERT OR UPDATE ON VAGAS_APRENDIZ
    FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    BEGIN
        INSERT INTO FILA_TRIAGEM_VAGA_APRENDIZ (ID, ID_VAGA, DATA_CRIACAO) VALUES (SEQ_FILA_TRIAGEM_VAGA_APRENDIZ_01.NEXTVAL, :NEW.ID, SYSDATE);
        COMMIT;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
END;