
ALTER TABLE PARAMETROS_CONTRATOS_IE ADD ID_CORPO NUMBER(20);

ALTER TABLE PARAMETROS_CONTRATOS_IE ADD POSSUI_CORPO_PROPRIO NUMBER(1,0) DEFAULT 0;

COMMENT ON COLUMN PARAMETROS_CONTRATOS_IE.POSSUI_CORPO_PROPRIO 
     IS 'ENUM: 0-NAO 1-SIM';