-- PK-12405 - Implementar parâmetro ciee - Limite de dias para o cancelamento e reversão do cancelamento do contrato de estágio e aprendiz

ALTER TABLE REP_PARAMETROS_UNIDADES_CIEE ADD LIMITE_DIAS_CANCELAMENTO_CONTRATO_ESTAGIO NUMBER(3);
ALTER TABLE REP_PARAMETROS_UNIDADES_CIEE ADD LIMITE_DIAS_CANCELAMENTO_CONTRATO_APRENDIZ NUMBER(3);
ALTER TABLE REP_PARAMETROS_UNIDADES_CIEE ADD LIMITE_DIAS_REVERSAO_CANCELAMENTO_CONTRATO_ESTAGIO NUMBER(3);
ALTER TABLE REP_PARAMETROS_UNIDADES_CIEE ADD LIMITE_DIAS_REVERSAO_CANCELAMENTO_CONTRATO_APRENDIZ NUMBER(3);