-- DROP
ALTER TABLE VAGAS_APRENDIZ DROP COLUMN ID_SALA;
ALTER TABLE VAGAS_APRENDIZ DROP COLUMN ID_LOCAL_CAPACITACAO;
-- ADD
ALTER TABLE TURMAS ADD ID_SALA NUMBER(20);
ALTER TABLE TURMAS ADD ID_LOCAL_CAPACITACAO NUMBER(20);