CREATE TABLE "SERVICE_VAGAS_DEV"."DOCUMENTOS_CONTR_EMP_EST_ALTERADO" (
    "ID" NUMBER(20, 0) NOT NULL ENABLE,
    "ID_ORIGEM" NUMBER(20, 0) NOT NULL ENABLE,
    "ID_CONTR_EMP_EST" NUMBER(20, 0) NOT NULL ENABLE,
    "ID_DOCUMENTO" NUMBER(20, 0),
    "TIPO_DOCUMENTO" VARCHAR2(255)
);

ALTER TABLE
    DOCUMENTOS_CONTR_EMP_EST_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009942 PRIMARY KEY(ID);

ALTER TABLE
    DOCUMENTOS_CONTR_EMP_EST_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009943 FOREIGN KEY (ID_CONTR_EMP_EST) REFERENCES CONTRATO_ESTUDANTES_EMPRESAS_ALTERADO (ID);

CREATE SEQUENCE SEQ_DOCUMENTOS_CONTR_EMP_EST_ALTERADO MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

CREATE TABLE "SERVICE_VAGAS_DEV"."FERIAS_ALTERADO" (
    "ID" NUMBER(20, 0) NOT NULL ENABLE,
    "ID_ORIGEM" NUMBER(20, 0) NOT NULL ENABLE,
    "ID_CONTR_EMP_EST" NUMBER(20, 0) NOT NULL ENABLE,
    "TIPO_FERIAS" NUMBER(1, 0) NOT NULL ENABLE,
    "DELETADO" NUMBER,
    "DATA_CRIACAO" TIMESTAMP (6) NOT NULL ENABLE,
    "DATA_ALTERACAO" TIMESTAMP (6),
    "CRIADO_POR" VARCHAR2(255) NOT NULL ENABLE,
    "MODIFICADO_POR" VARCHAR2(255) NOT NULL ENABLE
);

ALTER TABLE
    FERIAS_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009944 PRIMARY KEY(ID);

ALTER TABLE
    FERIAS_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009945 FOREIGN KEY (ID_CONTR_EMP_EST) REFERENCES CONTRATO_ESTUDANTES_EMPRESAS_ALTERADO (ID);

CREATE SEQUENCE SEQ_FERIAS_ALTERADO MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

CREATE TABLE "SERVICE_VAGAS_DEV"."PERIODOS_ALTERADO" (
    "ID" NUMBER(20, 0) NOT NULL ENABLE,
    "ID_ORIGEM" NUMBER(20, 0) NOT NULL ENABLE,
    "ID_FERIAS" NUMBER(20, 0) NOT NULL ENABLE,
    "DATA_INICIO" TIMESTAMP (6) NOT NULL ENABLE,
    "DATA_FIM" TIMESTAMP (6) NOT NULL ENABLE,
    "DELETADO" NUMBER,
    "DATA_CRIACAO" TIMESTAMP (6) NOT NULL ENABLE,
    "DATA_ALTERACAO" TIMESTAMP (6),
    "CRIADO_POR" VARCHAR2(255) NOT NULL ENABLE,
    "MODIFICADO_POR" VARCHAR2(255)
);

ALTER TABLE
    PERIODOS_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009946 PRIMARY KEY(ID);

ALTER TABLE
    PERIODOS_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009947 FOREIGN KEY (ID_FERIAS) REFERENCES FERIAS_ALTERADO (ID);

CREATE SEQUENCE SEQ_PERIODOS_ALTERADO MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;

CREATE TABLE "SERVICE_VAGAS_DEV"."VINCULOS_CONTRATOS_ATIVIDADES_APRENDIZ_ALTERADO" (
    "ID_CONTRATO_CURSO_CAPACITACAO" NUMBER(20, 0) NOT NULL ENABLE,
    "ID_ATIVIDADE" NUMBER(20, 0) NOT NULL ENABLE,
    "ID_CBO" NUMBER(20, 0) NOT NULL ENABLE
);

ALTER TABLE
    VINCULOS_CONTRATOS_ATIVIDADES_APRENDIZ_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009948 FOREIGN KEY (ID_CONTRATO_CURSO_CAPACITACAO) REFERENCES CONTRATOS_CURSOS_CAPACITACAO_ALTERADO (ID);

ALTER TABLE
    VINCULOS_CONTRATOS_ATIVIDADES_APRENDIZ_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009949 FOREIGN KEY (ID_ATIVIDADE) REFERENCES ATIVIDADES_APRENDIZ (ID);

ALTER TABLE
    VINCULOS_CONTRATOS_ATIVIDADES_APRENDIZ_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009950 FOREIGN KEY (ID_CBO) REFERENCES CBOS (ID);