ALTER TABLE CLASSIFICACOES_ESTUDANTES_LOG DROP COLUMN ID_ESTUDANTE CASCADE CONSTRAINTS;

ALTER TABLE CLASSIFICACOES_ESTUDANTES_LOG ADD (IDS_ESTUDANTES IDS_TYP) 
	NESTED TABLE IDS_ESTUDANTES store as nested_tab return as value;

ALTER TABLE CLASSIFICACOES_ESTUDANTES_LOG MODIFY MENSAGEM VARCHAR2(4000 CHAR);

ALTER TABLE CLASSIFICACOES_ESTUDANTES_LOG MODIFY ID_CLASSIFICACOES_PARAMETROS_ITENS NUMBER(20) NULL;