create or replace view {{user}}.V_APRENDIZES_VINCULADOS as
SELECT VAGAS_APRENDIZ.id,
       VAGAS_APRENDIZ.id_local_contrato,
       VAGAS_APRENDIZ.codigo_da_vaga,
       VAGAS_APRENDIZ.DATA_CRIACAO,
       VAGAS_APRENDIZ.numero_vagas,
       SITUACOES.descricao     AS SITUACAO,
       SITUACOES.sigla         AS SIGLA_SITUACAO,
       SITUACOES.id            as ID_SITUACAO_VAGA,
       AREAS_ATUACAO_APRENDIZ.descricao_area_atuacao,
       COUNT(VINCULOS_VAGA.id) AS CANDIDATOS_VINCULADOS,
       VAGAS_APRENDIZ.PCD
FROM VAGAS_APRENDIZ
         JOIN SITUACOES ON VAGAS_APRENDIZ.ID_SITUACAO_VAGA = SITUACOES.id
         JOIN CURSOS_CAPACITACAO CC on VAGAS_APRENDIZ.ID_CURSO_CAPACITACAO = CC.ID
         JOIN AREAS_ATUACAO_APRENDIZ ON CC.ID_AREA_ATUACAO = AREAS_ATUACAO_APRENDIZ.id
         LEFT JOIN VINCULOS_VAGA on VAGAS_APRENDIZ.CODIGO_DA_VAGA = VINCULOS_VAGA.CODIGO_VAGA
GROUP BY VAGAS_APRENDIZ.id, VAGAS_APRENDIZ.id_local_contrato, VAGAS_APRENDIZ.codigo_da_vaga,
         VAGAS_APRENDIZ.DATA_CRIACAO, VAGAS_APRENDIZ.numero_vagas,
         SITUACOES.descricao, SITUACOES.sigla, SITUACOES.id,
         AREAS_ATUACAO_APRENDIZ.descricao_area_atuacao, VAGAS_APRENDIZ.PCD
;