INSERT INTO portarias_mte (ID, DESCRICAO_PORTARIA, SITUACAO_PORTARIA,
DELETADO, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR) VALUES (SEQ_PORTARIAS_MTE.nextval,
'Portaria nº 671/2021', 1, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'SCRIPT', 'SCRIPT');