DECLARE
    tabela_existente INT := 0;
BEGIN
    SELECT
        COUNT(*)
    INTO tabela_existente
    FROM
        all_tables
    WHERE
        table_name = 'DIARIO_DE_BORDO';

    IF tabela_existente <= 0 THEN
        EXECUTE IMMEDIATE '
							create table  DIARIO_DE_BORDO(
							ID                      NUMBER(20,0) NOT NULL,
							ID_CONTR_EMP_EST        NUMBER(20,0) NOT NULL,
							CPF        				VARCHAR2(11 BYTE) NOT NULL,
							TIPO_DO_DIARIO			VARCHAR2(250) NOT NULL,
							CAMPO_DESCRITIVO		CLOB NOT NULL,
							CAMPO_IMAGEM       		CLOB NULL,
							DATA_CRIACAO          	TIMESTAMP NOT NULL,
							DATA_ALTERACAO        	TIMESTAMP,
							CRIADO_POR            	VARCHAR2(255 BYTE),
							MODIFICADO_POR        	VARCHAR2(255 BYTE),
							DELETADO              	NUMBER(1)
							)';
        EXECUTE IMMEDIATE 'ALTER TABLE DIARIO_DE_BORDO ADD CONSTRAINT KRS_INDICE_12068 PRIMARY KEY(ID)';
        EXECUTE IMMEDIATE 'ALTER TABLE DIARIO_DE_BORDO ADD CONSTRAINT KRS_INDICE_12069 FOREIGN KEY(ID_CONTR_EMP_EST) REFERENCES CONTRATOS_ESTUDANTES_EMPRESA (ID)';
        EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_DIARIO_DE_BORDO MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
    END IF;

END;