DECLARE
    tabela_existente int:=0;
BEGIN
  SELECT count(*) into tabela_existente FROM all_tables where table_name = 'REP_CEPS_CORE'; 
  if tabela_existente<=0 then
     EXECUTE IMMEDIATE 'CREATE TABLE SERVICE_VAGAS_DEV.REP_CEPS_CORE 
(	
    CODIGO_CEP NUMBER(19,0) NOT NULL ENABLE, 
    CRIADO_POR VARCHAR2(255 CHAR), 
    DATA_CRIACAO TIMESTAMP (6) NOT NULL ENABLE, 
    DELETADO NUMBER(1,0) NOT NULL ENABLE, 
    MODIFICADO_POR VARCHAR2(255 CHAR), 
    DATA_ALTERACAO TIMESTAMP (6) NOT NULL ENABLE, 
    ENDERECO VARCHAR2(255 CHAR), 
    COMPLEMENTO_LOGRADOURO VARCHAR2(255 CHAR), 
    DESCRICAO_LOGRADOURO VARCHAR2(255 CHAR), 
    TIPO_LOGRADOURO VARCHAR2(255 CHAR), 
    COD_MUNICIPIO_IBGE NUMBER(19,0) NOT NULL ENABLE, 
    ULTIMA_ATUALIZACAO TIMESTAMP (6) NOT NULL ENABLE, 
    DESCRICAO_LOCALIDADE VARCHAR2(255 CHAR) NOT NULL ENABLE, 
    DESCRICAO_BAIRRO VARCHAR2(255 CHAR), 
    REGULAR NUMBER(1,0) NOT NULL ENABLE, 
    CODIGO_UNIDADE_FEDERATIVA VARCHAR2(255 CHAR) NOT NULL ENABLE, 
    TIPO NUMBER(19,0) NOT NULL ENABLE, 
    LATITUDE FLOAT(126), 
    LONGITUDE FLOAT(126), 
    GEO_POINT SDO_GEOMETRY, 
    CONSTRAINT KRS_INDICE_11325 PRIMARY KEY (CODIGO_CEP)
)';
  end if;
END;

/

COMMENT ON TABLE SERVICE_VAGAS_DEV.REP_CEPS_CORE IS 'CORE_DEV:SERVICE_CORE_DEV:CEPS:CODIGO_CEP';