UPDATE BENEFICIOS
SET DESCRICAO        = '13º Bolsa - Auxílio',
    UTILIZA_NA_FOLHA = 1
WHERE DESCRICAO = '13º Bolsa-auxílio ou Salário';

INSERT INTO BENEFICIOS
    (ID, DESCRICAO, TEM_VALOR_MONETARIO, UTILIZA_NA_CONTRATACAO, DELETADO, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR, MOSTRA_VALOR, UTILIZA_NA_FOLHA)
    VALUES (9999, 'Outros', 1, 0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'script-flyway', 'script-flyway', 0, 1);