-- Adicionando campos simples
alter table TRIAGENS_ESTUDANTES
ADD (
    POSSUI_VIDEO NUMBER(1) DEFAULT 0 NOT NULL,
    SITUACAO NUMBER(1),
    NOME VARCHAR2(255),
    CODIGO_ESTUDANTE VARCHAR2(20),
    CPF VARCHAR2(11),
    SITUACAO_ANALISE_PCD NUMBER(1),
    ID_RESPONSAVEL NUMBER(20, 0),
    NOME_MAE VARCHAR2(150 char),
    POSSUI_REDACAO NUMBER(1)
)
;

-- Atualizar UDTs de estudantes

ALTER TABLE TRIAGENS_ESTUDANTES ADD(ENDERECOS {{user}}.ENDERECOS_TYP)
NESTED TABLE ENDERECOS store as n_enderecos_estud
;

ALTER TABLE TRIAGENS_ESTUDANTES ADD(EMAILS {{user}}.EMAILS_TYP)
NESTED TABLE EMAILS store as n_emails_estud
;

ALTER TABLE TRIAGENS_ESTUDANTES ADD(TELEFONES {{user}}.TELEFONES_TYP)
NESTED TABLE TELEFONES store as n_telefones_estud
;

ALTER TABLE TRIAGENS_ESTUDANTES ADD(EXPERIENCIAS_PROFISSIONAIS {{user}}.EXPERIENCIAS_PROFISSIONAIS_TYP)
NESTED TABLE EXPERIENCIAS_PROFISSIONAIS store as n_experiencias_profissionais_estud
;

ALTER TABLE TRIAGENS_ESTUDANTES ADD(CONHECIMENTOS_DIVERSOS {{user}}.CONHECIMENTOS_DIVERSOS_TYP)
NESTED TABLE CONHECIMENTOS_DIVERSOS store as n_conhecimentos_diversos_estud
;

ALTER TABLE TRIAGENS_ESTUDANTES ADD(AREAS_PROFISSIONAL {{user}}.AREAS_PROFISSIONAL_TYP)
NESTED TABLE AREAS_PROFISSIONAL store as n_areas_profissional_estud
;

ALTER TABLE TRIAGENS_ESTUDANTES ADD(CONHECIMENTOS {{user}}.CONHECIMENTOS_TYP)
NESTED TABLE CONHECIMENTOS store as n_conhecimentos_estud
;

ALTER TABLE TRIAGENS_ESTUDANTES ADD(IDIOMAS {{user}}.IDIOMAS_TYP)
NESTED TABLE IDIOMAS store as n_idiomas_estud
;

ALTER TABLE TRIAGENS_ESTUDANTES ADD(PCDS {{user}}.PCDS_ESTUDANTE_TYP)
NESTED TABLE PCDS store as n_pcds_estud
;

-- Atualizar UDTs de vagas
alter table TRIAGENS_VAGAS add (PCDS {{user}}.PCDS_VAGA_TYP)
nested table PCDS store as n_pcds_vaga
;

alter table TRIAGENS_VAGAS add (IDIOMAS {{user}}.IDIOMAS_TYP)
nested table IDIOMAS store as n_idiomas_vagas
;

alter table TRIAGENS_VAGAS add (CONHECIMENTOS {{user}}.CONHECIMENTOS_TYP)
nested table CONHECIMENTOS store as n_conhecimentos_vagas
;