-- Remover FKs
-- ESTUDANTES_RECUSAS
ALTER TABLE SERVICE_VAGAS_DEV.ESTUDANTES_RECUSAS DROP CONSTRAINT KRS_INDICE_01522;
ALTER TABLE SERVICE_VAGAS_DEV.ESTUDANTES_RECUSAS DROP CONSTRAINT KRS_INDICE_01523;

-- ESTUDANTES_EMPRESA
ALTER TABLE SERVICE_VAGAS_DEV.ESTUDANTES_EMPRESA DROP CONSTRAINT KRS_INDICE_01514;
ALTER TABLE SERVICE_VAGAS_DEV.ESTUDANTES_EMPRESA DROP CONSTRAINT KRS_INDICE_01515;

-- TRIAGEM_CANDIDATOS_ANALITICO
ALTER TABLE SERVICE_VAGAS_DEV.TRIAGEM_CANDIDATOS_ANALITICO DROP CONSTRAINT KRS_INDICE_01525;
ALTER TABLE SERVICE_VAGAS_DEV.TRIAGEM_CANDIDATOS_ANALITICO DROP CONSTRAINT KRS_INDICE_01526;

-- Indice em CLASSIFICACOES_ESTUDANTES_ANALITICO
CREATE INDEX SERVICE_VAGAS_DEV.KRS_INDICE_10600 ON SERVICE_VAGAS_DEV.CLASSIFICACOES_ESTUDANTES_ANALITICO (ID_ESTUDANTE);
CREATE INDEX SERVICE_VAGAS_DEV.KRS_INDICE_10634 ON SERVICE_VAGAS_DEV.CLASSIFICACOES_ESTUDANTES_ANALITICO (ID_CLASSIFICACAO_PARAMETROS_ITEN);

-- Alteração de Paralelismo nas tabelas de Classificação
ALTER TABLE SERVICE_VAGAS_DEV.CLASSIFICACOES_ESTUDANTES_ANALITICO PARALLEL 6;
ALTER TABLE SERVICE_VAGAS_DEV.CLASSIFICACOES_ESTUDANTES_CONSOLIDADO PARALLEL 6;
ALTER TABLE SERVICE_VAGAS_DEV.CLASSIFICACOES_ESTUDANTES_LOG PARALLEL 6;
ALTER TABLE SERVICE_VAGAS_DEV.CLASSIFICACOES_PARAMETROS_ITENS PARALLEL 6;
ALTER TABLE SERVICE_VAGAS_DEV.CLASSIFICACOES_PARAMETROS_PONTOS PARALLEL 6;
ALTER TABLE SERVICE_VAGAS_DEV.CLASSIFICACOES_IES_ENAD PARALLEL 6;
ALTER TABLE SERVICE_VAGAS_DEV.CLASSIFICACOES_IES_IGC PARALLEL 6;