ALTER TABLE ESTUDANTES_AGENDA ADD (
    DATA_CONFIRMACAO TIMESTAMP NULL,
    TIPO_CONFIRMACAO NUMBER(1) NULL
);

COMMENT ON COLUMN ESTUDANTES_AGENDA.TIPO_CONFIRMACAO IS
'ENUM
0: CONFIRMADA
1: REAGENDADA
2: RECUSADA
';

ALTER TABLE RESULTADOS_PROCESSO_SELETIVO ADD JUSTIFICATIVA_ESTUDANTE VARCHAR2(500 CHAR) null;

ALTER TABLE PARAMETROS_COMUNICACAO ADD DIAS_CONFIRMACAO_AGENDA NUMBER(2) DEFAULT 3 NOT NULL;
