CREATE TABLE REP_CI_FIXOS_FAIXAS_COMPANY (
    ID              NUMBER(20) NOT NULL,
    DATA_CRIACAO    TIMESTAMP,
    DATA_ALTERACAO  TIMESTAMP,
    CRIADO_POR      VARCHAR2(255 CHAR),
    MODIFICADO_POR  VARCHAR2(255 CHAR),
    DELETADO        NUMBER(1),
    VALOR_COBRADO   NUMBER(10, 2),
    VALOR_MIN       NUMBER(10),
    VALOR_MAX       NUMBER(10),
    ID_CONTRATO     NUMBER
);
COMMENT ON TABLE REP_CI_FIXOS_FAIXAS_COMPANY IS
    'COMPANY_DEV:SERVICE_COMPANY_DEV:CI_FIXOS_FAIXAS:ID';
ALTER TABLE REP_CI_FIXOS_FAIXAS_COMPANY ADD CONSTRAINT KRS_INDICE_07982 PRIMARY KEY ( ID );

ALTER TABLE REP_CI_FIXOS_FAIXAS_COMPANY
    ADD CONSTRAINT KRS_INDICE_08000 FOREIGN KEY ( ID_CONTRATO )
        REFERENCES REP_CONTRATOS ( ID );

CREATE TABLE REP_DADOS_CONTRIBUICAO_COMPANY (
    ID                    NUMBER NOT NULL,
    ID_TIPO_CONTRIBUICAO  NUMBER,
    ID_CONTRATO           NUMBER,
    VALOR_CONTRIBUICAO    NUMBER(7, 2),
    ID_MES_BASE           NUMBER,
    DATA_CRIACAO          TIMESTAMP,
    DATA_ALTERACAO        TIMESTAMP,
    CRIADO_POR            VARCHAR2(255 CHAR),
    MODIFICADO_POR        VARCHAR2(255 CHAR),
    DELETADO              NUMBER(1),
    CONTRIBUICAO_INICIAL  NUMBER(5, 2),
    ID_INDICE             NUMBER
);
COMMENT ON TABLE REP_DADOS_CONTRIBUICAO_COMPANY IS
    'COMPANY_DEV:SERVICE_COMPANY_DEV:DADOS_CONTRIBUICAO:ID';
ALTER TABLE REP_DADOS_CONTRIBUICAO_COMPANY ADD CONSTRAINT KRS_INDICE_07981 PRIMARY KEY ( ID );
        
ALTER TABLE REP_DADOS_CONTRIBUICAO_COMPANY
    ADD CONSTRAINT KRS_INDICE_08001 FOREIGN KEY ( ID_CONTRATO )
        REFERENCES REP_CONTRATOS ( ID );