
ALTER TABLE parametros_empresa_contrato MODIFY MSG_ADICIONAL_BACKOFFICE VARCHAR2(3000 CHAR);

ALTER TABLE parametros_empresa_contrato MODIFY MSG_ADICIONAL_EMPRESA VARCHAR2(3000 CHAR);

ALTER TABLE parametros_empresa_contrato MODIFY MSG_ADICIONAL_ESTUDANTE VARCHAR2(3000 CHAR);

ALTER TABLE parametros_empresa_contrato MODIFY MSG_BACKOFFICE VARCHAR2(3000 CHAR);

ALTER TABLE parametros_empresa_contrato MODIFY MSG_EMPRESA VARCHAR2(3000 CHAR);

ALTER TABLE parametros_empresa_contrato MODIFY MSG_ESTUDANTE VARCHAR2(3000 CHAR);

