INSERT INTO QUALIFICACAO
(ID, NOME, NIVEL, SITUACAO, NUMERO_QUESTOES, NOTA_MINIMA, NOTA_MAXIMA, CRIADO_POR, DATA_CRIACAO, DATA_ALTERACAO, MODIFICADO_POR, DELETADO, TIPO)
SELECT SEQ_QUALIFICACAO.nextval,'EDUCAFRO', null, 1, null, null, null, 'PK-21144' ,current_timestamp, current_timestamp, 'PK-21144', 0, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM QUALIFICACAO WHERE NOME = 'EDUCAFRO' AND TIPO = 0);