ALTER TABLE VAGAS_ESTAGIO MODIFY CONTRAPARTIDA_AUX_TRANSPORTE VARCHAR2(200 CHAR);
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA MODIFY CONTRAPARTIDA_AUX_TRANSPORTE VARCHAR2(200 CHAR);
ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA MODIFY CONTRAPARTIDA_AUX_TRANSPORTE VARCHAR2(200 CHAR);
ALTER TABLE CONTRATO_ESTUDANTES_EMPRESAS_ALTERADO MODIFY CONTRAPARTIDA_AUX_TRANSPORTE VARCHAR2(200 CHAR);
ALTER TABLE HIST_CONTRATOS_ESTUDANTES_EMPRESA MODIFY CONTRAPARTIDA_AUX_TRANSPORTE VARCHAR2(200 CHAR);
