DECLARE
tabela_existente int:=0;
BEGIN
  SELECT count(*) into tabela_existente FROM all_tables where table_name = 'REP_REGISTROS_BLOQUEADOS_CORE'; 

  if tabela_existente<=0 then
     EXECUTE IMMEDIATE 'CREATE TABLE REP_REGISTROS_BLOQUEADOS_CORE (
		ID					NUMBER(20,0)     NOT NULL,        
		TEXTO				VARCHAR2(1000 CHAR) NOT NULL,
		TIPO            	NUMBER(1) DEFAULT 0, 
		CRIADO_POR		    VARCHAR2(255 CHAR) NOT NULL,
		DATA_CRIACAO		TIMESTAMP NOT NULL,
		MODIFICADO_POR		VARCHAR2(255 CHAR) NOT NULL,
		DATA_ALTERACAO		TIMESTAMP NOT NULL,
		DELETADO		    NUMBER(1) NOT NULL)';
     	EXECUTE IMMEDIATE 'ALTER TABLE REP_REGISTROS_BLOQUEADOS_CORE ADD CONSTRAINT KRS_INDICE_12268 PRIMARY KEY ( ID )';
        EXECUTE IMMEDIATE 'COMMENT ON COLUMN REP_REGISTROS_BLOQUEADOS_CORE.TIPO IS ''Enum: 0-TELEFONE; 1-EMAIL;''';       
  end if;
END;
/
COMMENT ON TABLE SERVICE_VAGAS_DEV.REP_REGISTROS_BLOQUEADOS_CORE  IS 'CORE_DEV:SERVICE_CORE_DEV:REGISTROS_BLOQUEADOS:id';