ALTER TABLE
    CONTRATO_ESTUDANTES_EMPRESAS_ALTERADO
ADD
    ID_ORIGEM number(20);

ALTER TABLE
    CONTRATO_ESTUDANTES_EMPRESAS_ALTERADO
ADD
    CONSTRAINT KRS_INDICE_1009961 FOREIGN KEY (ID_ORIGEM) REFERENCES CONTRATOS_ESTUDANTES_EMPRESA (ID);


