
UPDATE BENEFICIOS 
SET DESCRICAO = 'Vale alimentação', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'VALE ALIMENTACAO';

UPDATE BENEFICIOS 
SET DESCRICAO = 'Seguro de vida (aprendiz)', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'SEGURO DE VIDA (APRENDIZ)';

UPDATE BENEFICIOS
SET DESCRICAO = 'Ajuda de custo', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO =  'AJUDA DE CUSTO';

UPDATE BENEFICIOS
SET DESCRICAO = 'Ajuda de custo escolar', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'AJUDA DE CUSTO ESCOLAR';

UPDATE BENEFICIOS
SET DESCRICAO = 'Vale transporte', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'VALE TRANSPORTE';

UPDATE BENEFICIOS
SET DESCRICAO = 'Restaurante no local', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'RESTAURANTE NO LOCAL';

UPDATE BENEFICIOS
SET DESCRICAO = 'Vale combustível', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'VALE COMBUSTIVEL';

UPDATE BENEFICIOS
SET DESCRICAO = 'Assistência médica', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'ASSISTENCIA MEDICA';

UPDATE BENEFICIOS
SET DESCRICAO = 'Vale refeição',  DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'VALE REFEICAO';

UPDATE BENEFICIOS
SET DESCRICAO = 'Cesta básica', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'CESTA BASICA';

UPDATE BENEFICIOS
SET DESCRICAO = 'Ambulatório médico', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'AMBULATORIO MEDICO';

UPDATE BENEFICIOS
SET DESCRICAO = 'Convênio com farmácia', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'CONVENIO COM FARMACIA';

UPDATE BENEFICIOS
SET DESCRICAO = 'Férias', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'FERIAS';

UPDATE BENEFICIOS
SET DESCRICAO = 'Refeitório no local',  DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'REFEITORIO NO LOCAL';

UPDATE BENEFICIOS
SET DESCRICAO = 'Assistência odontológica',DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'ASSISTENCIA ODONTOLOGICA';

UPDATE BENEFICIOS
SET DESCRICAO = 'Possibilidade prorrogação', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'POSSIBILIDADE PRORROGACAO';

UPDATE BENEFICIOS
SET DESCRICAO = 'Possibilidade efetivação', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'POSSIBILIDADE EFETIVACAO';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio transporte mensal', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'AUXILIO TRANSPORTE MENSAL';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio transporte %', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'AUXILIO TRANSPORTE %';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio transporte por dia', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'AUXILIO TRANSPORTE POR DIA';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio alimentação mensal', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'AUXILIO ALIMENTACAO MENSAL';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio alimentação diario', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'AUXILIO ALIMENTACAO DIARIO';

UPDATE BENEFICIOS
SET DESCRICAO = 'Passe livre (metrô)', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'PASSE LIVRE (METRO)';

UPDATE BENEFICIOS
SET DESCRICAO = 'Curso de inglês', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'CURSO DE INGLES';

UPDATE BENEFICIOS
SET DESCRICAO = 'Ônibus da empresa', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'ONIBUS DA EMPRESA';

UPDATE BENEFICIOS
SET DESCRICAO = 'Reembolso de combustível', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'REEMBOLSO DE COMBUSTIVEL';

UPDATE BENEFICIOS
SET DESCRICAO = 'Ajuda de custo escolar', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'AJUDA DE CUSTO ESCOLAR';

UPDATE BENEFICIOS
SET DESCRICAO = 'Lanche na empresa', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'LANCHE NA EMPRESA';

UPDATE BENEFICIOS
SET DESCRICAO = 'Vale alimentação', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Vale alimentacao';

UPDATE BENEFICIOS
SET DESCRICAO = 'Vale combustível', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Vale Combustível';

UPDATE BENEFICIOS
SET DESCRICAO = 'Assistência médica', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Assistência medica';

UPDATE BENEFICIOS
SET DESCRICAO = 'Vale refeição', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Vale refeicao';

UPDATE BENEFICIOS
SET DESCRICAO = 'Cesta básica', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Cesta basica';

UPDATE BENEFICIOS
SET DESCRICAO = 'Ambulatório médico', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Ambulatorio medico';

UPDATE BENEFICIOS
SET DESCRICAO = 'Convênio com farmácia', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Convenio com farmacia';

UPDATE BENEFICIOS
SET DESCRICAO = 'Férias', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Ferias';

UPDATE BENEFICIOS
SET DESCRICAO = 'Refeitório no local', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Refeitorio no local';

UPDATE BENEFICIOS
SET DESCRICAO = 'Assistência odontológica', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Assistencia odontologica';

UPDATE BENEFICIOS
SET DESCRICAO = 'Possibilidade prorrogação', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Possibilidade prorrogacao';

UPDATE BENEFICIOS
SET DESCRICAO = 'Possibilidade efetivação', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Possibilidade efetivacao';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio transporte mensal', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Auxilio transporte mensal';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio transporte', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Auxilio transporte';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio transporte por dia', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Auxilio transporte por dia';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio alimentação mensal', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Auxilio alimentacao mensal';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio alimentação diario', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Auxilio alimentacao diario';

UPDATE BENEFICIOS
SET DESCRICAO = 'Passe livre (metrô)', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Passe livre (metro)';

UPDATE BENEFICIOS
SET DESCRICAO = 'Curso de inglês', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Curso de ingles';

UPDATE BENEFICIOS
SET DESCRICAO = 'Auxílio transporte', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Auxilio transporte';

UPDATE BENEFICIOS
SET DESCRICAO = 'Ônibus da empresa', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Onibus da empresa';

UPDATE BENEFICIOS
SET DESCRICAO = 'Reembolso de combustível', DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Reembolso de combustivel';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Ajuda de custo escolar';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Ambulatório médico';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Auxílio transporte %';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Cesta básica';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Convênio com farmácia'; 

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Curso de inglês';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Lanche na empresa';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Ônibus da empresa';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Auxílio transporte por dia';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Auxílio transporte mensal';

UPDATE BENEFICIOS
SET DELETADO = 1, DATA_ALTERACAO = sysdate, MODIFICADO_POR = 'PK-19039' WHERE DESCRICAO = 'Reembolso de combustível';
