CREATE OR REPLACE VIEW V_SITUACAO_VAGAS_NOVAS AS
SELECT DISTINCT
    E.ID_VAGA,
    (SELECT
         COUNT(viv.id)
     FROM
         vinculos_vaga viv
     WHERE
             viv.codigo_vaga = E.ID_VAGA
       AND viv.deletado = 0) AS NUMERO_ENCAMINHADOS
FROM
    ETAPAS_PERIODOS EP
        INNER JOIN ETAPAS_PROCESSO_SELETIVO E ON EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
WHERE
    ( EP.DATA_INICIO = SYSDATE + 1 OR EP.DATA_INICIO < SYSDATE )
ORDER BY E.ID_VAGA;