ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA ADD INTEGRACAO_TOTVS NUMBER(1) DEFAULT 0;

COMMENT ON COLUMN CONTRATOS_ESTUDANTES_EMPRESA.INTEGRACAO_TOTVS IS
'Flag 0 ou 1
0 - Contrato estudante empresa não integrado
1 - Contrato estudante empresa integrado';