-- Tabela de relatorios ESOCIAL
CREATE TABLE RELATORIOS_ESOCIAL (
    ID NUMBER(20) NOT NULL ENABLE,
    NOME_RELATORIO  VARCHAR2(255 CHAR) NOT NULL,
	COMPETENCIA DATE NOT NULL,
	ID_CONTRATO NUMBER(20) NOT NULL,
    DELETADO NUMBER DEFAULT 0,
    DATA_CRIACAO TIMESTAMP (6) NOT NULL ENABLE,
    DATA_ALTERACAO TIMESTAMP (6) NOT NULL ENABLE,
    CRIADO_POR VARCHAR2(255 CHAR),
    MODIFICADO_POR VARCHAR2(255 CHAR)
);
ALTER TABLE RELATORIOS_ESOCIAL ADD CONSTRAINT KRS_INDICE_10000 PRIMARY KEY (ID);
ALTER TABLE RELATORIOS_ESOCIAL ADD CONSTRAINT KRS_INDICE_10001 FOREIGN KEY (ID_CONTRATO) REFERENCES REP_CONTRATOS (ID) ENABLE;
CREATE SEQUENCE SEQ_RELATORIOS_ESOCIAL MINVALUE 1 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE;