--PK-14686 - Integrar ICN com Kairos - integrar supervisor de estágio ao Kairos
CREATE TABLE LOGS_INTEGRACOES_SUPERVISORES_ESTAGIOS_KAIROS
(
    ID                               NUMBER(20) NOT NULL,
    CIEE_RESPONSAVEL                 NUMBER(1),
    UF_CONTRATO_ESTAGIO_AUTONOMO     VARCHAR(2 CHAR),
    NUMERO_CONTRATO_ESTAGIO_AUTONOMO NUMBER(20),
    NOME_SUPERVISOR                  VARCHAR(255 CHAR),
    CARGO_SUPERVISOR                 VARCHAR(255 CHAR),
    DATA_PROCESSADO                  TIMESTAMP,
    CODIGO_CONTRATO_EMPRESA          NUMBER(20),
    SITUACAO                         VARCHAR(255 CHAR),
    ERRO                             CLOB,
    DATA_CRIACAO                     TIMESTAMP  NOT NULL,
    DATA_ALTERACAO                   TIMESTAMP  NOT NULL,
    CRIADO_POR                       VARCHAR2(255 CHAR),
    MODIFICADO_POR                   VARCHAR2(255 CHAR),
    DELETADO                         NUMBER(1) DEFAULT 0
);
ALTER TABLE LOGS_INTEGRACOES_SUPERVISORES_ESTAGIOS_KAIROS
    ADD CONSTRAINT KRS_INDICE_08045 PRIMARY KEY (ID);
COMMENT ON COLUMN LOGS_INTEGRACOES_SUPERVISORES_ESTAGIOS_KAIROS.CIEE_RESPONSAVEL IS
    'ENUM:
0-SP
1-RJ';
CREATE SEQUENCE SEQ_LOGS_INTEGRACOES_SUPERVISORES_ESTAGIOS_KAIROS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--
CREATE TABLE CONTROLES_INTEGRACOES_SUPERVISORES_ESTAGIOS_KAIROS
(
    ID             NUMBER(20) NOT NULL,
    CHAVE_ICN      VARCHAR(20 CHAR),
    UF_ICN         VARCHAR(2 CHAR),
    DATA_CRIACAO   TIMESTAMP  NOT NULL,
    DATA_ALTERACAO TIMESTAMP  NOT NULL,
    CRIADO_POR     VARCHAR2(255 CHAR),
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DELETADO       NUMBER(1) DEFAULT 0
);
ALTER TABLE CONTROLES_INTEGRACOES_SUPERVISORES_ESTAGIOS_KAIROS
    ADD CONSTRAINT KRS_INDICE_08060 PRIMARY KEY (ID);
CREATE SEQUENCE SEQ_CONTROLES_INTEGRACOES_SUPERVISORES_ESTAGIOS_KAIROS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;