DELETE FROM BENEFICIOS_RH WHERE 1=1;

INSERT INTO BENEFICIOS_RH VALUES(SEQ_BENEFICIOS_RH.nextval, 'Vale transporte', CURRENT_DATE, CURRENT_DATE, 'flyway', 'flyway', 0);
INSERT INTO BENEFICIOS_RH VALUES(SEQ_BENEFICIOS_RH.nextval, 'Vale refeição', CURRENT_DATE, CURRENT_DATE, 'flyway', 'flyway', 0);
INSERT INTO BENEFICIOS_RH VALUES(SEQ_BENEFICIOS_RH.nextval, 'Vale alimentação', CURRENT_DATE, CURRENT_DATE, 'flyway', 'flyway', 0);
INSERT INTO BENEFICIOS_RH VALUES(SEQ_BENEFICIOS_RH.nextval, 'Cesta básica', CURRENT_DATE, CURRENT_DATE, 'flyway', 'flyway', 0);
INSERT INTO BENEFICIOS_RH VALUES(SEQ_BENEFICIOS_RH.nextval, '2ª Via de crachá', CURRENT_DATE, CURRENT_DATE, 'flyway', '', 0);
