
-- Cria réplica de REP_DADOS_COMPLEMENTARES_COMPANY
CREATE TABLE REP_DADOS_COMPLEMENTARES_COMPANY
(
    ID                           NUMBER(19,0) NOT NULL,
    MULTI_EMPRESA                NUMBER(1,0) NOT NULL,
    CRIADO_POR                   VARCHAR2(255),
    DATA_CRIACAO                 TIMESTAMP(6) NOT NULL,
    DELETADO                     NUMBER(1,0),
    MODIFICADO_POR               VARCHAR2(255),
    DATA_ALTERACAO               TIMESTAMP(6) NOT NULL
);
ALTER TABLE REP_DADOS_COMPLEMENTARES_COMPANY ADD CONSTRAINT KRS_INDICE_10275 PRIMARY KEY (ID) ENABLE;

-- Cria réplica de REP_TIPO_MULTIEMPRESA_COMPANY
CREATE TABLE REP_TIPO_MULTIEMPRESA_COMPANY
(
    ID                           NUMBER(19,0) NOT NULL,
    DESCRICAO  	                 VARCHAR2(255),
    CRIADO_POR                   VARCHAR2(255),
    DATA_CRIACAO                 TIMESTAMP(6) NOT NULL,
    DELETADO                     NUMBER(1,0) NOT NULL,
    MODIFICADO_POR               VARCHAR2(255),
    DATA_ALTERACAO               TIMESTAMP(6) NOT NULL
);
ALTER TABLE REP_TIPO_MULTIEMPRESA_COMPANY ADD CONSTRAINT KRS_INDICE_10276 PRIMARY KEY (ID) ENABLE;

-- Inclui coluna ID_TIPO_MULTIEMPRESA na REP_INFO_CONTRATOS_EMPRESAS
ALTER TABLE REP_INFO_CONTRATO_EMPRESAS ADD ID_TIPO_MULTIEMPRESA NUMBER(19,0);

-- Inclui coluna ID_DADOS_COMPLEMENTARES na REP_CONTRATOS
ALTER TABLE REP_CONTRATOS ADD ID_DADOS_COMPLEMENTARES NUMBER(19,0);