ALTER TABLE VAGA_APRENDIZ_RESERVA ADD DELETADO NUMBER(1);
ALTER TABLE VAGA_APRENDIZ_RESERVA ADD DATA_CRIACAO TIMESTAMP NOT NULL;
ALTER TABLE VAGA_APRENDIZ_RESERVA ADD DATA_ALTERACAO TIMESTAMP NOT NULL;
ALTER TABLE VAGA_APRENDIZ_RESERVA ADD CRIADO_POR VARCHAR2(255);
ALTER TABLE VAGA_APRENDIZ_RESERVA ADD MODIFICADO_POR VARCHAR2(255);