--PK-14684 - Manter registros padroes ICN
CREATE TABLE PARAMETROS_ICN (
    ID              NUMBER(20) NOT NULL,
    ID_PADRAO       NUMBER(20),
    DESCRICAO       VARCHAR2(255 CHAR),
    DATA_CRIACAO    TIMESTAMP NOT NULL,
    DATA_ALTERACAO  TIMESTAMP NOT NULL,
    CRIADO_POR      VARCHAR2(255 CHAR),
    MODIFICADO_POR  VARCHAR2(255 CHAR),
    DELETADO        NUMBER(1) DEFAULT 0
);
ALTER TABLE PARAMETROS_ICN ADD CONSTRAINT KRS_INDICE_08028 PRIMARY KEY ( ID );
CREATE SEQUENCE SEQ_PARAMETROS_ICN MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
