ALTER TABLE QUALIFICACAO ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE QUALIFICACOES_ASSUNTOS ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE QUALIFICACOES_ESTUDANTE ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE FORMULARIOS_ESTUDANTES ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE RESPOSTAS_FORMS_ESTUDANTES ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE PARAMETROS_IE ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE VINCULO_TCE_ATIVIDADE_EMPRESAS ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE ATIVIDADES_CONTR_EMP_EST ADD ID_LEGADO VARCHAR2(200 CHAR);