-- Adiciona coluna id_legado para tabelas de migração via ETL
ALTER TABLE BENEFICIOS ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE AREAS_ATUACAO_APRENDIZ ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE DURACOES_CAPACITACAO ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE LOCAIS_CAPACITACAO ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE SALAS_CAPACITACAO ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE CURSOS_CAPACITACAO ADD ID_LEGADO VARCHAR2(200 CHAR);
ALTER TABLE CURSOS_MTE ADD ID_LEGADO VARCHAR2(200 CHAR);