INSERT INTO motivos_cancelamento_vaga
(ID,DESCRICAO,ORIGEM,ATIVO,
 DELETADO,DATA_CRIACAO,DATA_ALTERACAO,CRIADO_POR,MODIFICADO_POR)
VALUES
(6,'INICIATIVA DO CIEE',0,1,
 0,SYSDATE,SYSDATE,'Migration','Migration');