--PK-14689 - Integrar ICN com Kairos - integrar contratos ao Kairos

alter table LOGS_INTEGRACOES_CONTRATOS_KAIROS modify HORARIO_ESTAGIO VARCHAR2(255 char);

alter table LOGS_INTEGRACOES_CONTRATOS_KAIROS modify ATIVIDADE_ESTAGIO VARCHAR2(1000 char);

alter table LOGS_INTEGRACOES_CONTRATOS_KAIROS modify DV_AGENCIA_PAGAMENTO VARCHAR2(2 char);

alter table LOGS_INTEGRACOES_CONTRATOS_KAIROS modify DV_CONTA_PAGAMENTO VARCHAR(2 char);
