--PK-11285 - Integrar sistema com ICN para atualizar CSE
CREATE TABLE CONTROLES_ICN_ATUALIZACOES_CSE (
    ID NUMBER(20) NOT NULL,
    CHAVE_ICN VARCHAR(20 CHAR),
    UF_ICN VARCHAR(2 CHAR),
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    CRIADO_POR VARCHAR2(255 CHAR),
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DELETADO NUMBER(1) DEFAULT 0
);
ALTER TABLE CONTROLES_ICN_ATUALIZACOES_CSE ADD CONSTRAINT KRS_INDICE_08080 PRIMARY KEY ( ID );
CREATE SEQUENCE SEQ_CONTROLES_ICN_ATUALIZACOES_CSE MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;