CREATE TABLE HIST_VINCULOS_CONTRATOS_ATIVIDADES_APRENDIZ (
    ID_CONTRATO_CURSO_CAPACITACAO   NUMBER NOT NULL,
    ID_ATIVIDADE                    NUMBER NOT NULL,
    ID_CBO                          NUMBER NOT NULL
);
ALTER TABLE HIST_VINCULOS_CONTRATOS_ATIVIDADES_APRENDIZ
    ADD CONSTRAINT KRS_INDICE_08280 FOREIGN KEY ( ID_CONTRATO_CURSO_CAPACITACAO )
        REFERENCES HIST_CONTRATOS_CURSOS_CAPACITACAO ( ID );

ALTER TABLE HIST_VINCULOS_CONTRATOS_ATIVIDADES_APRENDIZ
    ADD CONSTRAINT KRS_INDICE_08281 FOREIGN KEY ( ID_ATIVIDADE )
        REFERENCES ATIVIDADES_APRENDIZ ( ID );

ALTER TABLE HIST_VINCULOS_CONTRATOS_ATIVIDADES_APRENDIZ
    ADD CONSTRAINT KRS_INDICE_08282 FOREIGN KEY ( ID_CBO )
        REFERENCES CBOS ( ID );
