ALTER TABLE AGENCIAS ADD DIGITO_AGENCIA_TMP VARCHAR2(1);
UPDATE AGENCIAS SET DIGITO_AGENCIA_TMP = DIGITO_AGENCIA WHERE DIGITO_AGENCIA IS NOT NULL;
UPDATE AGENCIAS SET DIGITO_AGENCIA = NULL WHERE DIGITO_AGENCIA IS NOT NULL;
ALTER TABLE AGENCIAS MODIFY DIGITO_AGENCIA VARCHAR2(1);
UPDATE AGENCIAS SET DIGITO_AGENCIA = DIGITO_AGENCIA_TMP WHERE DIGITO_AGENCIA IS NULL;
ALTER TABLE AGENCIAS DROP COLUMN DIGITO_AGENCIA_TMP;