DECLARE
tabela_existente int:=0;
BEGIN
  SELECT count(*) into tabela_existente FROM all_tables where table_name = 'FORMULARIOS_BLOCOS'; 

  if tabela_existente<=0 then
     EXECUTE IMMEDIATE 'CREATE TABLE FORMULARIOS_BLOCOS (
		ID				NUMBER(20,0)     NOT NULL,
		DESCRICAO			VARCHAR2(255 CHAR) NOT NULL,
		SITUACAO			NUMBER(1) DEFAULT 1 NOT NULL ,
		CRIADO_POR		    	VARCHAR2(255 CHAR) NOT NULL,
		DATA_CRIACAO		TIMESTAMP NOT NULL,
		MODIFICADO_POR		VARCHAR2(255 CHAR) NOT NULL,
		DATA_ALTERACAO		TIMESTAMP NOT NULL,
		DELETADO		    	NUMBER(1) NOT NULL)';
     	EXECUTE IMMEDIATE 'ALTER TABLE FORMULARIOS_BLOCOS ADD CONSTRAINT KRS_INDICE_12030 PRIMARY KEY ( ID )';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_FORMULARIOS_BLOCOS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
  end if;
END;
/


DECLARE
tabela_existente int:=0;
BEGIN
  SELECT count(*) into tabela_existente FROM all_tables where table_name = 'FORMULARIOS_COMPETENCIAS'; 

  if tabela_existente<=0 then
     	EXECUTE IMMEDIATE 'CREATE TABLE FORMULARIOS_COMPETENCIAS (
		ID				NUMBER(20,0)     NOT NULL,
		DESCRICAO			VARCHAR2(255 CHAR) NOT NULL,
		SITUACAO			NUMBER(1) DEFAULT 1 NOT NULL ,
		ID_FORMULARIOS_BLOCO	NUMBER(20,0)     NOT NULL,
		CRIADO_POR		    	VARCHAR2(255 CHAR) NOT NULL,
		DATA_CRIACAO		TIMESTAMP NOT NULL,
		MODIFICADO_POR		VARCHAR2(255 CHAR) NOT NULL,
		DATA_ALTERACAO		TIMESTAMP NOT NULL,
		DELETADO		    	NUMBER(1) NOT NULL
)';
	EXECUTE IMMEDIATE 'ALTER TABLE FORMULARIOS_COMPETENCIAS ADD CONSTRAINT KRS_INDICE_12031 PRIMARY KEY ( ID )';
	EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_FORMULARIOS_COMPETENCIAS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
	EXECUTE IMMEDIATE 'ALTER TABLE FORMULARIOS_COMPETENCIAS ADD CONSTRAINT KRS_INDICE_12032 FOREIGN KEY ( ID_FORMULARIOS_BLOCO ) REFERENCES FORMULARIOS_BLOCOS( ID ) NOT DEFERRABLE';
  end if;
END;
/


DECLARE
  COLUNA_EXISTENTE number := 0;  
BEGIN
  select count(*) into COLUNA_EXISTENTE from ALL_TAB_COLUMNS where upper(column_name) = 'ID_FORMULARIOS_COMPETENCIAS' and upper(table_name) = 'PARAMS_PERGUNTAS_FORMULARIOS';
  if (COLUNA_EXISTENTE = 0) then
      EXECUTE IMMEDIATE 'ALTER TABLE PARAMS_PERGUNTAS_FORMULARIOS ADD (ID_FORMULARIOS_COMPETENCIAS NUMBER(20,0))';
	EXECUTE IMMEDIATE 'ALTER TABLE PARAMS_PERGUNTAS_FORMULARIOS ADD CONSTRAINT KRS_INDICE_12033 FOREIGN KEY ( ID_FORMULARIOS_COMPETENCIAS ) REFERENCES FORMULARIOS_COMPETENCIAS( ID ) NOT DEFERRABLE';
  end if;
end;
/

DECLARE
  COLUNA_EXISTENTE number := 0;  
BEGIN
  select count(*) into COLUNA_EXISTENTE from ALL_TAB_COLUMNS where upper(column_name) = 'ID_USUARIO' and upper(table_name) = 'FORMULARIOS_BLOCOS';
  if (COLUNA_EXISTENTE = 0) then
        EXECUTE IMMEDIATE 'ALTER TABLE FORMULARIOS_BLOCOS ADD (ID_USUARIO NUMBER(20,0))';
        EXECUTE IMMEDIATE 'ALTER TABLE FORMULARIOS_COMPETENCIAS ADD (ID_USUARIO NUMBER(20,0))';
  end if;
end;


