----- ALTERAÇÃO DAS TABELAS DE PALAVRAS CHAVE PARA PERMITIR CARACTERES ESPECIAIS
ALTER TABLE PALAVRAS_CHAVE_APRENDIZ MODIFY PALAVRA VARCHAR2(30 CHAR);
ALTER TABLE PALAVRAS_CHAVE MODIFY PALAVRA VARCHAR2(30 CHAR);