DECLARE
    coluna_existente int:=0;
BEGIN
  SELECT count(*) into coluna_existente from all_tab_columns where table_name = 'REP_PARAMETROS_PROGRAMA_APR' and column_name = 'DATA_INICIO_MINIMA_GERAR_CERTIFICADO'; 

  if coluna_existente<=0 then
     EXECUTE IMMEDIATE 'ALTER TABLE REP_PARAMETROS_PROGRAMA_APR ADD DATA_INICIO_MINIMA_GERAR_CERTIFICADO timestamp(6)';
  else
     EXECUTE IMMEDIATE 'ALTER TABLE REP_PARAMETROS_PROGRAMA_APR DROP COLUMN DATA_INICIO_MINIMA_GERAR_CERTIFICADO';
     EXECUTE IMMEDIATE 'ALTER TABLE REP_PARAMETROS_PROGRAMA_APR ADD DATA_INICIO_MINIMA_GERAR_CERTIFICADO timestamp(6)';
  end if;
END;