CREATE TABLE CONTROLES_HIST_ESTAGIO_APRENDIZ
   (	
    ID NUMBER(19,0) NOT NULL ENABLE,
	CRIADO_POR VARCHAR2(255 CHAR),
	DATA_CRIACAO TIMESTAMP (6),
	DELETADO NUMBER(1,0),
	MODIFICADO_POR VARCHAR2(255 CHAR),
	DATA_ALTERACAO TIMESTAMP (6),
    ID_CONTRATO NUMBER(19,0),
	ID_LOCAL_CONTRATO NUMBER(19,0),
    ID_CONTRATO_ESTUDANTE_EMPRESA NUMBER(19,0),
    ID_ESTUDANTE NUMBER(19,0),
    DT_INICIO TIMESTAMP (6),
    DT_TERMINO TIMESTAMP (6),
    DT_RESCISAO TIMESTAMP (6),
    CODIGO_ESTUDANTE VARCHAR2(50 CHAR),
    CODIGO_TCE VARCHAR2(50 CHAR),
    CODIGO_DEPTO VARCHAR2(50 CHAR),
	ID_LEGADO VARCHAR2(200 CHAR)
    );
CREATE SEQUENCE SEQ_CONTROLES_HIST_ESTAGIO_APRENDIZ  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL;