DELETE FROM CAMPOS_OBRIGATORIOS_CONTRATO WHERE CAMPO = 'NATURALIDADE';

DELETE FROM CAMPOS_OBRIGATORIOS_CONTRATO WHERE CAMPO = 'NACIONALIDADE';

DELETE FROM CAMPOS_OBRIGATORIOS_CONTRATO WHERE CAMPO = 'RG';

DELETE FROM CAMPOS_OBRIGATORIOS_CONTRATO WHERE CAMPO = 'INFO_RG';