--PK-14683 - Integrar ICN com Kairos - Mapear Empresas ICN para Kairos
CREATE TABLE MAPEAMENTOS_EMPRESAS_ICN_KAIROS (
    ID                 NUMBER(20) NOT NULL,
    ID_LOCAL_CONTRATO  NUMBER(20) NOT NULL,
    ID_CONTRATO        NUMBER(20) NOT NULL,
    CNPJ               VARCHAR2(14 CHAR),
    UF                 VARCHAR2(2 CHAR),
    DATA_CRIACAO       TIMESTAMP NOT NULL,
    DATA_ALTERACAO     TIMESTAMP NOT NULL,
    CRIADO_POR         VARCHAR2(255 CHAR),
    MODIFICADO_POR     VARCHAR2(255 CHAR),
    DELETADO           NUMBER(1) DEFAULT 0
);
ALTER TABLE MAPEAMENTOS_EMPRESAS_ICN_KAIROS ADD CONSTRAINT KRS_INDICE_08020 PRIMARY KEY ( ID );
ALTER TABLE MAPEAMENTOS_EMPRESAS_ICN_KAIROS
    ADD CONSTRAINT KRS_INDICE_08022 FOREIGN KEY ( ID_LOCAL_CONTRATO )
        REFERENCES REP_LOCAIS_CONTRATO ( ID );
ALTER TABLE MAPEAMENTOS_EMPRESAS_ICN_KAIROS
    ADD CONSTRAINT KRS_INDICE_08023 FOREIGN KEY ( ID_CONTRATO )
        REFERENCES REP_CONTRATOS ( ID );
CREATE SEQUENCE SEQ_MAPEAMENTOS_EMPRESAS_ICN_KAIROS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;