CREATE OR REPLACE
VIEW SERVICE_VAGAS_DEV.V_PRORROGACOES_CONTR_EST_EMP (ID,
	NOME_EMPRESA,
	DATA_CRIACAO,
	TIPO_CONTRATO,
	SITUACAO_CONTRATO,
	CONTRATO_ID,
	LOCAL_CONTRATO_ID,
	LOC_CONTR_TIPO_LOGRADOURO,
	LOC_CONTR_ENDERECO,
	LOC_CONTR_BAIRRO,
	LOC_CONTR_NUM_ENDERECO,
	LOC_CONTR_COMPL_ENDERECO,
	LOC_CONTR_CEP,
	LOC_CONTR_CIDADE,
	LOC_CONTR_UF,
	CODIGO_ESTUDANTE,
	NOME_ESTUDANTE,
	DATA_VIGENCIA_TA,
	PRORROGADO_PARA,
	ALTERADO,
	PENDENTE_EMISSAO,
	PENDENTE_APROVACAO,
	SEQ_TA,
	TIPO_PRORROGACAO,
	ID_ESTUDANTE) AS (
SELECT
	CEE.ID,
	CEE.NOME_EMPRESA,
	MAX(TRUNC(TA.DATA_CRIACAO)) DATA_CRIACAO,
	CEE.TIPO_CONTRATO TIPO_CONTRATO,
	CEE.SITUACAO SITUACAO_CONTRATO,
	RLC.ID_CONTRATO CONTRATO_ID,
	RLC.ID LOCAL_CONTRATO_ID,
	RE.TIPO_LOGRADOURO LOC_CONTR_TIPO_LOGRADOURO,
	RE.ENDERECO LOC_CONTR_ENDERECO,
	RE.BAIRRO LOC_CONTR_BAIRRO,
	RE.NUMERO LOC_CONTR_NUM_ENDERECO,
	RE.COMPLEMENTO LOC_CONTR_COMPL_ENDERECO,
	RE.CEP LOC_CONTR_CEP,
	RE.CIDADE LOC_CONTR_CIDADE,
	RE.UF LOC_CONTR_UF,
	CEE.CODIGO_ESTUDANTE,
	CEE.NOME_ESTUDANTE,
	CEE.DATA_VIGENCIA_TA,
	CASE
		WHEN CEE.PENDENCIA_TA = 1 THEN CEE.DATA_PREVISTA_PRORROGACAO
		ELSE CEE.DATA_FINAL_ESTAGIO
	END PRORROGADO_PARA,
	CASE
		WHEN (
		SELECT
			MAX(TA.SEQ_TA)
		FROM
			CONTRATO_TA TA
		WHERE
			TA.DESCRICAO_CAMPO <> 'dataFinal'
			AND TA.ID_CONTR_EMP_EST = CEE.ID) IS NOT NULL THEN 1
		ELSE 0
	END ALTERADO,
	CEE.EMISSAO_DOCUMENTO_PENDENTE PENDENTE_EMISSAO,
	CEE.PENDENCIA_TA PENDENTE_APROVACAO,
	CEE.SEQ_TA SEQ_TA,
	COALESCE(CEE.PRORROGACAO_AUTOMATICA, 0) TIPO_PRORROGACAO,
	EST.ID ID_ESTUDANTE
FROM CONTRATO_TA TA
JOIN CONTRATOS_ESTUDANTES_EMPRESA CEE ON TA.ID_CONTR_EMP_EST = CEE.ID
JOIN REP_LOCAIS_CONTRATO RLC ON	CEE.ID_LOCAL_CONTRATO = RLC.ID
JOIN REP_LOCAIS_ENDERECOS RLE ON RLC.ID = RLE.ID_LOCAL_CONTRATO
JOIN REP_ENDERECOS RE ON RLE.ID_ENDERECO = RE.ID
JOIN REP_ESTUDANTES EST ON EST.ID = CEE.ID_ESTUDANTE
WHERE
	TA.DESCRICAO_CAMPO = 'dataFinal'
	AND (CEE.PENDENCIA_TA = 1
	OR CEE.EMISSAO_DOCUMENTO_PENDENTE = 1)
GROUP BY
	CEE.ID,
	CEE.SEQ_TA,
	CEE.NOME_EMPRESA,
	RLC.ID,
	RE.UF,
	RE.CIDADE,
	RE.CEP,
	RE.COMPLEMENTO,
	RE.ENDERECO,
	RE.BAIRRO,
	RE.NUMERO,
	CEE.CODIGO_ESTUDANTE,
	CEE.NOME_ESTUDANTE,
	CEE.DATA_FINAL_ESTAGIO,
	CEE.EMISSAO_DOCUMENTO_PENDENTE,
	CEE.PENDENCIA_TA,
	CEE.DATA_PREVISTA_PRORROGACAO,
	CEE.DATA_VIGENCIA_TA,
	RE.TIPO_LOGRADOURO,
	CEE.TIPO_CONTRATO,
	CEE.SITUACAO,
	RLC.ID_CONTRATO,
	COALESCE(CEE.PRORROGACAO_AUTOMATICA, 0),
	EST.ID
)