update QUALIFICACAO SET VULNERAVEL = 1, MODIFICADO_POR = 'PK-19284', DATA_ALTERACAO = SYSDATE WHERE NOME = 'ACOLHIDA';

update QUALIFICACAO SET VULNERAVEL = 1, MODIFICADO_POR = 'PK-19284', DATA_ALTERACAO = SYSDATE WHERE NOME = 'ACNUR';

update QUALIFICACAO SET VULNERAVEL = 1, MODIFICADO_POR = 'PK-19284', DATA_ALTERACAO = SYSDATE WHERE NOME = 'TRAMPO JUSTO';

update QUALIFICACAO SET VULNERAVEL = 1, MODIFICADO_POR = 'PK-19284', DATA_ALTERACAO = SYSDATE WHERE NOME = 'CONVIVENCIA E FORTALECIMENTO';

update QUALIFICACAO SET VULNERAVEL = 1, MODIFICADO_POR = 'PK-19284', DATA_ALTERACAO = SYSDATE WHERE NOME = 'OFICINA DE CRIATIVIDADE';

update QUALIFICACAO SET VULNERAVEL = 1, MODIFICADO_POR = 'PK-19284', DATA_ALTERACAO = SYSDATE WHERE NOME = 'VULNERAVEL';