ALTER TABLE CONTRATOS_CALENDARIOS DROP COLUMN ID_CONTR_EMP_EST CASCADE CONSTRAINTS;

ALTER TABLE CONTRATOS_CALENDARIOS ADD id_contrato NUMBER(20) NOT NULL;
ALTER TABLE contratos_calendarios
    ADD CONSTRAINT krs_indice_07202 FOREIGN KEY ( id_contrato )
        REFERENCES rep_contratos ( id );