ALTER TABLE ENVIOS_CAMPANHAS_POM ADD data_criacao TIMESTAMP;
ALTER TABLE ENVIOS_CAMPANHAS_POM ADD data_alteracao TIMESTAMP;
ALTER TABLE ENVIOS_CAMPANHAS_POM ADD criado_por VARCHAR2(255 CHAR);
ALTER TABLE ENVIOS_CAMPANHAS_POM ADD modificado_por VARCHAR2(255 CHAR);
ALTER TABLE ENVIOS_CAMPANHAS_POM ADD deletado NUMBER(1);