CREATE TABLE SERVICE_VAGAS_DEV.REP_LOCAIS_PESSOAS_COMPANY
(	
    ID_LOCAL_CONTRATO NUMBER NOT NULL ENABLE, 
    ID_PESSOA NUMBER NOT NULL ENABLE
);
COMMENT ON TABLE SERVICE_VAGAS_DEV.REP_LOCAIS_PESSOAS_COMPANY IS 'COMPANY_DEV:SERVICE_COMPANY_DEV:LOCAIS_PESSOAS:';