CREATE OR REPLACE VIEW ACOMP_VAGAS_NOVAS as
(
(SELECT DISTINCT RC.ID CONTRATO, VE.CODIGO_DA_VAGA, VE.PROCESSO_PERSONALIZADO VAGA_PP, 'E' TIPO_VAGA, VE.DATA_CRIACAO, VE.NUMERO_VAGAS, P.ID ID_PCD, RPUC.NUMERO_MIN_ESTUDANTES_TRIAGEM,
                 (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                 (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VIV.DELETADO = 0) TRIADOS,
                 (SELECT COUNT(ACOMP.ID) FROM ACOMPANHAMENTOS_VAGAS ACOMP WHERE ACOMP.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND ACOMP.DELETADO = 0) FOLLOW_UP,
                 (SELECT COUNT(ACOMP.ID) FROM ACOMPANHAMENTOS_VAGAS ACOMP WHERE ACOMP.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND ACOMP.DELETADO = 0 and ACOMP.TIPO_REGISTRO = 0) FOLLOW_UP_MANUAL,
                 (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                  WHERE E.ID_VAGA = VE.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                 (SELECT DISTINCT CASE WHEN (
                                                SELECT MIN(EP.DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                                                WHERE (EP.DATA_INICIO = SYSDATE + 1 OR EP.DATA_INICIO < SYSDATE) AND E.ID_VAGA = VE.CODIGO_DA_VAGA
                                                  AND NUMERO_MIN_ESTUDANTES_TRIAGEM > (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VE.CODIGO_DA_VAGA AND VIV.DELETADO = 0)) IS NOT NULL THEN 1 ELSE 0  END AS ALERTA
                  FROM ETAPAS_PERIODOS) ALERTA

 FROM VAGAS_ESTAGIO VE
          JOIN REP_LOCAIS_CONTRATO ON VE.ID_LOCAL_CONTRATO = REP_LOCAIS_CONTRATO.ID
          JOIN REP_CONTRATOS RC ON REP_LOCAIS_CONTRATO.ID_CONTRATO = RC.ID
          LEFT JOIN PCD_ESTAGIO P ON VE.ID = P.ID_VAGA_ESTAGIO
          JOIN REP_LOCAIS_ENDERECOS RLE on REP_LOCAIS_CONTRATO.ID = RLE.ID_LOCAL_CONTRATO
          JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
 WHERE (
             VE.ID_SITUACAO_VAGA = (SELECT ID FROM SITUACOES WHERE SIGLA = 'A')
         OR (
                         VE.ID_SITUACAO_VAGA = (SELECT ID FROM SITUACOES WHERE SIGLA = 'B')
                     AND not exists(select 1 from OCORRENCIAS_ESTAGIO OE where OE.ID_VAGA_ESTAGIO = VE.ID and OE.DELETADO = 0)
                 )
     )
   AND VE.DELETADO = 0)

UNION

(SELECT DISTINCT RC.ID CONTRATO, VA.CODIGO_DA_VAGA, NULL VAGA_PP, 'A' TIPO_VAGA, VA.DATA_CRIACAO, VA.NUMERO_VAGAS, P.ID ID_PCD, RPUC.NUMERO_MIN_ESTUDANTES_TRIAGEM,
                 (SELECT COUNT(VV.ID) FROM VINCULOS_VAGA VV WHERE VV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VV.SITUACAO_VINCULO = 1 AND VV.DELETADO = 0) ENCAMINHADOS,
                 (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VIV.DELETADO = 0) TRIADOS,
                 (SELECT COUNT(ACOMP.ID) FROM ACOMPANHAMENTOS_VAGAS ACOMP WHERE ACOMP.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND ACOMP.DELETADO = 0) FOLLOW_UP,
                 (SELECT COUNT(ACOMP.ID) FROM ACOMPANHAMENTOS_VAGAS ACOMP WHERE ACOMP.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND ACOMP.DELETADO = 0 AND ACOMP.TIPO_REGISTRO = 0) FOLLOW_UP_MANUAL,
                 (SELECT MIN(DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                  WHERE E.ID_VAGA = VA.CODIGO_DA_VAGA) DATA_PROCESSO_SELETIVO,
                 (SELECT DISTINCT CASE WHEN (
                                                SELECT MIN(EP.DATA_INICIO) FROM ETAPAS_PERIODOS EP INNER JOIN ETAPAS_PROCESSO_SELETIVO E on EP.ID_ETAPA_PROCESSO_SELETIVO = E.ID
                                                WHERE (EP.DATA_INICIO = SYSDATE + 1 OR EP.DATA_INICIO < SYSDATE) AND E.ID_VAGA = VA.CODIGO_DA_VAGA
                                                  AND NUMERO_MIN_ESTUDANTES_TRIAGEM > (SELECT COUNT(VIV.ID) FROM VINCULOS_VAGA VIV  WHERE VIV.CODIGO_VAGA = VA.CODIGO_DA_VAGA AND VIV.DELETADO = 0)) IS NOT NULL THEN 1 ELSE 0 END AS ALERTA
                  FROM ETAPAS_PERIODOS) ALERTA

 FROM VAGAS_APRENDIZ VA
          JOIN REP_LOCAIS_CONTRATO ON VA.ID_LOCAL_CONTRATO = REP_LOCAIS_CONTRATO.ID
          JOIN REP_CONTRATOS RC ON REP_LOCAIS_CONTRATO.ID_CONTRATO = RC.ID
          LEFT JOIN PCD_APRENDIZ P ON P.ID_VAGA_APRENDIZ = VA.ID
          JOIN REP_LOCAIS_ENDERECOS RLE on REP_LOCAIS_CONTRATO.ID = RLE.ID_LOCAL_CONTRATO
          JOIN REP_PARAMETROS_UNIDADES_CIEE RPUC ON RPUC.ID_UNIDADE_CIEE = RLE.ID_UNIDADE_CIEE
 WHERE (
             VA.ID_SITUACAO_VAGA = (SELECT ID FROM SITUACOES WHERE SIGLA = 'A')
         OR (
                         VA.ID_SITUACAO_VAGA = (SELECT ID FROM SITUACOES WHERE SIGLA = 'B')
                     AND not exists(select 1 from OCORRENCIAS_APRENDIZ OA where OA.ID_VAGA_APRENDIZ = VA.ID and OA.DELETADO = 0)
                 )
     ) AND VA.DELETADO = 0)
)
;