CREATE OR REPLACE FUNCTION CONVERSAO_SEMESTRE(
    V_PERIODO NUMBER,
    V_TIPO_DURACAO VARCHAR2,
    V_CONCLUIDO NUMBER := 1
)
RETURN NUMBER
IS
BEGIN
    IF V_TIPO_DURACAO = 'Anual' AND (EXTRACT(MONTH FROM SYSDATE) > 6 OR V_CONCLUIDO = 1) THEN
        RETURN V_PERIODO * 2;
    ELSIF V_TIPO_DURACAO = 'Anual' AND EXTRACT(MONTH FROM SYSDATE) <= 6 THEN
        RETURN V_PERIODO * 2 - 1;
    ELSIF V_TIPO_DURACAO = 'Mensal' THEN
        RETURN CEIL(V_PERIODO / 6);
    ELSE
        RETURN V_PERIODO;
    END IF;
END;