CREATE OR REPLACE VIEW V_APOLICES_EMPRESAS AS 
  SELECT
        AE.ID,        
        AE.NUMERO AS CODIGO_APOLICE,
        SEG.NOME AS SEGURADORA,
        AE.DATA_INICIO,
        AE.DATA_TERMINO,
        VAE.MORTE AS VALOR_MORTE,
        VAE.INVALIDEZ AS VALOR_INVALIDEZ
  FROM REP_APOLICES_EMPRESAS AE
  LEFT JOIN REP_SEGURADORAS SEG ON AE.ID_SEGURADORA = SEG.ID
  LEFT JOIN REP_VALORES_APOLICES_EMPRESAS VAE ON VAE.ID = AE.ID_VALORES_APOLICES_EMPRESAS;