UPDATE CLASSIFICACOES_PARAMETROS_ITENS
	SET FAIXA = '$<5'
	WHERE INDICADOR = 'SEM_RETORNO_PENDENTE' AND FAIXA = '%<5';

UPDATE CLASSIFICACOES_PARAMETROS_ITENS
	SET CRIADO_POR = 'CARGA', MODIFICADO_POR = 'CARGA'
	WHERE DELETADO = 0;