alter table TRIAGENS_ESTUDANTES
    modify ENDERECO_CAMPUS_GEOHASH VARCHAR2(20)
;

alter table TRIAGENS_ESTUDANTES
    add ENDERECO_GEOHASHS GEOHASHS_TYP
NESTED TABLE ENDERECO_GEOHASHS store as n_endereco_geohashs_est
;