

INSERT INTO SITUACOES_CURSOS_MTE (ID, DESCRICAO, DISPONIVEL_CONTRATACAO, SITUACAO, DELETADO, DATA_CRIACAO, DATA_ALTERACAO, CRIADO_POR, MODIFICADO_POR) 
VALUES ('9', 'INATIVO', '0', '1', '0', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 'MIGRACAO', 'MIGRACAO')
