CREATE TABLE REP_TIPOS_DEPENDENTES_STUDENT
(
    ID             NUMBER             NOT NULL ENABLE,
    DESCRICAO      VARCHAR2(200 BYTE) NOT NULL ENABLE,
    DATA_CRIACAO   TIMESTAMP(6)       NOT NULL ENABLE,
    DATA_ALTERACAO TIMESTAMP(6)       NOT NULL ENABLE,
    CRIADO_POR     VARCHAR2(255 BYTE),
    MODIFICADO_POR VARCHAR2(255 BYTE),
    DELETADO       NUMBER(1, 0),
    CODIGO         NUMBER(3)
);

ALTER TABLE REP_TIPOS_DEPENDENTES_STUDENT ADD CONSTRAINT KRS_INDICE_09820 PRIMARY KEY (ID) ENABLE;

COMMENT ON TABLE REP_TIPOS_DEPENDENTES_STUDENT IS 'STUDENT_DEV:SERVICE_STUDENT_DEV:TIPOS_DEPENDENTES:id';