INSERT INTO QUALIFICACAO
(ID, NOME, NIVEL, SITUACAO, NUMERO_QUESTOES, NOTA_MINIMA, NOTA_MAXIMA, CRIADO_POR, DATA_CRIACAO, DATA_ALTERACAO, MODIFICADO_POR, DELETADO, TIPO)
SELECT SEQ_QUALIFICACAO.nextval,'Cota social em empresa', null, 1, null, null, null, 'PK-21189' ,current_timestamp, current_timestamp, 'PK-21189', 0, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM QUALIFICACAO WHERE NOME = 'Cota social em empresa' AND TIPO = 0);

INSERT INTO QUALIFICACAO
(ID, NOME, NIVEL, SITUACAO, NUMERO_QUESTOES, NOTA_MINIMA, NOTA_MAXIMA, CRIADO_POR, DATA_CRIACAO, DATA_ALTERACAO, MODIFICADO_POR, DELETADO, TIPO)
SELECT SEQ_QUALIFICACAO.nextval,'Cota social no CIEE', null, 1, null, null, null, 'PK-21189' ,current_timestamp, current_timestamp, 'PK-21189', 0, 0 FROM DUAL
WHERE NOT EXISTS(SELECT 1 FROM QUALIFICACAO WHERE NOME = 'Cota social no CIEE' AND TIPO = 0);