DECLARE
    tabela_existente int:=0;
BEGIN
  SELECT count(*) into tabela_existente FROM all_tables where table_name = 'INSTRUTOR';

if tabela_existente <= 0 then
     EXECUTE IMMEDIATE '	
    create table INSTRUTOR (
        ID                  NUMBER(20,0) NOT NULL,
        ID_SECRETARIA   	NUMBER(20,0) NOT NULL,
        CPF			        VARCHAR2(255 CHAR),
        NOME			    VARCHAR2(255 CHAR),
        NOME_SOCIAL		    VARCHAR2(255 CHAR),
        EMAIL				VARCHAR2(100 CHAR),
        TELEFONE			VARCHAR2(60 CHAR),
        DATA_CRIACAO 		TIMESTAMP,
        DATA_ALTERACAO 		TIMESTAMP,
        CRIADO_POR 			VARCHAR2(255 CHAR),
        MODIFICADO_POR 		VARCHAR2(255 CHAR),
        DELETADO 			NUMBER(1) DEFAULT 0
    )';
   
    EXECUTE IMMEDIATE 'ALTER TABLE INSTRUTOR ADD CONSTRAINT KRS_INDICE_12034 PRIMARY KEY(ID)';

    EXECUTE IMMEDIATE 'CREATE SEQUENCE SEQ_INSTRUTOR  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE';
  end if;
END;