-- Tabelas
ALTER TABLE FILA_TRIAGEM_ESTUDANTE  PARALLEL 10;
ALTER TABLE FILA_TRIAGEM_ESTUDANTE INMEMORY PRIORITY NONE MEMCOMPRESS FOR QUERY LOW ;

CREATE TABLE FILA_TRIAGEM_VAGA_ESTAGIO
(	ID NUMBER NOT NULL ENABLE,
     ID_VAGA NUMBER(20,0) NOT NULL ENABLE,
     DATA_CRIACAO DATE NOT NULL ENABLE,
     CONSTRAINT PK_FILA_TRIAGEM_VAGA_ESTAGIO_01 PRIMARY KEY (ID)
);


CREATE TABLE FILA_TRIAGEM_VAGA_APRENDIZ
(	ID NUMBER NOT NULL ENABLE,
     ID_VAGA NUMBER(20,0) NOT NULL ENABLE,
     DATA_CRIACAO DATE NOT NULL ENABLE,
     CONSTRAINT PK_FILA_TRIAGEM_APRENDIZ_01 PRIMARY KEY (ID)
);