ALTER TABLE PARAMETROS_IE MODIFY MSG_ADICIONAL_BACKOFFICE VARCHAR2(3000 CHAR);
ALTER TABLE PARAMETROS_IE MODIFY MSG_ADICIONAL_EMPRESA VARCHAR2(3000 CHAR);
ALTER TABLE PARAMETROS_IE MODIFY MSG_ADICIONAL_ESTUDANTE VARCHAR2(3000 CHAR);