CREATE OR REPLACE VIEW V_ICN_EMPRESA AS 
  SELECT DISTINCT ROWNUM AS ID,
        ICE.CNPJ,
        ICE.RAZAO_SOCIAL,
        END.UF,
        C.ID AS ID_CONTRATO,
        C.SITUACAO_CONTRATO,
        CC.CENTRALIZAR_ADM_FINANCEIRA,
        C.TIPO_SERVICO,
        SPG.CATEGORIA,
        C.DATA_CRIACAO,
        CVC.TIPO_CONTRIBUICAO,
        CVC.VALOR_CI,
        RPL.NOME AS REPRESENTANTE_LEGAL,
        RPA.NOME AS REPRESENTANTE_ADM,
        END.CEP,
        END.TIPO_LOGRADOURO,
        END.ENDERECO,
        END.NUMERO,
        END.COMPLEMENTO,
        END.BAIRRO,
        END.CIDADE,
        ICE.ID_EMPRESA,
        CC.DATA_INICIO_CONTRATO,
        CC.VALIDADE_CONTRATO,
        ICE.TIPO_EMPRESA,
        C.DATA_ALTERACAO,
        CC.ID_UNIDADE_CIEE,
        CUC.ID_UNIDADE_ADMINISTRATIVA,
        CUC.UF_UNIDADE_CIEE,
        CC.DATA_ASSINATURA_CONTRATO,
        CCE.ATENDE_AUTONOMO,
        CCE.POSSUI_ADITIVO_PE,
        C.ID_TIPO_SIS_PGA_ESTAGIARIO,
        C.ID_FORMA_CONTRATACAO,
        
        -- Seguradora
        CASE WHEN C.ID_APOLICES_CIEE IS NULL THEN
               'EMPRESA' ELSE 'CIEE' END AS TIPO_APOLICE,
               
        CASE WHEN C.ID_APOLICES_CIEE IS NULL THEN
               APE.CODIGO_APOLICE ELSE APC.CODIGO_APOLICE END AS CODIGO_APOLICE,
        
        CASE WHEN C.ID_APOLICES_CIEE IS NULL THEN
               APE.SEGURADORA ELSE APC.SEGURADORA END AS SEGURADORA,
               
        CASE WHEN C.ID_APOLICES_CIEE IS NULL THEN
               APE.DATA_INICIO ELSE APC.DATA_INICIO END AS INICIO_APOLICE,
               
        CASE WHEN C.ID_APOLICES_CIEE IS NULL THEN
               APE.DATA_TERMINO ELSE APC.DATA_TERMINO END AS TERMINO_APOLICE,
               
        CASE WHEN C.ID_APOLICES_CIEE IS NULL THEN
               APE.VALOR_MORTE ELSE APC.VALOR_MORTE END AS VALOR_MORTE
                       
  FROM REP_CONTRATOS C
  INNER JOIN REP_INFO_CONTRATO_EMPRESAS ICE ON ICE.ID_CONTRATO = C.ID AND ICE.PRINCIPAL = 1
  INNER JOIN REP_CONFIGURACAO_CONTRATOS CC ON C.ID = CC.ID_CONTRATO
  INNER JOIN REP_LOCAIS_CONTRATO LC ON LC.ID_CONTRATO = C.ID
  INNER JOIN REP_LOCAIS_ENDERECOS LE ON LE.ID_LOCAL_CONTRATO = LC.ID AND LE.ENDERECO_PRINCIPAL = 1
  INNER JOIN REP_ENDERECOS END ON END.ID = LE.ID_ENDERECO
  INNER JOIN V_ICN_CONTRATO_UNIDADE_CIEE CUC ON CUC.ID_CONTRATO = C.ID
  INNER JOIN V_ICN_CONTRATO_VALOR_CI CVC ON CVC.ID_CONTRATO = C.ID
  INNER JOIN REP_CONFIG_CONTRATOS_ESTAGIO_COMPANY CCE ON CC.ID = CCE.ID AND CCE.ATENDE_AUTONOMO = 1
  INNER JOIN REP_TIPOS_SIS_PGA_ESTAGIARIO_COMPANY SPG ON C.ID_TIPO_SIS_PGA_ESTAGIARIO = SPG.ID
  INNER JOIN REP_REPRESENTANTES_CONTRATO RCA ON RCA.ID_CONTRATO = C.ID AND RCA.TIPO = 'REPRESENTANTE ADMINISTRATIVO'
  INNER JOIN REP_REPRESENTANTES RPA ON RPA.ID = RCA.ID_REPRESENTANTE
  INNER JOIN REP_REPRESENTANTES_CONTRATO RCL ON RCL.ID_CONTRATO = C.ID AND RCL.TIPO = 'REPRESENTANTE LEGAL'
  INNER JOIN REP_REPRESENTANTES RPL ON RPL.ID = RCL.ID_REPRESENTANTE       
  LEFT JOIN V_APOLICES_CIEE APC ON APC.ID = C.ID_APOLICES_CIEE
  LEFT JOIN V_APOLICES_EMPRESAS APE ON APE.ID = C.ID_APOLICES_EMPRESAS;