BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE REP_DOCUMENTO_ESTUDANTE_STUDENT
    (
        ID_ESTUDANTE NUMBER(19,0) NOT NULL ENABLE, 
        ID_DOCUMENTO NUMBER(19,0) NOT NULL ENABLE, 
        TIPO_DOCUMENTO VARCHAR2(100 CHAR) 
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = 955 THEN
            RAISE;
        END IF;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'ALTER TABLE REP_DOCUMENTO_ESTUDANTE_STUDENT ADD CONSTRAINT KRS_INDICE_10560 PRIMARY KEY (ID_ESTUDANTE, ID_DOCUMENTO)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = 2260 THEN
            RAISE;
        END IF;
END;
/
COMMENT ON TABLE SERVICE_VAGAS_DEV.REP_DOCUMENTO_ESTUDANTE_STUDENT  IS 'STUDENT_DEV:SERVICE_STUDENT_DEV:DOCUMENTO_ESTUDANTE:';