-- Cria coluna de descrição do curso para as tabela de contratos_cursos_capacitacao.


ALTER TABLE PRE_CONTRATOS_CURSOS_CAPACITACAO ADD DURACAO_CURSO VARCHAR2(150 CHAR);

ALTER TABLE CONTRATOS_CURSOS_CAPACITACAO ADD DURACAO_CURSO VARCHAR2(150 CHAR);