CREATE MATERIALIZED VIEW MV_VITRINE_VAGAS
            PARALLEL 8
            BUILD IMMEDIATE
    REFRESH FORCE
        ON DEMAND
AS
SELECT VT.ID_ESTADO,
       VT.DATA_ALTERACAO,
       VE.ID AS ID_VAGA,
       VT.CODIGO_VAGA,
       CASE WHEN (EXISTS(SELECT 1 FROM PCD_ESTAGIO PCD WHERE PCD.ID_VAGA_ESTAGIO = VE.ID AND PCD.DELETADO = 0)) THEN 'PCD' ELSE 'ESTAGIO' END AS TIPO_VAGA,
       COALESCE(RLC.RAZAO_SOCIAL, RLC.NOME) AS NOME_EMPRESA,
       AP.DESCRICAO_AREA_PROFISSIONAL AREA_PROFISSIONAL,
       NULL AREA_ATUACAO,
       VE.VALOR_BOLSA_FIXO VALOR_BOLSA,
       VE.DESCRICAO,
       VT.ORDEM
FROM VITRINE_VAGAS VT
         INNER JOIN VAGAS_ESTAGIO VE ON VE.CODIGO_DA_VAGA = VT.CODIGO_VAGA
         INNER JOIN SITUACOES S ON S.ID = VE.ID_SITUACAO_VAGA
         INNER JOIN REP_LOCAIS_CONTRATO RLC ON RLC.ID = VE.ID_LOCAL_CONTRATO
         INNER JOIN REP_AREAS_PROFISSIONAIS AP ON AP.CODIGO_AREA_PROFISSIONAL = VE.CODIGO_AREA_PROFISSIONAL
WHERE VT.SITUACAO = 1
  AND S.SIGLA IN ('A', 'B')
  AND (CURRENT_DATE BETWEEN VT.DATA_PUBLICACAO_INICIO AND VT.DATA_PUBLICACAO_FIM)

UNION ALL

SELECT VT.ID_ESTADO,
       VT.DATA_ALTERACAO,
       VA.ID AS ID_VAGA,
       VT.CODIGO_VAGA,
       CASE WHEN (EXISTS(SELECT 1 FROM PCD_APRENDIZ PCD WHERE PCD.ID_VAGA_APRENDIZ = VA.ID AND PCD.DELETADO = 0)) THEN 'PCD' ELSE 'APRENDIZ' END AS TIPO_VAGA,
       COALESCE(RLC.RAZAO_SOCIAL, RLC.NOME) AS NOME_EMPRESA,
       NULL AREA_PROFISSIONAL,
       AA.DESCRICAO_AREA_ATUACAO AREA_ATUACAO,
       VA.VALOR_SALARIO VALOR_BOLSA,
       VA.DESCRICAO,
       VT.ORDEM
FROM VITRINE_VAGAS VT
         INNER JOIN VAGAS_APRENDIZ VA ON VA.CODIGO_DA_VAGA = VT.CODIGO_VAGA
         INNER JOIN SITUACOES S ON S.ID = VA.ID_SITUACAO_VAGA
         INNER JOIN REP_LOCAIS_CONTRATO RLC ON RLC.ID = VA.ID_LOCAL_CONTRATO
         INNER JOIN CURSOS_CAPACITACAO CC ON CC.ID = VA.ID_CURSO_CAPACITACAO
         INNER JOIN AREAS_ATUACAO_APRENDIZ AA ON AA.ID = CC.ID_AREA_ATUACAO
WHERE VT.SITUACAO = 1
  AND S.SIGLA IN ('A', 'B')
  AND (CURRENT_DATE BETWEEN VT.DATA_PUBLICACAO_INICIO AND VT.DATA_PUBLICACAO_FIM);