ALTER TABLE dados_pagamentos_contratos_estudantes_empresas MODIFY SITUACAO NUMBER(1,0) DEFAULT 0;
ALTER TABLE dados_pagamentos_contratos_estudantes_empresas ADD MOTIVO VARCHAR2(255 CHAR);
COMMENT ON COLUMN dados_pagamentos_contratos_estudantes_empresas.situacao IS
    'Enum:
0 - Não validado
1 - Válido
2 - Inválido';

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA MODIFY SITUACAO_DADOS_BANCARIOS NUMBER(1,0) DEFAULT 0;

ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA ADD MOTIVO_DADOS_BANCARIOS VARCHAR2(255 CHAR);
COMMENT ON COLUMN CONTRATOS_ESTUDANTES_EMPRESA.SITUACAO_DADOS_BANCARIOS IS

    'Enum:
0 - Não validado
1 - Válido
2 - Inválido';


ALTER TABLE REP_DEPENDENTES_STUDENT ADD SITUACAO_DADOS_BANCARIOS NUMBER(1,0) DEFAULT 0;

ALTER TABLE REP_DEPENDENTES_STUDENT ADD MOTIVO_DADOS_BANCARIOS VARCHAR2(255 CHAR);
COMMENT ON COLUMN REP_DEPENDENTES_STUDENT.SITUACAO_DADOS_BANCARIOS IS
    'Enum:
0 - Não validado
1 - Válido
2 - Inválido';