-- Altera colunas de complementos de endereço das tabelas PRE_CONTRATOS_ESTUDANTES_EMPRESA e CONTRATOS_ESTUDANTES_EMPRESA.


ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA MODIFY COMPLEMENTO_END_ESTUDANTE VARCHAR2(200 CHAR);
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA MODIFY COMPLEMENTO_END_ESTUDANTE VARCHAR2(200 CHAR);

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA MODIFY COMPLEMENTO_CAMPUS	VARCHAR2(50 CHAR);
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA MODIFY COMPLEMENTO_CAMPUS	VARCHAR2(50 CHAR);

ALTER TABLE PRE_CONTRATOS_ESTUDANTES_EMPRESA MODIFY COMPLEMENTO_EMPRESA	VARCHAR2(50 CHAR);
ALTER TABLE CONTRATOS_ESTUDANTES_EMPRESA MODIFY COMPLEMENTO_EMPRESA	VARCHAR2(50 CHAR);