ALTER TABLE REP_CONFIGURACOES_FOLHAS_PAGAMENTOS_FINANCEIRO DROP COLUMN ID_LOCAL_CONTRATO CASCADE CONSTRAINTS;
ALTER TABLE REP_CONFIGURACOES_FOLHAS_PAGAMENTOS_FINANCEIRO ADD ID_CONTRATO NUMBER(20) NULL;
ALTER TABLE rep_configuracoes_folhas_pagamentos_financeiro
    ADD CONSTRAINT krs_indice_07183 FOREIGN KEY ( id_contrato )
        REFERENCES rep_contratos ( id );