UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Ajuda de custo escolar';

UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Ambulatorio medico';

UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Auxilio transporte %';

UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Cesta basica';

UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Convenio com farmacia';

UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Curso de ingles';

UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Lanche na empresa';

UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Onibus da empresa';

UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Reembolso de combustivel';

UPDATE BENEFICIOS
SET DELETADO = 1
WHERE DESCRICAO = 'Auxilio transporte mensal';
