--PK-14689 - Integrar ICN com Kairos - integrar contratos ao Kairos
CREATE TABLE LOGS_INTEGRACOES_CONTRATOS_KAIROS (
    ID NUMBER(20) NOT NULL,
    CIEE_RESPONSAVEL NUMBER(1),
    UF_CIEE_AUTONOMO VARCHAR(2 CHAR),
    NUMERO_TCE_AUTONOMO NUMBER(20),
    CPF_ESTUDANTE VARCHAR(11 CHAR),
    NOME_ESTUDANTE VARCHAR(255 CHAR),
    CNPJ_EMPRESA VARCHAR(14 CHAR),
    NOME_EMPRESA VARCHAR(255 CHAR),
    DATA_INICIO_TCE TIMESTAMP,
    DATA_TERMINO_TCE TIMESTAMP,
    DATA_RESCISAO_TCE TIMESTAMP,
    MOTIVO_RESCISAO_TCE VARCHAR(300 CHAR),
    DATA_CANCELAMENTO_TCE TIMESTAMP,
    MOTIVO_CANCELAMENTO_TCE VARCHAR(300 CHAR),
    VALOR_BOLSA NUMBER(10,2),
    BANCO_PAGAMENTO VARCHAR(10 CHAR),
    AGENCIA_PAGAMENTO NUMBER(4),
    DV_AGENCIA_PAGAMENTO NUMBER(1),
    CONTA_PAGAMENTO NUMBER(15),
    DV_CONTA_PAGAMENTO NUMBER(1),
    NOME_SUPERVISOR VARCHAR(150 CHAR),
    CARGO_SUPERVISOR VARCHAR(150 CHAR),
    EMAIL_SUPERVISOR VARCHAR(150 CHAR),
    HORARIO_ESTAGIO TIMESTAMP,
    ATIVIDADE_ESTAGIO VARCHAR(5 CHAR),
    ENDERECO_LOCAL_ESTAGIO VARCHAR(150 CHAR),
    BAIRRO_LOCAL_ESTAGIO VARCHAR(100 CHAR),
    CIDADE_LOCAL_ESTAGIO VARCHAR(100 CHAR),
    CEP_LOCAL_ESTAGIO VARCHAR(8 CHAR),
    DATA_PROCESSADO TIMESTAMP,
    CODIGO_ESTUDANTE NUMBER(20),
    SITUACAO NUMBER(1),
    CODIGO_CONTRATO NUMBER(20),
    NUMERO_TCE_KAIROS NUMBER(20),
    ERRO CLOB,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    CRIADO_POR VARCHAR2(255 CHAR),
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DELETADO NUMBER(1) DEFAULT 0
);
ALTER TABLE LOGS_INTEGRACOES_CONTRATOS_KAIROS ADD CONSTRAINT KRS_INDICE_08061 PRIMARY KEY ( ID );
COMMENT ON COLUMN LOGS_INTEGRACOES_CONTRATOS_KAIROS.CIEE_RESPONSAVEL IS
    'ENUM:
0-SP
1-RJ';
COMMENT ON COLUMN LOGS_INTEGRACOES_CONTRATOS_KAIROS.SITUACAO IS
    'ENUM:
0-EFETIVADO
1-MANUAL';
CREATE SEQUENCE SEQ_LOGS_INTEGRACOES_CONTRATOS_KAIROS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--
CREATE TABLE CONTROLES_INTEGRACOES_CONTRATOS_KAIROS (
    ID NUMBER(20) NOT NULL,
    CHAVE_ICN VARCHAR(20 CHAR),
    UF_ICN VARCHAR(2 CHAR),
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    CRIADO_POR VARCHAR2(255 CHAR),
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DELETADO NUMBER(1) DEFAULT 0
);
ALTER TABLE CONTROLES_INTEGRACOES_CONTRATOS_KAIROS ADD CONSTRAINT KRS_INDICE_08062 PRIMARY KEY ( ID );
CREATE SEQUENCE SEQ_CONTROLES_INTEGRACOES_CONTRATOS_KAIROS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;