--PK-13461 - Implementar Necessidade de controle de Tickets
ALTER TABLE REP_CONFIGURACAO_CONTRATOS ADD LIMITE_TICKET NUMBER(1) DEFAULT 0;
COMMENT ON COLUMN REP_CONFIGURACAO_CONTRATOS.LIMITE_TICKET IS
    '0 - NAO - DEFAULT
1 - SIM';