CREATE MATERIALIZED VIEW MV_CURSOS_AREA_PROFISSIONAL
            PARALLEL 4
            BUILD IMMEDIATE
    REFRESH FORCE ON DEMAND
AS
SELECT distinct C.CODIGO_CURSO, AP.CODIGO_AREA_PROFISSIONAL
FROM REP_AREAS_ATUACAO_ESTAGIO A
         INNER JOIN REP_AREAS_PROFISSIONAL_ATUACAO AP
                    ON AP.CODIGO_AREA_ATUACAO = A.CODIGO_AREA_ATUACAO
         INNER JOIN REP_AREAS_ATUACAO_CURSOS AC ON AC.CODIGO_AREA_ATUACAO = A.CODIGO_AREA_ATUACAO
         INNER JOIN REP_CURSOS C ON AC.CODIGO_CURSO = C.CODIGO_CURSO;