--PK-14685 - Integrar ICN com Kairos - integrar estagiários ao Kairos
CREATE TABLE LOGS_ICN_INTEGRACOES_ESTAGIARIOS_KAIROS (
    ID NUMBER(20) NOT NULL,
    CIEE_RESPONSAVEL NUMBER(1),
    UF_ESTUDANTE VARCHAR(2 CHAR),
    CPF_ESTUDANTE VARCHAR(11 CHAR),
    NOME_ESTUDANTE VARCHAR(255 CHAR),
    DATA_NASCIMENTO_ESTUDANTE TIMESTAMP,
    DATA_PROCESSADO TIMESTAMP,
    CODIGO_ESTUDANTE NUMBER(20),
    SITUACAO VARCHAR(255 CHAR),
    ERRO CLOB,
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    CRIADO_POR VARCHAR2(255 CHAR),
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DELETADO NUMBER(1) DEFAULT 0
);
ALTER TABLE LOGS_ICN_INTEGRACOES_ESTAGIARIOS_KAIROS ADD CONSTRAINT KRS_INDICE_08040 PRIMARY KEY ( ID );
COMMENT ON COLUMN LOGS_ICN_INTEGRACOES_ESTAGIARIOS_KAIROS.CIEE_RESPONSAVEL IS
    'ENUM:
0-SP
1-RJ';
CREATE SEQUENCE SEQ_LOGS_ICN_INTEGRACOES_ESTAGIARIOS_KAIROS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;
--
CREATE TABLE CONTROLES_ICN_INTEGRACOES_ESTAGIARIOS_KAIROS (
    ID NUMBER(20) NOT NULL,
    CHAVE_ICN VARCHAR(20 CHAR),
    UF_ICN VARCHAR(2 CHAR),
    DATA_CRIACAO TIMESTAMP NOT NULL,
    DATA_ALTERACAO TIMESTAMP NOT NULL,
    CRIADO_POR VARCHAR2(255 CHAR),
    MODIFICADO_POR VARCHAR2(255 CHAR),
    DELETADO NUMBER(1) DEFAULT 0
);
ALTER TABLE CONTROLES_ICN_INTEGRACOES_ESTAGIARIOS_KAIROS ADD CONSTRAINT KRS_INDICE_08041 PRIMARY KEY ( ID );
CREATE SEQUENCE SEQ_CONTROLES_ICN_INTEGRACOES_ESTAGIARIOS_KAIROS MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOKEEP NOSCALE GLOBAL;