-- Cria coluna de indicacao se possui rodape e o id do rodape na tabela de parametros_contratos_ie.


ALTER TABLE PARAMETROS_CONTRATOS_IE ADD ID_RODAPE NUMBER(20);

ALTER TABLE PARAMETROS_CONTRATOS_IE ADD POSSUI_RODAPE_PROPRIO NUMBER(1,0) DEFAULT 0;
COMMENT ON COLUMN PARAMETROS_CONTRATOS_IE.POSSUI_RODAPE_PROPRIO 
     IS 'ENUM:
0-SIM
1-NAO';

